### ISSUE TITLE
Error when using internal events in a guard expression

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1014]
With the following statechart:

    internal:
      event evtA
     
    +----------+   [evtA]       +----------+
    | State A  |--------------->| StateB   |
    +----------+                +----------+

The usage of `[evtA]` produces an error underlining when the text field is __active__, saying `could not resolve reference to EObject evtA`, implying the object is not known. When the field loses focus and is __inactive__, __no__ error marker is shown in any way. The construct works perfectly when simulated.

**Comment by andreasmuelder** [comment]
This seems to be fixed as a side effect to PR #1023
