### ISSUE TITLE
 CPPDefaultFeatureValueProvider is not reexported

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#1026]
I've tried the example @jdicks posted on your website (https://blogs.itemis.com/en/how-to-standalone-generate-statechart-code-for-continuous-integration-builds). Unfortunately it does not work with the C++ generator. The reason is that the package of the CPPDefaultFeatureValueProvider is not reexported in the plugins manifest file.

**Comment by andreasmuelder** [comment]
The example is outdated, closing this for now. If you still require the export feel free to open a pull request
