### ISSUE TITLE
Saving big model file takes too long

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#1030]
Take the model from manual-tests/org.yakindu.sct.test.manual/testmodels/big_file.sct

Change something and save it.

The "Building workspace" job starts and hangs at "invoking build participants" for a long time. This is way too long.

**Comment by tkutz** [comment]
Most time seems to be spent for painting the figures again.

<img width="1146" alt="bildschirmfoto 2016-10-13 um 09 42 04" src="https://cloud.githubusercontent.com/assets/2589669/19340486/60852354-9129-11e6-98c2-4959f82150e8.png">

**Comment by andreasmuelder** [comment]
@tkutz Can you still reproduce this with the 2.8 release? At least on my windows machine it is quite fast.

**Comment by andreasmuelder** [comment]
@tkutz is this still an issue?

**Comment by BeckmaR** [comment]
@andreasmuelder Yakindu/sctpro#773 says yes, it is

**Comment by andreasmuelder** [comment]
Closing this, fixed in Pro
