### ISSUE TITLE
Wrong behavior when existing statename is used as guard on a transition

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1043]
When the user has
    interface sensor:
        in event measure

and a state named `measure` and then proceeds to use `measure` as transition guard (instead of `sensor.measure`), SCT goes in a loop in TypeInferrer until it finally throws a StackOverflowError in the console. After some time, the validation is done and SCT is usable again, but not showing an Error Marker.
The problem view only shows `Error executing EValidator`.

Steps to reproduce:
* Create new Statechart Model
* Create transition from `StateA` back to `StateA`
* In the transition guard, write `StateA`.

Also, SCT has no problem with the user declaring

    internal:
        event StateA

**Comment by tkutz** [comment]
We have a recursion after adding the shortcut method ```InferenceResult infer(EObject) ```, in order to avoid calling ```InferenceResult infer(EObject, IValidationIssueAcceptor) ``` with an null acceptor from outside. However "infer" just calls "inferTypeDispatch", which fallbacks to "infer" when no other implementation is found => Recursion

**Comment by tkutz** [comment]
Fixed with pull request #1044
