### ISSUE TITLE
Standalone build does not compile any more

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#1048]
The standalone build based on the following blog article does not compile any more due to deep API changes: https://blogs.itemis.com/en/how-to-standalone-generate-statechart-code-for-continuous-integration-builds

Please adjust the example for C/C++ generator purposes or document how to get a standalone build running.

**Comment by andreasmuelder** [comment]
This example is outdated, we will provide a standalone application soon, closing.
