### ISSUE TITLE
Document generator infrastructure

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#1052]
We should document
- How to write own generator
  - What interfaces/classes to implement/extend (class diagrma / sequence diagram)
  - How to use GeneratorEntry and FSA
  - How to use GenArtifactConfigurations
- How to register custom generator via extension point
- How to configure custom generator via generator module (bindings)
- How to add custom genmodel features

**Comment by BeckmaR** [comment]
Maybe we should do that after we refactored the generator infrastructure...

**Comment by andreasmuelder** [comment]
this is more a topic for the professional support. There is some basic documentation on how to write custom code generators
