### ISSUE TITLE
PNG export on Linux makes font too big

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1053]
For some reason, the file->print as image file export somewhat "works", but uses a different font and font size in the resulting image file, rendering the file useless.

![sensor](https://cloud.githubusercontent.com/assets/15799654/19509601/d0044916-95df-11e6-84f7-5293457e83d5.png)

**Comment by BeckmaR** [comment]
Seems to be related to [eclipse bug 312723](https://bugs.eclipse.org/bugs/show_bug.cgi?id=312723).

**Comment by andreasmuelder** [comment]
closing this as external bug
