### ISSUE TITLE
Bug: Deleting internal operations in the interface description removes necessary includes for tracing callback functions

### ISSUE THREAD

**Issue by lostwald** [Yakindu/statecharts#1082]
Hi,

after removing an internal operation from the interface of a statechart model:

![bug1](https://cloud.githubusercontent.com/assets/23447929/20258206/cf7d91f4-aa4e-11e6-9209-61317c81ab47.png)

the necessary include of the statechart header is removed from the <statechart>_required.h. However, this Include is still needed for the state_entered & state_exited tracing callback functions. See diff:

![bug2](https://cloud.githubusercontent.com/assets/23447929/20258295/50b540be-aa4f-11e6-9c75-d8ac172511dc.jpg)

The resulting code cannot be compiled.

**Comment by BeckmaR** [comment]
Hey @lostwald,

thank you for the feedback. I could reproduce the issue; activating the tracing feature in the `*.sgen` file produces the `*Required.h`-file, but the main statechart header is not included there. We will fix this.

However, a workaround would be to include `OSM.h` and `OSMRequired.h` in the compilation unit where the tracing functions are defined. I have attached an example project for you that builds and runs on my linux machine. Please be advised that the toolchain will likely need to be reconfigured when you want to try it out on a windows machine.
[tracing.zip](https://github.com/Yakindu/statecharts/files/589163/tracing.zip)

Regards,
Rene

**Comment by andreasmuelder** [comment]
Scheduled for Milestone 34
