### ISSUE TITLE
Pseudo-States cannot change fillcolor

### ISSUE THREAD

**Issue by bohl-itemis** [Yakindu/statecharts#110]
It would be nice, if pseudo-states could change their color.

**Comment by andreasmuelder** [comment]
Line style and fill style are only allowed for model elements created from version 2.5.
This is because the default background color for entry nodes in existing models is white.

**Comment by bohl-itemis** [comment]
addition: Coloring will only work on models that have been created by at least Version 2.5 (or nightly from now on).
