### ISSUE TITLE
SCTGenerator extension point references IGenModelExecutor which is no longer available

### ISSUE THREAD

**Issue by wendehals** [Yakindu/statecharts#1104]
The executor attribute of extension point org.yakindu.sct.generator.core.SCTGenerator references IGenModelExecutor which is no longer available. If I'm right, it should be
org.yakindu.sct.generator.core.execution.IGeneratorEntryExecutor

**Comment by andreasmuelder** [comment]
@wendehals you re right. Fixed this via cce361a
