### ISSUE TITLE
User Defined Types in State Charts

### ISSUE THREAD

**Issue by robfox1976** [Yakindu/statecharts#1106]
I thought the only way of having access to user defined types in a state chart was by using the Pro version, however, a colleague seems to remember being told in a training course a while ago that you can simply change the sc_types file.

Is this a possibility and if so, is there a master sc_types file which you alter?

**Comment by andreasmuelder** [comment]
@robfox1976 
In the gen models outlet feature, you can specifiy a libraryTargetFolder:

feature Outlet {
	targetProject = "test"
	targetFolder = "src-gen"
	libraryTargetFolder = "src"
}

From the documentation:
"libraryTargetFolder (String, optional): The folder to store the static (i.Â e. model-independent artifacts) to. In case this is not specified, all artifacts will be generated into the target folder. All artifacts in this folder will be preserved during re-generation. "

This means, you can change the type defs in the sc_types.h and it will not be overridden when placed in this folder. What you can do is for example change the type def for sc_integer from int32_t to int16_t:
typedef int36_t sc_integer; but in the statechart model, you still have only the 'integer' type that you map to int16_t. This is possible with the open source edition.

However, if you want to use the c standard ints and your user defined types (enums, structs, type aliases etc.) within your model, you can use our professional edition.
