### ISSUE TITLE
Bug in raiseTimeEvent()

### ISSUE THREAD

**Issue by Anzey** [Yakindu/statecharts#1109]
C++ generator created function 
```
void Glad::raiseTimeEvent(sc_eventid evid)
{
	if ((evid >= &timeEvents) && (evid < &timeEvents + sizeof(timeEvents)))
	{
		 *(sc_boolean*)evid = true;
	}
}
```
Part:
`&timeEvents + sizeof(timeEvents)`
is wrong.

At least should be (without ampersand):
`timeEvents + sizeof(timeEvents)`
or something even better like e.g.:
`if ((evid >= ((sc_eventid)timeEvents)) && (evid < ((sc_eventid)(((char*)timeEvents) + sizeof(timeEvents)))))`

Additional remark
As I understand function checks if pointer passed to function is sane. If not it silently goes over it. But it generally means serious problem in application that uses `raiseTimeEvent()`. And this check just hides the problem.
IMHO this check should be removed or replaced with something meaningful (like e.g. assertion).

**Comment by stmork** [comment]
This issue fits perfectly into my still open issue #608 from April. The pointer arithmetics is not only insane but also it is not really object orientated. So:
+1

**Comment by BeckmaR** [comment]
Hey @Anzey, I've allowed myself to edit your comment for better readability.

**Comment by terfloth** [comment]
@Anzey you are right - will fix that soon.

**Comment by terfloth** [comment]
The current fix will look like this:

```
void Test::raiseTimeEvent(sc_eventid evil)
{
	if ((evid >= (sc_eventid)timeEvents) && (evid < (sc_eventid)(&timeEvents[timeEventsCount])))
	{
		*(sc_boolean*)evid = true;
	}				
}
```

while `timeEventsCount` is defined as a constant and `sc_eventid` is redefined as:

`typedef intptr_t sc_eventid;`
