### ISSUE TITLE
Discuss meaning of "readonly", "external" variable modifiers

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1122]
I stumbled over these things in the documentation. What `readonly` is supposed to do is clear, but there's also `const`. To make matters worse, `const readonly` is possible. `external` remains a mystery, because whatever one could assume about its use can be done with `interface` or `internal` just as well.

One more thing: what is a `local event`?
```
internal:
   local event ev1
```

Either we should discuss the usecases and make them more clear in the documentation or we should set it to deprecated and schedule it to be deleted.

**Comment by robert-rudi** [comment]
As introduced in 7a11af1 the keywords "readonly", "external" and "local" will be validated as deprecated.
I will close this for now.
