### ISSUE TITLE
History EditPart changes size with name and overlap name

### ISSUE THREAD

**Issue by bohl-itemis** [Yakindu/statecharts#113]
The name of a shallow history or deep history name is displayed behind the figure. 
Also the width of the figure rises with the length of the name.
![bug001](https://cloud.githubusercontent.com/assets/12081541/8278969/36813ed0-18d0-11e5-85a3-3cf759558d22.PNG)

**Comment by andreasmuelder** [comment]
Duplicate, see  #115
