### ISSUE TITLE
Configure SCT to use GTK2 on Linux

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1130]
Apart from GTK2 being pretty old, it is at least stable. GTK3 and eclipse aren't friends yet, the performance while drawing statecharts is pretty bad. The welcome page is rendered incorrectly with GTK3, disabling it and falling back to GTK2 solves these issues. The GTK+ team promised verison 3.22 that came out in September would be long term stable, so maybe with the adoption of it in SWT we could actually use GTK3 again.

Until then, I propose to add the following lines to the SCT.ini on linux:
```
--launcher.GTK_version
2
```

before the vmargs parameter.

**Comment by andreasmuelder** [comment]
Since GTK2 is pretty old and the rest of eclipse looks ugly with GTK2 we should stay with GTK3.
