### ISSUE TITLE
Consistent notation(s) for "YAKINDU Statechart Tools"

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1132]
Currently there are many different notations for our product and its professional and open source flavours. We should select very few of them and use them consistently throughout the documentation and the software.

Here are some of the notations I saw:
- YAKINDU Statechart Tools
- Yakindu Statechart Tools
- YAKINDU STATECHART TOOLS
- YAKINDU Statechart Tools Professional Edition
- YAKINDU Statechart Tools Open Edition
- YAKINDU Statechart Tools Pro
- YAKINDU Statechart Tools PRO
- YAKINDU Statechart Tools Pro Edition
- YAKINDU Statechart Tools (SCT)
- YAKINDU SCT
- Yakindu SCTPRO
- SCT
- SCT Professional
- SCT Pro Edition
- Statechart Tools Pro Edition
- Trusted Download Bundle

**Comment by BeckmaR** [comment]
I'd say we should never use the following:

* YAKINDU Statechart Tools Open Edition
* YAKINDU Statechart Tools Pro
* YAKINDU Statechart Tools PRO
* SCT Pro Edition
* Statechart Tools Pro Edition

**Comment by RainerKlute** [comment]
My suggestions:

Full names:
- YAKINDU Statechart Tools
- YAKINDU Statechart Tools Professional Edition

Valid abbreviations, maintaining the 'Y' for brand recognition:
- YAKINDU Statechart Tools Professional
- YSCT
- YSCT PRO

**Comment by BeckmaR** [comment]
We have used SCT on so many places and occasions, I believe it would be unwise to drop it now. It's common usage.

**Comment by RainerKlute** [comment]
Sometimes you have to slaughter holy cows. And with the release of the professional edition, now is a good point in time to do so and start something new.

**Comment by andreasmuelder** [comment]
This will be discussed in the pro repository.
