### ISSUE TITLE
Consistent naming of statechart concepts

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1133]
Suggestion for a consistent naming of statechart concepts to be use throughout documentation and software:
- a **statechart model** is everything that goes into an _.sct_ file. It consists of:
- the **definition section** and
- the **statechart**, i.e. the graphical part of the statechart model.

**Comment by terfloth** [comment]
Ok - we should extend the naming conventions towards the notion of 'state machine'.

Watt is the required action?

**Comment by andreasmuelder** [comment]
* a statechart is everything that goes into an .sct file. It consists of:
 * the definition section allows the definition of interfaces/ reactions etc.
 * the graphical canvas contains regions

@RainerKlute Please review the documentation

**Comment by terfloth** [comment]
We should also speak of **state machine code** in the context of code generators as well as **state machine execution** in the context of the simulation.

**Comment by terfloth** [comment]
@RainerKlute : what is the progress here ?

**Comment by RainerKlute** [comment]
Nearing completion, but delayed for more urgent stuff. I don't think it is release relevant.

**Comment by RainerKlute** [comment]
Fixed by #1597.
