### ISSUE TITLE
Redo doesn't work after refactoring

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#1137]
1. Refactor -> Extract Subdiagram
2. Open Subdiagram 
3. Go back to main Statechart
4. Press "strg + z"
5. Warining / Click yes

6. Press "strg + y" -> don't work

**Comment by BeckmaR** [comment]
Probably related to #803 & #864.

**Comment by BeckmaR** [comment]
Closing: already fixed
