### ISSUE TITLE
Java code generator generates invalid code for readonly variables in default interface.

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#114]
Declare a statechart with:

interface:
   var readonly x : integer

and generate the Java code. The generator will generate a setX on the statechart class that tries to delegate to setX on the interface object, wich does not exist. This leads to a compile error.

**Comment by bohl-itemis** [comment]
Created test for ReadOnlyVariables with read only variables in default and named interface.

Error doesn't appear, no setters are generated for read only variables in java, nor in C, C++ or interpreter.
