### ISSUE TITLE
#define to save space

### ISSUE THREAD

**Issue by robfox1976** [Yakindu/statecharts#1144]
I'm working on my first project using Yakindu. Although I've found it very useful, I've come to a point where I've run out of room on my micro!

One thing that I would like to do, is rather than use "var readonly" I'd ideally like to use a #define.

I've had a look around but I couldn't see anything.

I did try changing all my "var readonly" variables to "const", but one issue I had with this is that they were all under "internal". When I changed all to "const" I got an error "expected a declaration", as I basically had 

`/*! Type definition of the data structure for the TestMInternal interface scope. */
typedef struct
{

} TestMInternal;`

**Comment by BeckmaR** [comment]
In the open source edition of YAKINDU SCT, it is not possible to use a `#define`. Did you already try the Inlining-Features of the Code generator, compiler optimizations and switching to the default build instead of debug?

**Comment by robfox1976** [comment]
I have not tried the inlining features yet. I have set the optimisation settings to high for size and this has helped considerably.

Are there any plans to introduce something like #define?

**Comment by BeckmaR** [comment]
You can only use defines from header files in the Professional Edition using our Deep C Integration. It allows you to use all types, variables and defines from your header files.

The bug you mentioned in your issue description concerning the empty structs has been fixed recently with PR #1196, and we plan to release a new version including this fix on next friday.
