### ISSUE TITLE
Out of memory exception after: "Writing new resource descriptions chunk i of n" blocks Eclipse

### ISSUE THREAD

**Issue by lostwald** [Yakindu/statecharts#1146]
Hi,

After installation of the the Yakindu SCT Pro Versionw ith c integration several users have the problem, that a job is running (for several days). The Job Description is "Writing new resource descriptions chunk i of n (see screenshot). The problem disappears after deinstalling Yakindu SCT.

![chunkproblem](https://cloud.githubusercontent.com/assets/23447929/21587207/e4369e72-d0d9-11e6-8a14-27a3e5d3ea0d.png)

**Comment by lostwald** [comment]
Additional information,

when this job is started it is not possible to access types defined in C Domain source code.

The job finally quits whith an out of memory exception after consuming more than 16GB heap space.

**Comment by tkutz** [comment]
Did you only uninstall the Pro edition? So is it a problem in the Pro Edition only, or also in the Open Edition of SCT?

**Comment by lostwald** [comment]
The problem is in the Pro edition only. I can reproduce the problem by opening a project in the 
Project Explorer with some "bigger" amount of source code. It does not occur when only some trivial c-files with types are available.

**Comment by paphko** [comment]
I found the culprit: https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/clustering/ClusteringBuilderState.java#L216

**Comment by lostwald** [comment]
Hi,
but the message is "Writing new resource descriptions chunk", instead of "Updating resource descriptions chunk " like in line https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/clustering/ClusteringBuilderState.java#L386

**Comment by andreasmuelder** [comment]
Currently, all header files from the whole workspace are indexed during a workspace build. We will change this implementation so that only header files that are imported into a statechart will be indexed. 
There is also a performance issue when using a lot of defines, maybe this is the case in your example. 
This issue will be closed and reopened in the internal professional edition repository.
