### ISSUE TITLE
EntryPoints naming changes icon size

### ISSUE THREAD

**Issue by bohl-itemis** [Yakindu/statecharts#115]
Manuel ClickTest T2.10.1:

- The name of entry points is displayed behind the icon.
- The wide of entry points scales with the length of the name.

![issue_entry_point](https://cloud.githubusercontent.com/assets/12081541/8645285/5305dd96-2946-11e5-8fa6-fa25534e81f0.PNG)

**Comment by andreasmuelder** [comment]
Regression due to Pseudo-States cannot change fillcolor #110
