### ISSUE TITLE
Move statechart specification to collapsable editor area just like the palette

### ISSUE THREAD

**Issue by paphko** [Yakindu/statecharts#1151]
The specification of a statechart may contain a lot of text which is not really a graphical part of the statechart. It looks especially awkward when it interfers with the graphical part as shown here: 

![sct-spec](https://cloud.githubusercontent.com/assets/6435623/21604621/76d58cf0-d1a4-11e6-8463-3105f2fd5be9.png)

I would suggest to add a collapsable editor which is by default located at the left-hand side of the graphical editor. Then the specification can be shown and also resized as needed, it does not clutter the graphical representation of the statechart, and syntax highlighting could be enabled permanently.

**Comment by BeckmaR** [comment]
I like this idea. I don't think the specification needs to be always visible. This would also enable us to show the specification in sub-statecharts.

But one tip for now: You can move and resize regions and the specification section. It does not need to overlap with your region.

**Comment by andreasmuelder** [comment]
We should plan this for one of the next milestones then

**Comment by terfloth** [comment]
That seems to make sense > discuss with usability engineer

**Comment by svenjawendler** [comment]
To adapt the UI to the personal needs is important to enhance usability. To fade out features that are currently not important enables the user to focus. @SimonEit Do you agree?

**Comment by svenjawendler** [comment]
The survey participants also mentioned this point multiple times. Here are some cites: separation of textual FSM content definition from graphical view into own file; Why is the statechart description language written in a field in the .sct model and not simply in a distinct file (e.g. model.sdl)?; The input for the events, variables and so on should not be in the drawing area.; Provide a high-level textual script language to edit diagrams; Text only representation of state machines. Graphical representation is automatically generated from the DSL representation of the state machine.

**Comment by andreasmuelder** [comment]
https://github.com/Yakindu/statecharts/issues/849 is referenced

**Comment by terfloth** [comment]
Sketch proposal of solution.

**Comment by robert-rudi** [comment]
As implemented in #1740 there is a new feature, where the inlined definition section can be pinned to the left side of the statechart diagram editor. With the options to collapse and expand the pinned definition section, the behaviour is as the one of the palette on the right side. 

As a result of a short usability discussion it should be evaluated, if the option to re-inline the definition section is needed at all. The only argument we have found to switch to the old definition section appearance, is the printing-feature for the statechart diagram. In case the user wants to print the diagram, he wouldn't get the pinned definition section. 

As an internal feature request there might be the possibility to print the pinned definition section besides the statechart diagram when exporting the diagram to an image with the new ImageRenderer (in a diagram: Right Click -> File -> Save As Image File ... ).
The complexity for this request must be evaluated.
