### ISSUE TITLE
Xpand Generator SGen doesn't generate code.

### ISSUE THREAD

**Issue by bohl-itemis** [Yakindu/statecharts#116]
This test is defined in the manual click test T8.4 and T8.4.1:

"Select TestProject in Package Explorer
Select File->New->Other (CTRL+N) from the menu
Select Yakindu->Code Generator Model
Click on Next button
Set the name to StaircaseXpand.sgen
Click on Next button
Select Custom Xpand-based Generator and check Staircase.sct
Click on Finish button"

"Open file StaircaseXpand.sgen and set following features:
- targetFolder = "src-gen-xpand"
- templateProject = "TestProject.generator.xpand"
- templatePath = "testproject::generator::xpand::TextGenerator::main""

Generating Code Artifacts on the SGen file does not have any effect.

![issue_sgen_xpand_01](https://cloud.githubusercontent.com/assets/12081541/8645606/27968d10-2949-11e5-8b1a-b99bdbfa1e52.PNG)

**Comment by andreasmuelder** [comment]
Missing Project Dependency from model project to generator project, Testcases adopted
