### ISSUE TITLE
Change default transition layouting to rectilinear

### ISSUE THREAD

**Issue by SimonEit** [Yakindu/statecharts#1162]
Rectilinear layouting provides a much more robust style of rendering transitions, as the angle values of the bendpoints will always stay at 90°

Manually adjusted obligue transitions change the angle values of their bendpoints to unexpected/unwated degrees when model elements are changed/added/resized. This can cause a visually unappealing result.

**Comment by BeckmaR** [comment]
Does PR #1202 resolve this?
