### ISSUE TITLE
Bug in Doku ( ??? instead of an arrow)

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#1168]
![unbenannt](https://cloud.githubusercontent.com/assets/15800400/22112376/fbcf53da-de62-11e6-8ef6-42f58a106f03.png)

**Comment by RainerKlute** [comment]
I checked the generated HTML code for both Eclipse help and website, and it is perfectly okay.

**Comment by RainerKlute** [comment]
Ah, okay! While as [already stated](https://github.com/Yakindu/statecharts/issues/1168#issuecomment-274458328) the generated HTML code is fine, this is only true in my development environment, but **not** in the built product. Somewhere in the toolchain all special characters got replaced by "???".

**Comment by RainerKlute** [comment]
In older versions this worked fine, but has been broken somewhere between 2.6.0 and 2.9.1.

**Comment by andreasmuelder** [comment]
Reason is a wrong encoding on the new build slaves, it should be UTF-8. fixed on build server
