### ISSUE TITLE
Xtend Generator SGen can't find generatorClass

### ISSUE THREAD

**Issue by bohl-itemis** [Yakindu/statecharts#117]
Based on the manual clicktest T8.5 and T8.5.1:

"Select TestProject in Package Explorer
Select File->New->Other (CTRL+N) from the menu
Select Yakindu->Code Generator Model
Click on Next button
Set the name to StaircaseXtend.sgen
Click on Next button
Select Custom Xtend2/Java-based Generator
Check Staircase.sct file
Click on Finish button"

"Open file StaircaseXtend.sgen and set following features:
- targetFolder = "src-gen-xtend"
- generatorProject = "TestProject.generator.xtend"
- generatorClass = "testproject.generator.xtend.XtendGenerator""

The generator class cannot be resolved, see screenshot.

![issue_xtend_resolve](https://cloud.githubusercontent.com/assets/12081541/8646066/187e6736-294d-11e5-8aba-7149898754cc.PNG)

**Comment by andreasmuelder** [comment]
Missing Project Dependency from model project to generator project, Testcases adopted
