### ISSUE TITLE
sgen can't find custom generator class

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1172]
Steps to reproduce:
Manual teststeps 7.2, 7.2.1, 7.2.2
Expected: sgen file can find generatorClass `TestProject.generator.java.JavaGenerator`
Error: sgen file can find project `TestProject.generator.java`, but `TestProject.generator.java.JavaGenerator`  produces the error "Generator class does not exist".

**Comment by tkutz** [comment]
The testplan is missing one point: you need to add the test project to the java build path of your client project.
