### ISSUE TITLE
Thrown exception in simulation not displayed / explained

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1173]
With a java operations class where an operation throws an exception, the simulation only shows that an unexpected exception has occured instead of the actual exception + its text.

**Comment by tkutz** [comment]
I can easily change this to behave as the following:

On exception during simulation one would get the following
![bildschirmfoto 2017-01-25 um 13 04 27](https://cloud.githubusercontent.com/assets/2589669/22290042/08204c70-e2ff-11e6-9afa-2737562c0579.png)

In the error log, one would see: 
![bildschirmfoto 2017-01-25 um 13 04 45](https://cloud.githubusercontent.com/assets/2589669/22290047/119d2674-e2ff-11e6-87f2-302f56c88e01.png)
