### ISSUE TITLE
AERI error reporting doesn't seem to work

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1175]
I have never seen a popup telling me Eclipse wants to send error reports to YAKINDU, and even with the forced error on [ctrl + alt + L] this does not seem to happen.

**Comment by andreasmuelder** [comment]
For whatever reason the eclipse.buildId property was missing in the product definition.
<property name="eclipse.buildId" value="${unqualifiedVersion}.${buildQualifier}" />
AERI thinks it is running in test env if this property is not there.
