### ISSUE TITLE
No documentation for keywords "import" and "as"

### ISSUE THREAD

**Issue by bohl-itemis** [Yakindu/statecharts#118]
No documentation is available for the keyword "import".

Manual click test T 9.1:
"Select Statechart Properties view.
Hit Ctrl+Space
Expected proposals:  “import”, “interface”, “internal”, “namespace”
Check if the proper documentation is displayed for every proposal"

Import does not have a documentation.

Manual click test T 9.3.1:
"enter “after” as keyword and hit Ctrl+Space
Expected proposals : Expression that evaluates to  an integer value
Enter a integer value and hit Ctrl+Space again.
Expected proposals with documentation :”ms”, “ns”, “us”, “s”"

"as" is not a time using, but it can be triggered by this test.

**Comment by andreasmuelder** [comment]
The import auto completion should be removed from the proposals since it is not fully supported yet.
For the cast operator 'as' documentation should be added
