### ISSUE TITLE
Error handling for identical statechart names

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#1198]
As pointed out in this comment:
https://groups.google.com/forum/embed/?place=forum%2Fyakindu-user#!topic/yakindu-user/hLtKW32bbdc

When having two identically named statecharts, the sgen model is always using the first one from index. This is unclear for the user. We should either provide some warning/error message, or some opportunity to qualify the statechart in sgen.

**Comment by andreasmuelder** [comment]
We can use the namespace feature to qualify the statechart name. The error message should give a hint on how to use a namespace.

**Comment by rherrmannr** [comment]
This is fixed with https://github.com/Yakindu/statecharts/pull/2305
