### ISSUE TITLE
Problem with sc_string type in C-Generator

### ISSUE THREAD

**Issue by dalai4git** [Yakindu/statecharts#121]
Functions that take `sc_string` have in the generated code signatures with `const sc_string`.

This would have been ok, but unfortunately `sc_string` is defined in `sc_types.h` by:

    typedef char * sc_string; 

This means that the function argument is in reality `char *const` (a const pointer to char) and not `const char *` (a pointer to const char) as one would expect. 

A workaround is to define the sc_string with `#define sc_string char*`.

**Comment by muehlbrandt** [comment]
An alternative possibility would be to directly generate the `char * ` into the code, but for compatibility reasons i also prefer the `#define sc_string char*` solution.
