### ISSUE TITLE
Testplan 4.3: Errors while using the welcome page

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#1225]
Open: Help -> Welcome Page -> Professional Edition -> Click on the yellow "back" arrow (not the home button!) 

This uploaded window appears (screenshot).

To enter the welcome screen, it is needed to click on the backward arrow twice.

![grafik](https://cloud.githubusercontent.com/assets/25480651/23251541/122f53f8-f9ae-11e6-9678-c8666b6d42f6.png)

**Comment by RainerKlute** [comment]
Reproducible on Linux (openSuse Leap 42.2)

**Comment by RainerKlute** [comment]
Reproducible on Linux (openSuse Leap 42.2)

Fixed by YSCT PRO pull request 693.
