### ISSUE TITLE
Interface in generated Function-Name missing after using IdentifierSetting

### ISSUE THREAD

**Issue by DefCon-CC** [Yakindu/statecharts#1239]
When using IdentifierSettings in sgen. For example: 

feature IdentifierSettings {
    moduleName =  "DspControl" 
    statemachinePrefix =  "DspCtrl" 
    maxIdentifierLength = 64
    separator =  "_" 
}

Every Function will have the StateMachine-Prefix which is pretty nice but the information for which Interface the event is generated is missing:

![2017-02-28 15_21_31-dspctrl h _--_ dspcontrol h - textvergleich - beyond compare](https://cloud.githubusercontent.com/assets/25898240/23408975/2897a18e-fdca-11e6-8efa-87a0e4a51e70.png)

This can also cause problems when two Interfaces have the same Event with the same name. Then two functions with the same Function name will be generated:

interface Test1:
in event StateReached

interface Test2:
in event StateReached

**Comment by andreasmuelder** [comment]
@terfloth Please consolidate if this issue should be fixed for the next milestone
