### ISSUE TITLE
Size of Choice Symbol not changeable

### ISSUE THREAD

**Issue by DefCon-CC** [Yakindu/statecharts#1241]
It would be great if the size of a "Choice" Symbol would changeable, because it is hard to click on the "Choice" Symbol when many lines and arrows are connected to it.

![sm_model](https://cloud.githubusercontent.com/assets/25898240/23453992/e1ddbed0-fe6a-11e6-99b6-6b56c34ce921.png)

**Comment by andreasmuelder** [comment]
This is related to https://github.com/Yakindu/statecharts/issues/432

**Comment by BeckmaR** [comment]
I have got one tip for you: go through the incoming transitions, check out the properties tab in the bottom and change the arrow routing from "oblique" to "rectilinear". Then you will have it easier to align the transitions on top of each other and clean up the statechart a little. This makes handling the routing of transitions a bit easier in general. We changed the default setting in the last release, but it only applies to new transitions.
