### ISSUE TITLE
Do not invoke PreferenceInitializer from code

### ISSUE THREAD

**Issue by Bananeweizen** [Yakindu/statecharts#1242]
Please remove all calls to initializeDefaultPreferences() from the statecharts code. As [AbstractPreferenceInitializer](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcore%2Fruntime%2Fpreferences%2FAbstractPreferenceInitializer.html) states: 

> Clients should not call this method. It will be called automatically by the preference initializer when the appropriate default preference node is accessed.

Background: You are calling the initializer yourself from the Yakindu preference pages. This leads to resetting the defaults whenever preference pages are opened. Products using Yakindu SCT therefore don't have a chance to cleanly override your defaults.

Affected locations that I'm aware of: https://github.com/Yakindu/statecharts/blob/13c25ad8080bd0dbed3689983ecefdd6184e2b07/plugins/org.yakindu.sct.examples.wizard/src/org/yakindu/sct/examples/wizard/preferences/ExamplesPreferencePage.java#L86

https://github.com/Yakindu/statecharts/blob/e9a3c18a7199412aca6cd62421546353441650dc/plugins/org.yakindu.sct.ui.editor/src/org/yakindu/sct/ui/editor/preferences/StatechartAppearancePreferencePage.java#L113

**Comment by andreasmuelder** [comment]
This is right - the calls should be removed there. They do not make sense anyway.
