### ISSUE TITLE
Better documentation index

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#1256]
Use a more fine grained index for the documentation on our website.

**Comment by terfloth** [comment]
First evaluate options.

**Comment by RainerKlute** [comment]
The most important information is that Textile by itself does neither support an index nor a table of contents (TOC). Our options:
- Investigate what Mylyn Wikitext offers. If needed, we should also investigate developer versions.
- Extend Mylyn by a so-called "language customization".
- Look at solutions developed by others – probably not very promising.
- Develop our own solution that parses a couple of Textile files and emits index and/or TOC.
- Replace Textile by something better, e.g. DocBook or AsciiDoc.

![better_index](https://cloud.githubusercontent.com/assets/1495781/25753111/ab53a694-31ba-11e7-8265-abeb2eefde6f.png)

**Comment by RainerKlute** [comment]
Using the Mylyn Wikitext API looks very promising. Writing a custom document builder producing a table of contents artifact is definitely possible.

**Comment by RainerKlute** [comment]
Thomas Laß provided a layout draft.

**Comment by RainerKlute** [comment]
Moving the index to the left-hand side requires non-trivial changes to the new Textile-to-Hubspot generator.

**Comment by RainerKlute** [comment]
Fixed with pull request #1688.
