### ISSUE TITLE
Make sure varargs in template functions are handled correctly

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1263]
See TODO in ExpressionsTypeInferrer.

**Comment by terfloth** [comment]
@BeckmaR : what is the problem? Please describe independently from TODO tag in some implementation!

**Comment by BeckmaR** [comment]
When @tkutz and I hacked the TypeInferrer together we just stumpled upon a location where there might be an issue with VarArgs. At the time we did not have the time to investigate further if there is actually an issue. Basically we would need a test for the combined case of generics and varArgs.
