### ISSUE TITLE
Create a tutorial series to cater to first time users

### ISSUE THREAD

**Issue by SimonEit** [Yakindu/statecharts#1267]
The concept for this is to built a very simple tutorial project series that contains tasks, examples and sample solutions for the target audience of 'first time users' who have a cold start with the tool.

The goal is not to educate the users about the basic principle of statemachines though, but is focused on the functionality of the tool.

**Comment by terfloth** [comment]
@SimonEit : what is the current status?

**Comment by svenjawendler** [comment]
Maybe we could create cheatsheets on this?

**Comment by svenjawendler** [comment]
Result 1: An example project with some very basic lessons. It needs a review: https://drive.google.com/drive/folders/0BxqrVB1ADkfARG16R25uckc2U00 
Result 2: To make cheatsheets work successfully with YAKINDU Statechart Tools we need more COMMANDS. Currently there is only the COMMAND: Create Subdiagramm. We need Commands for create state, create transition.

**Comment by andreasmuelder** [comment]
moving to backlog

**Comment by andreasmuelder** [comment]
closing as orphaned
