### ISSUE TITLE
Simplify the entering of text edit mode on a transition

### ISSUE THREAD

**Issue by SimonEit** [Yakindu/statecharts#1273]
If you have a blank label on a transition it is too hard to get into the text edit mode again. One problem is that the Warning-Sign seems to consum at least one click of the doubleclick. Also the clickable box around the arrow could be a few pixels wider.

**Comment by svenjawendler** [comment]
I do it simply by starting typing. Selecting the transition and start typing. This works fine.

**Comment by BeckmaR** [comment]
I don't understand this issue either. Doubleclicking a transition opens the edit window, no matter if there is an error marker or not. Clicking it once and just typing does the trick as well like @svenjawendler mentioned. Closing this for now.
