### ISSUE TITLE
Add a checkbox "save automatically" to the save dialog when running a simulation

### ISSUE THREAD

**Issue by SimonEit** [Yakindu/statecharts#1275]
At the moment the dialog pops up every time you run a simulation on an unsaved statechart. Far more often the user wants to save the model at this point rather than simulating the model in a dirty state. Therefore the dialog should contain a checkbox, which provides an auto-save functionality.

**Comment by svenjawendler** [comment]
![saveandlaunch](https://cloud.githubusercontent.com/assets/22005752/25612482/2cebab80-2f2b-11e7-97a5-029030ccbbe9.png)

**Comment by svenjawendler** [comment]
SOLUTION

It can be done by setting the preference:
![saverequireddirtyeditorsbeforelaunching](https://cloud.githubusercontent.com/assets/22005752/25613191/b4a52554-2f2d-11e7-8049-be5ae576e591.png)

Maybe we could ship this with the YSCT preferences?
/instance/org.eclipse.debug.ui/org.eclipse.debug.ui.save_dirty_editors_before_launch=always

**Comment by andreasmuelder** [comment]
I think the problem here is that a different dialog shows up when a sct editor is in dirty state

![unbenannt](https://cloud.githubusercontent.com/assets/6338708/25741527/79b065d4-318b-
11e7-8bb1-0a4077048e7f.PNG)

**Comment by SimonEit** [comment]
Yes, i was talking about that dialog @andreasmuelder. Its obviously not a showstopper or something, simply an annoying dialog. Adding a "always save before simulation" checkbox to that dialog would fix it.
