### ISSUE TITLE
Red color of active states in a simulation confuses first time users

### ISSUE THREAD

**Issue by SimonEit** [Yakindu/statecharts#1277]
Multiple usability testusers (who were **first-time-users** of the application)  have mentioned that they associate the red color of active states in a running simulation with things like "error", "problem", "fault", "inactivity" etc. 

Obviously for experienced users this is not a problem. Changing the default color  - for example - from red to green might annoy/confuse this user group.

However i suggest changing the default color and providing the experienced user with the info that he can customize it back the way he is used to via the preferences. This could be done in the release notes for example.

**Comment by svenjawendler** [comment]
Here are some suggestions for a new default color for simulation. I prefer orange -> 
1. it is close to red (so the difference is less big) and 
2. it is a part color of the YAKINDU logo and 
3. it is shinny and easily recognized and 
4. people with red-green color blindness recognize this accentuation

![simulationproposal03](https://cloud.githubusercontent.com/assets/22005752/26542515/7b3d9570-445a-11e7-8803-bea88f71cab7.png)
![simulationproposal01](https://cloud.githubusercontent.com/assets/22005752/26542514/7b3ca2aa-445a-11e7-8ee3-89471080d6a5.png)
![simulationproposal02](https://cloud.githubusercontent.com/assets/22005752/26542513/7b3a1de6-445a-11e7-8061-94f3067085c5.png)

**Comment by BeckmaR** [comment]
+1 for orange

**Comment by andreasmuelder** [comment]
+1 for yellow orange

**Comment by andreasmuelder** [comment]
@terfloth please comment

**Comment by tkutz** [comment]
+1 for yellow/orange

**Comment by jdicks** [comment]
+1 for yellow/orange

**Comment by svenjawendler** [comment]
5 votes for orange.
