### ISSUE TITLE
Definition section does not appear as an editable textarea

### ISSUE THREAD

**Issue by SimonEit** [Yakindu/statecharts#1278]
Multiple usability tests have shown that users do not recognize the definition section as an editable area in its current state. At the moment it appears to be more than a "legend area" for inexperienced users. To make it more visible and easier to understand it should feature a monospace font and syntax highlighting in its default appearance.

**Comment by andreasmuelder** [comment]
This becomes obsolete when https://github.com/Yakindu/statecharts/issues/1151 is implemented

**Comment by BeckmaR** [comment]
I'm closing this because we derived a task to rework the definition section in #1442
