### ISSUE TITLE
Change back to modeling perspective after terminating a simulation

### ISSUE THREAD

**Issue by SimonEit** [Yakindu/statecharts#1279]
It is confusing to alot of users that you stay in the simulation perspective after terminating a simulation. By changing back to the modeling perspective when terminating a simulation the perspective switch concept would make a lot more sense.

**Comment by SimonEit** [comment]
I am still convinced that the basic idea behind the perspective switch-back is a good thing for the users. Obviously the buggy behavior in #1646 and #1641 needs to be fixed, but i would advise against a complete revoke of this feature.

**Comment by andreasmuelder** [comment]
closing since the related bugs are fixed
