### ISSUE TITLE
The "New Model"-Wizard should auto-fill the .sct file extension when missing

### ISSUE THREAD

**Issue by SimonEit** [Yakindu/statecharts#1280]
At the moment you need to manually add the .sct file extension to your new model filename. First time users had trouble with this after they deleted the default name. If you forgot that the file extension is .sct you have to close and reopen the wizard.

A quick solution would be to change the error-text to tell the user what filename they need to add.

The proper solution would be to add a parsing of the filename and auto-add the missing file extension, if the user forgot to put it in.

**Comment by andreasmuelder** [comment]
Fixed with PR #1288
File extension is shown in error message
