### ISSUE TITLE
The hint "Content Assist Available" is too hard to notice

### ISSUE THREAD

**Issue by SimonEit** [Yakindu/statecharts#1282]
This hint is crucial for a convenient usage of sct but in all of the usability tests not a single user was aware of the lamp-symbol that should inform the user.

To tackle this, there a multiple options:
a) Make the Lamp-Symbol more prominent (i.e. larger in size)
+ Easy to implement
- Might be annoying if you already know about Ctrl+Space

b) Switch to another Symbol which is more noticable but keep the size. For example a bright green exclamation mark
+ Easy to implement
- Might still get overlooked by users

c) Implement it in a way that this hint cannot be overlooked until the user clicks it away
+ This would make sure that the users is aware of this important hint 
- Not entirely show how this can be implemented

**Comment by svenjawendler** [comment]
Add the hint as comment to the definition section.

**Comment by svenjawendler** [comment]
Suggestion b) should not be realized. It violates the "conformity with user expectations" for eclipse users (ISO 9241-110).

**Comment by svenjawendler** [comment]
![hintctrlcmd](https://user-images.githubusercontent.com/22005752/27025354-775001b8-4f5a-11e7-91f8-a69000c4b024.png)
