### ISSUE TITLE
Error message should be short and precise. In the extended information (F2) example code should be available.

### ISSUE THREAD

**Issue by SimonEit** [Yakindu/statecharts#1283]
At the moment it is quite hard to learn the statechart language. A very common way is to *learn by example*. The best way to provide examples is in the "F2" extended info of an error.

**Comment by svenjawendler** [comment]
Rework error messages and validators. Connect with documentation where an example solution is given.

**Comment by svenjawendler** [comment]
#559  Fix upper case /lower case issues in error and validation messages can be done within this issue.

**Comment by BeckmaR** [comment]
Closing in favor of #1742 where all error message issues are collected.
