### ISSUE TITLE
Use of active(MSM.STANDBY) as guard expression does not work anymore!

### ISSUE THREAD

**Issue by DefCon-CC** [Yakindu/statecharts#1314]
I'm using the transition condition always[active(MSM.STANDBY)] in my State-Machine. But with Yakindu SCT 2.9.3 I'm getting the error "Could not resolve reference to State 'MSM.STANDBY'". But the State STANDBY is existing in my State-Machine. Does the naming somehow changed?

**Comment by andreasmuelder** [comment]
This seems to be a duplicate to https://github.com/Yakindu/statecharts/issues/1294
This should have been resolved with the latest bugfix - can you check if this error still exists after checking for updates?

**Comment by DefCon-CC** [comment]
Seems to work now when using always[active(**StateMachineName**.MSM.STANDBY)] instead of always[active(MSM.STANDBY)]
