### ISSUE TITLE
Avoid magic numbers in C code generator

### ISSUE THREAD

**Issue by paphko** [Yakindu/statecharts#1336]
There are plenty of magic numbers generated that should rather be defines to avoid QAC warnings:
![image002](https://cloud.githubusercontent.com/assets/6435623/25653441/2adbb070-2fed-11e7-8b83-dd36e538c669.png)
![image003](https://cloud.githubusercontent.com/assets/6435623/25653440/2adab404-2fed-11e7-8ea0-c0211b63b033.png)

**Comment by stmork** [comment]
+1

**Comment by terfloth** [comment]
Annoying QAC ... ;-)

Yes - we can introduce defines...
