### ISSUE TITLE
(Eclipse sct editor) Impossible to scroll in a interface widget

### ISSUE THREAD

**Issue by wixiw** [Yakindu/statecharts#1347]
When you enter an "interface" widget (double clic to get the focus) in the statechart editor view, the mouse scrolling is disabled. It's particularly annoying on huge interfaces.

For instance, my interface
 interface:
	operation startLSA(id : integer)
	operation stopLSA()
	operation getLSAStatus() : integer
	operation goToLSAEntry(id : integer, dir : integer)
	operation beep(nb : integer)
	operation led1(blink : integer)
	operation led2(blink : integer)
	operation led3(blink : integer)
	operation led4(blink : integer)
	operation ledRGB(color : integer, blink : integer)
	operation isStartPlugged() : boolean
	operation isColorSwitchOnPrefered() : boolean
	operation isUser1SwitchOn() : boolean
	operation isUser2SwitchOn() : boolean
	operation logDebug(msg : string)
	operation logInfo(msg : string)
	operation logError(msg : string)
	operation dieMotherFucker()
	operation xav() : integer
	operation xar() : integer
	operation yside() : integer
	operation xavExtended() : integer
	operation xouter() : integer
	operation getRemainingTime() : integer
	operation setStatus(status : integer)
	operation enableAvoidance(on : boolean)
	operation setPosition(x : real, y : real, h : real)
	operation setSpeedAcc(vMax : integer, vMaxTurn : integer, accMax : integer, accMaxTurn : integer)
	operation goTo(x : real, y : real, dir : integer)
	operation goToNoSym(x : real, y : real, dir : integer)
	operation goToCap(x : real, y : real, h : real, dir : integer)
	operation goToCapNoSym(x : real, y : real, h : real, dir : integer)
	operation goForward(d : real)
	operation turnDelta(dh : real)
	operation turnTo(h : real)
	operation faceTo(x : real, y : real)
	operation recalFace(border : integer)
	operation recalRear(border : integer)
	operation stopMoving()
	operation targetReached() : boolean
	operation omronFrontLeft() : boolean
	operation omronFrontRight() : boolean
	operation omronRearLeft() : boolean
	operation omronRearRight() : boolean
	operation switchRecalFL() : boolean
	operation switchRecalFR() : boolean
	operation switchRecalRC() : boolean
	operation swallow(on : boolean)
	operation turnWheels(on : integer) //1 : swallow, 0 : stops, -1 : expulse
	operation lifter(up : boolean)
	operation lifterAtTarget() : boolean
	operation arms(left: integer, right : integer)
	operation armsAtTarget() : boolean
	operation turnCylinder(on : boolean)
	operation faceUpCylinder()
	operation getFaceUpStatus() : integer
	operation switchArmLout() : boolean
	operation switchArmLin() : boolean
	operation switchArmRout() : boolean
	operation switchArmRin() : boolean
	operation omronCylinder() : boolean
	operation switchCylinder() : boolean
	operation switchLifterUp() : boolean
	operation switchLifterDown() : boolean
	operation stockColor(): integer
	operation score() : integer
	operation robotStockCount() : integer
	operation nextCylinderColor() : integer
	operation containerCount(containerId : integer) : integer
	operation dispenserA_Count() : integer
	operation dispenserG_Count() : integer
	operation dispenserOppG_Count() : integer
	operation informWithdraw_A(nb: integer)
	operation informWithdraw_G(nb: integer)
	operation informWithdraw_OppG(nb: integer)
	operation informPooed_3(nb: integer)
	operation informPooed_4(nb: integer)
	operation informPooed_2(nb: integer)
	operation informPooed_5(nb: integer)
	operation informPooed_1(nb: integer)
	operation informPooed_6(nb: integer)
	operation informPooed_OnTable(nb: integer)
	operation informTaken_D()
	operation informTaken_F()
	operation informTaken_E()
	operation informTaken_B()
	operation informTaken_C()
	operation informTaken_Opp_D()
	operation informTaken_Opp_F()
	operation informTaken_Opp_E()
	operation informPushedAway_D()
	operation informPushedAway_F()
	operation informPushedAway_E()
	operation informPushedAway_B()
	operation informPushedAway_C()
	operation informPushedAway_Opp_D()
	operation informPushedAway_Opp_F()
	operation informPushedAway_Opp_E()
		var readonly FWD : integer =  1
		var readonly BWD : integer = -1
		//border enum
		var readonly TOP_Y : integer = 0
		var readonly OWN_SIDE_X : integer = 1
		var readonly OPP_SIDE_X : integer = 2
		var readonly START_AREA_Y : integer = 3
		var readonly BOT_Y : integer = 4
		var readonly START_AREA_X : integer = 5
		var readonly LED_OFF : integer = 0
		var readonly LED_ON : integer = 1
		var readonly SLOW_BLINK : integer = 2
		var readonly FAST_BLINK : integer = 3
		var readonly ledRED : integer = 0
		var readonly ledGREEN: integer = 1 		
		var readonly ledBLUE: integer = 2
		var readonly ledYELLOW: integer = 3
		var readonly ledCYAN: integer = 4		
		var readonly ledPURPLE: integer = 5 		
		var readonly ledWHITE: integer = 6
		var readonly cylUNKNOWN: integer = 0
		var readonly cylYELLOW: integer = 1
		var readonly cylBLUE: integer = 2
		var readonly cylWHITE: integer = 3
		var readonly NO_CMD: integer = 0
		var readonly FAILED: integer = 1
		var readonly OK: integer = 2
		var readonly NO_LSA : integer = 0
		var readonly SUCCESS : integer = 1
		var readonly FAILURE : integer = 2
		var readonly IN_PROGRESS : integer = 3
		var readonly LSA_A : integer = 0
		var readonly LSA_G : integer = 1
		var readonly LSA_OppG : integer = 2
		var readonly LSA_1 : integer = 3
		var readonly LSA_2 : integer = 4
		var readonly LSA_3 : integer = 5
		var readonly LSA_4 : integer = 6
		var readonly LSA_5 : integer = 7
		var readonly LSA_B : integer = 8
		var readonly LSA_C : integer = 9
		var readonly LSA_D : integer = 10
		var readonly LSA_E : integer = 11
		var readonly LSA_F : integer = 12
		var readonly LSA_OppD : integer = 13
		var readonly LSA_OppE : integer = 14
		var readonly LSA_OppF : integer = 15
		var readonly LSA_6 : integer = 16
		var readonly LSA_IA : integer = 17

**Comment by andreasmuelder** [comment]
This becomes obsolete when https://github.com/Yakindu/statecharts/issues/1151 is implemented

**Comment by wixiw** [comment]
agree

2017-05-05 10:40 GMT+02:00 Andreas Mülder <notifications@github.com>:
