### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by dmamalis** [Yakindu/statecharts#136]
The [link to your repository](https://github.com/Yakindu/base) seems to be broken.

**Comment by andreasmuelder** [comment]
The base repository was merged into https://github.com/Yakindu/statecharts/ and then deleted.
You can find the plugins under master/plugins/org.yakindu.base.*

**Comment by dmamalis** [comment]
Thanx for the info! Maybe you should update the installation instructions and remove that link :-)

**Comment by andreasmuelder** [comment]
Thanks for the hint, I updated the installation instructions accordingly!
