### ISSUE TITLE
Text not showing in definition block

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#138]
State names and declaration text is only visible during editing and disappears when the embedded editor is exited. 

Platform: Eclipse 4.4.0 on OSX Yosemite and El Capitan
See forum post: 

https://groups.google.com/forum/embed/?place=forum/yakindu-user#!topic/yakindu-user/G9F4fOAVTqE 

![2](https://cloud.githubusercontent.com/assets/1296498/10410937/6e6c140e-6f52-11e5-9f63-b5e516ec3264.png)
![1](https://cloud.githubusercontent.com/assets/1296498/10410938/6e6e9440-6f52-11e5-9812-7c52712230d8.png)
![3](https://cloud.githubusercontent.com/assets/1296498/10410936/6e69eb16-6f52-11e5-9c7e-386f68f79eef.png)

**Comment by andreasmuelder** [comment]
@terfloth could you check this I do not have a Mac ;)

**Comment by DominikTesch** [comment]
Hi
I can't reproduce your problem. I tried it on OSX El Captian with JDK 1.8 and 1.6 and Elcipse Luna.
