### ISSUE TITLE
Synchronization fires even when not all incoming states are active

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1386]
Synchronizations should only fire their outgoing transitions when source states are active.

However, a composite state containing an exit state can break this behavior at least in the simulation and can exit fire the synchronization without the other source state being active.

Example project attached. Just set x to 4 in the simulation, and `exit` becomes active **without** `a` being active.
[Synchronization.zip](https://github.com/Yakindu/statecharts/files/1014427/Synchronization.zip)

Tasks:
* [ ] Add as test
* [ ] Fix

**Comment by BeckmaR** [comment]
![default](https://cloud.githubusercontent.com/assets/15799654/26250310/e94c4934-3ca9-11e7-8e0b-2e7eb8a94927.jpg)

**Comment by terfloth** [comment]
nice test case ...

Assumption:
The transition from 'State1' to synch is also interpreted as the transition that has to be taken in the case of an exit. In this scenario an additional transition that does not target a sync node is required.

We need to:

- update the sequencer
- add validation

**Comment by tkutz** [comment]
I need some more clarification here. Let's take this slightly adjusted example. What shall happen when `x=1` is set. Shall transition `Composite_A->F` fire?

<img width="668" alt="bildschirmfoto 2018-07-12 um 11 41 43" src="https://user-images.githubusercontent.com/2589669/42625698-afa590aa-85c8-11e8-99e1-f0fdadce4e05.png">
