### ISSUE TITLE
Access the name value of states

### ISSUE THREAD

**Issue by arianaa30** [Yakindu/statecharts#139]
Currently it is not possible for Yakindu Statecharts to access the name value of states, regions, or other environmental values.

**Comment by terfloth** [comment]
What is the exact background of this feature request? As there are different possible approaches a short description of the usage scenario/use case would be great.

**Comment by arianaa30** [comment]
One thing was that we needed to know when a machine is now in a specific state. So a function like State1.isNowActive() which returns true or false given if the state is active. We can do that via flags inside states, but we should unset them whenever we are in other states- too much work!

**Comment by andreasmuelder** [comment]
There is a build in function active() (Press CTRL+space within the active function to get a list of all available states) Does this solve the issue?

**Comment by arianaa30** [comment]
I see. So active() basically returns list of all "active" states, is that correct? And what is the return type?

**Comment by andreasmuelder** [comment]
active takes the name of the state as an argument, for example
for example  active(main_statechart..main_region.A)  returns true if state A is active, false otherwise.

**Comment by arianaa30** [comment]
That would be best!

**Comment by andreasmuelder** [comment]
This is already implemented!
#Fixed
