### ISSUE TITLE
[GUI] Notes edition is not practical

### ISSUE THREAD

**Issue by wixiw** [Yakindu/statecharts#1392]
If a some difficulties to edit notes efficiently in the state machine graphical diagram editor. When I double click on a note the field is not editable, since I would expect it enters edition mode.

At present time I often go quickly in copying current text, deleting the note and creating a new one, which is not the expected workflow.

**Comment by BeckmaR** [comment]
I have to agree. I experienced the same problems with nootes and would say they are 90% broken right now.

**Comment by andreasmuelder** [comment]
This is an usability issue, the notes still use the old style to enter text edit mode (single click the label and wait) while all others use the new style (double click.)
