### ISSUE TITLE
Raise event based on operation callback

### ISSUE THREAD

**Issue by arianaa30** [Yakindu/statecharts#140]
Currently we can’t directly raise events on the state machine from the operation callback. I need to receive a value over socket network in my operation, and raise an event based on that. This is not yet supported.

**Comment by aboseley** [comment]
I think this is by design.  There are no event queues in yakindu you need to queue events outside the statemachine if this is what you need.  

https://groups.google.com/forum/embed/?place=forum/yakindu-user#!topic/yakindu-user/O9W7XJeIpcU

**Comment by terfloth** [comment]
This feature request is qualified as relevant. As this is an requirement that correlates with the execution of multiple state machines and Java classes within a simulation it will likely be part of a larger topic.

**Comment by BeckmaR** [comment]
This is now possible because in event queues have become available.
