### ISSUE TITLE
C++ generator should generate StatemachineInferface.h into libraryTargetFolder

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#1406]
Consider a scenario with multiple state machines. It makes sense to generate the base StatemachineInferface.h shared by all individual state machine headers into some common location, e.g.
````
[project]
 /common
    - StatemachineInterface.h
    - sc_types.h
 /machine0
   - M0.h
   - M0.c
 /machine1
   - M1.h
   - M1.c
````
However, this is currently not possible as StatemachineInterface.h is treated equally as the individual headers regarding generation target location.

We can solve this by defining that StatemachineInterface.h should be located under "libraryTargetFolder" (together with sc_types.h).

**Comment by BeckmaR** [comment]
Isn't this a dup of #1331, meaning that one should be closed as well?
