### ISSUE TITLE
Filter CycleBased, EventDriven & ExecutionOrder out of c-domain content assist of e.g. variable type

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#1419]
When using the content assist for e.g. variable types the proposals CycleBased, EventDriven & ExecutionOrder are provided, can be inserted and will not be validated even if they do not make sense at this position.

interface:
var pointA : CycleBased

**Comment by jdicks** [comment]
CycleBased & EventDriven aren't visible anymore as expected - ExecutionOrder is still visible

**Comment by jdicks** [comment]
There are 2 lements in Scope called ExecutionOrder:
1. the AnnotationType -> is filtered
2. the EnumerationType -> still visible

**Comment by andreasmuelder** [comment]
This is ok, I can't forbid references to Enumertion Types
