### ISSUE TITLE
TODO / FIXME Markers are broken

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#1429]
see comment on #706

**Comment by andreasmuelder** [comment]
@BeckmaR can you review the manual test cases if there is a test for TODO and FIXME markers?

**Comment by BeckmaR** [comment]
No, there hasn't ever been one. The whole documentation part of SCT might need some love in that regard.

**Comment by jdicks** [comment]
waiting for PR https://github.com/Yakindu/statecharts/pull/1468
