### ISSUE TITLE
Unable to download the program

### ISSUE THREAD

**Issue by MarkKroll** [Yakindu/statecharts#1430]
I could not find any place where to download the tool from. This page: https://github.com/Yakindu/statecharts has download and installation links. But the download link redirects to this page: https://info.itemis.com/state-machine/download-yakindu-statechart-tools, which looks to me like a sales lead form.

I am at the early stage of analysis for my non-commercial, open-source project. My plan is to use reactive programming, and I would love to use Yakindu statecharts to properly design the system dynamic behavior using Harel statemachines.

I am on a mac os, and I use RxSwift (I realize Swift is not supported by your tool, but code generation is not a must-have feature for me.)

Could you please point out where I can download the tool for non-commercial, open-source usage?

**Comment by andreasmuelder** [comment]
Great to hear that you want to use your tool for your project. After filling out the form you will get a download link per email where you can download our pro trials and also our community edition.

For future non technical questions you can use our user group:
https://groups.google.com/forum/#!forum/yakindu-user
