### ISSUE TITLE
Handle missing Xtext nature properly

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1439]
When a project is missing the xtext nature, generating code artifacts throws an NPE, as reported in #827.

Proposed by @andreasmuelder to resolve the issue:

> We should add a check in the SCTBuilder if the xtextNature is present. If not we should do nothing.
In the GenerateAction, we should show up the dialog if the user wants to add the XTextNature as in StatechartDiagramEditor#checkXTextNature

**Comment by andreasmuelder** [comment]
Can be closed. Prior to generation, the file is explicitly validated now and generating will result in the error message 'the file contains errors' This will force the user to open the file, the xtext nature is added then.
