### ISSUE TITLE
After creating a subdiagram, regions are positioned above each other

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1445]
- Unpack [twoRegions.zip](https://github.com/Yakindu/statecharts/files/1092168/twoRegions.zip) and open the statechart:
![auswahl_013](https://user-images.githubusercontent.com/1495781/27395064-cc1b082c-56ae-11e7-8a81-a2cee3df56d5.png)
- Right-click on the composite state C to open the context menu.
- Select _Refactor → Extract Subdiagram_.
- Open the subdiagram by clicking on the small symbol in state C.
Result: Only one of the regions is visible, because it covers the other. Move it to the side to unhide the other statechart.
![auswahl_014](https://user-images.githubusercontent.com/1495781/27395154-1648079c-56af-11e7-8435-d3137606703d.png)

**Comment by svenjawendler** [comment]
Here is an animated gif demonstrating this problem!
![extractsubdiagram_regions](https://user-images.githubusercontent.com/22005752/30267377-a52f6f0e-96e2-11e7-951a-68daf071bba7.gif)

**Comment by andreasmuelder** [comment]
This will be fixed via https://github.com/Yakindu/statecharts/pull/1890
