### ISSUE TITLE
Implement EventQueue

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1449]
For event-driven statecharts, all internal and in-events shall be queued. The runCycle function shall be executed as long as the queue is not empty.

**Comment by stmork** [comment]
We needed this feature request right today.
So: +1

**Comment by stmork** [comment]
Does the 'always' notation acts as an in event in terms of an event queue?

**Comment by terfloth** [comment]
No - it does not

**Comment by BeckmaR** [comment]
@stmork `always`, `oncycle`, `entry` et cetera are _triggers_, not events. Events can be used as triggers though.

**Comment by BeckmaR** [comment]
@terfloth, what about EventQueue for Java / C generators and how's the state of the simulation EventQueue?
