### ISSUE TITLE
Xtend missing in YSCT 3.0.0

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1510]
Xtend should be bundled with the product.

**Comment by RainerKlute** [comment]
By the way, this problem occured during manual test 7.1. I circumvented it by installing the Xpand SDK.

However, 7.3 led to a similar problem with *CustomGenerator.xtend* not being compiled to *CustomGenerator.java*. I installed the full Xtext, and all was fine.

**Comment by terfloth** [comment]
@andreasmuelder : please check ...

**Comment by andreasmuelder** [comment]
done
