### ISSUE TITLE
Stale error markers on sgen prohibit code generation

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1513]
1. Create two new projects, A & B
2. Create statechart & sgen in A, but sgen has targetProject B
3. Close project B
4. Error will appear in sgen because TargetProject can't be found
5. Open project B & open sgen
6. Error marker will go away but generation is only possible again when the sgen file is touched & resaved.

**Comment by andreasmuelder** [comment]
won't fix, underlying xtext framework is responsible for this
