### ISSUE TITLE
Downcast of scope object in custom code generator not working.

### ISSUE THREAD

**Issue by PGaus** [Yakindu/statecharts#1519]
In an custom Xtend generator we want to use following code:
`switch (scope) {
	InterfaceScope: scope.gen
	default: scope.toString
}
`
But the case is never reached. With each scope always the default is called.

With the two projects in [workspace.zip](https://github.com/Yakindu/statecharts/files/1159088/workspace.zip) we have an example showing this problem because there you see that line 33 of TestGenerator.xtend is never reached.  
Line 34 is the evidence that the scope object is of the type `org.yakindu.sct.model.stext.stext.impl.InterfaceScopeImpl`

After investigation into the problem a possible root cause could be that there are two different classloaders involved. You can see these if you execute `return scope.class.classLoader.toString + " " + InterfaceScopeImpl.classLoader.toString`

We already had a look to org.yakindu.sct.generator.runner.WorkspaceGeneratorExecutor.createInstance(GeneratorEntry, String) where the classLoader for generator runner is instantiated.

**Comment by andreasmuelder** [comment]
I can reproduce this on my machine. As suggested, it seems to be a class loading issue that has to be investigated further.

**Comment by andreasmuelder** [comment]
As discussed, we will remove the feature to develop code generators in the runtime in the next version 3.5.0. To develop a code generator, a developer workspace is required. Basic know-how about plugin development (PDE) is required.
