### ISSUE TITLE
Can't delete regions containing selected states

### ISSUE THREAD

**Issue by Timmmm** [Yakindu/statecharts#152]
~~If you select more than one region and press the delete key, nothing happens. With one region it works as expected.~~

If you select a region *and* a state it contains (e.g. using box-select) and press the delete key, nothing happens.

**Comment by andreasmuelder** [comment]
Minor fix scheduled for the next release, thanks for reporting!

**Comment by andreasmuelder** [comment]
Unfortunately I can't reproduce this, multiple Regions can be deleted when selected.
what does not work is deletion of a region when also a state that is contained in this region is selected.
Is this what you mean or can you provide additional information?

**Comment by Timmmm** [comment]
Ah yes that is what it must be. I selected multiple regions using a box select, which also selects the states in the regions. I'll edit the issue title.

**Comment by andreasmuelder** [comment]
Done

**Comment by Timmmm** [comment]
Thanks!
