### ISSUE TITLE
Welcome page: links to forum and issue tracker don't work

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1530]

**Comment by tkutz** [comment]
Works for me under MacOSX

**Comment by RainerKlute** [comment]
Okay, I assigned it to myself to investigate further on Linux.

**Comment by BeckmaR** [comment]
Works on my Linux machine. Ubuntu 16.10. Make sure you have a browser configured in SCT (Preferences - type "Browser" in the search field)

**Comment by RainerKlute** [comment]
Retested with the most recent product build and it still doesn't work for me in the default configuration.

I noticed the following messages on the console when clicking on the links:
```
env: „/some/dir/yakindu-sct/https:/groups.google.com/forum/#!forum/yakindu-user“: Datei oder Verzeichnis nicht gefunden
env: „/some/dir/yakindu-sct/https:/github.com/yakindu/statecharts/issues“: Datei oder Verzeichnis nicht gefunden
```

After changing the external browser in the preferences from "Default system web browser" to "Firefox", it works as expected. However, the user should not be required to do so in order to be able to access forum and issue tracker.

**Comment by andreasmuelder** [comment]
Platform dependend, closing
