### ISSUE TITLE
Wrong letter cases in error message

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1531]
The error message

```Outgoing Transitions from Entries can not have a Trigger or Guard.```

should read instead:

```Outgoing transitions from entry points can not have a trigger or guard.```

**Comment by rherrmannr** [comment]
wrong latter case, too

`Outgoing Transitions from Entries can only target to sibling or inner states.`

**Comment by RainerKlute** [comment]
There are likely many more of those. 😭

**Comment by BeckmaR** [comment]
That's a dup of the issue #559

**Comment by BeckmaR** [comment]
...and spelling errors are not bugs

**Comment by RainerKlute** [comment]
Oh, of course they are! Spelling errors are creating images in people's minds on how serious we are taking matters. Users might draw their own conclusions, conveying their impression on spelling quality to that of code quality, like it or not.
