### ISSUE TITLE
User-unfriendly error message regarding "SpecificationElement"

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1532]
The error message

```Duplicate SpecificationElement ‚A’ in Region ‚main region’```

should read instead:

```Duplicate state "A" in region "main region".```

**Comment by BeckmaR** [comment]
I can't figure out where that error message is defined. It's neither in the STextValidator nor in the SGraphValidator, and a full-text-search also couldn't find it.

**Comment by andreasmuelder** [comment]
The EValidator is NamesAreUniqueValidator and the error msg is generated in
INamesAreUniqueValidationHelper

**Comment by BeckmaR** [comment]
Closing in favor of #1742 where all error message issues are collected.
