### ISSUE TITLE
No subdiagram preview immediately after creation

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1535]
Immediately after creating a subdiagram, hovering over the decorator does **not** show the preview. Only after clicking elsewhere, the behaviour is as expected.

This is likely related to #1536.

**Comment by BeckmaR** [comment]
Can't reproduce, works as expected in newest Product Build

**Comment by andreasmuelder** [comment]
Can't reproduct this with product and runtime, please reopen with detailed steps to reproduce if this error still exists.
