### ISSUE TITLE
 No subdiagram editor on click immediately after creation

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1536]
Immediately after creating a subdiagram, clicking on the decorator does **not** open the subdiagram in a new editor tab. You have to click a second time.

This is likely related to #1535.

**Comment by BeckmaR** [comment]
Can't reproduce, works as expected in newest Product Build

**Comment by andreasmuelder** [comment]
Can't reproduct this with product and runtime, please reopen with detailed steps to reproduce if this error still exists.
