### ISSUE TITLE
Undoing subdiagram extraction does not always work

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1537]
I observed this at least twice, but haven't been able to reproduce the exact conditions. Anyway, at least here is one path to reproduce the faulty behaviour; there might be more.
1. Extract the subdiagram.
1. Click on the decorator (twice, see issue #1536). The subdiagram editor opens.
1. Close the subdiagram editor (without saving).
1. Press [Ctrl+Z] or select *Edit → Undo Refactoring Command*. Nothing happens.

**Comment by BeckmaR** [comment]
Related to:
* #1137 
* #803

**Comment by BeckmaR** [comment]
Actually, exact duplicate of #1137
