### ISSUE TITLE
[Example wizard] User gets lost when download fails

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1539]
If downloading the repository fails, it is not obvious to the user what he could to do next and how he should proceed.

**Comment by andreasmuelder** [comment]
![fail](https://user-images.githubusercontent.com/6338708/34487106-1fc7baf2-efd3-11e7-9581-c3c0d75d3bd6.png)

Closing, the error message and the provided link is enough information to install the examples manually.
