### ISSUE TITLE
"Junction" is missing

### ISSUE THREAD

**Issue by Timmmm** [Yakindu/statecharts#155]
The documentation mentions a "junction" element which sounds useful. Unfortunately it is currently not available. According to a comment I found somewhere on the web it is because the code gen doesn't support it.

The documentation should remove references to the junction, or at least note that it isn't actually available.

**Comment by terfloth** [comment]
We support no junctions use choices instead. 
@RainerKlute : remove from docs

**Comment by RainerKlute** [comment]
Has been removed from the user documentation. However, the website still needs to be updated.
