### ISSUE TITLE
[Documentation] Write a new section on execution semantics

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1561]

**Comment by andreasmuelder** [comment]
@Rainer so this can be closed?

**Comment by RainerKlute** [comment]
Reopened this issue since this is still not done. We don't describe the execution semantics properly or at least concisely and completely yet.

**Comment by RainerKlute** [comment]
The work I have done so far is on the _doc/1561_execution_semantics_ branch. I covered the following topics:
* The state vector
* Initializing a state machine
* Entering and exiting a state machine
* Entering and exiting a region
* Entering and exiting a state
* The run cycle
  * React methods of states
* Checking the active state for actions to be performed
* Transitioning from one state to another state

However, the explanations are still incomplete and have a varying level of details. They should not yet be merged into the master.
