### ISSUE TITLE
Mouse pointer messed up.

### ISSUE THREAD

**Issue by muehlbrandt** [Yakindu/statecharts#160]
If the mouse pointer is moved above a transition it is messed up. This can be reproduced under Linux with Eclipse Mars.

![bug](https://cloud.githubusercontent.com/assets/8243759/10879423/216a1480-8154-11e5-9747-f79e33769c30.png)

**Comment by terfloth** [comment]
@muehlbrandt : Please analyze problem.

**Comment by muehlbrandt** [comment]
This problem occurs if GTK3 is used by SWT. GTK3 scales the Mousepointer within Eclipse to fit into high DPI screens.  If Eclipse is started with SWT_GTK3=0 environment variable GTK2 is used by SWT and the bug disappears (Mouse isn't scaled anymore).

There are some pending bugfixes for the Eclipse Neon release addressing scaling problems with GTK3 and high DPI screens. Maybe they also fix the messed up mouse pointer.
