### ISSUE TITLE
Provide constant that provides the maximum number of parallel time events of a state machine

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#1600]
In application scenarios that require implementations of timer services with static allocation of buffers this value will be relevant to set the correct dimensions. 

Currently the C++ code generator defines a constant for the overall number of time events used in a state chart. But as time events are often exclusive to each other this value is safe but may be too large.

**Comment by andreasmuelder** [comment]
@terfloth  is this issue fixed ?

**Comment by terfloth** [comment]
no
