### ISSUE TITLE
Reaction trigger "after" with Variable as time

### ISSUE THREAD

**Issue by DefCon-CC** [Yakindu/statecharts#1606]
Is it possible to have something like this:

var EXT_SET_TIME_VAR : integer
after EXT_SET_TIME_VAR ms

instead of defining

after 10 ms

with fixed time in statechart? I would like to fill the variable EXT_SET_TIME_VAR from the outside of the statechart because I have many instances of the same statechart which needs to have different delay times.

**Comment by terfloth** [comment]
Just do it - it is already possible. Perhaps you should specify a default value for the variable.

**Comment by DefCon-CC** [comment]
Great I will give it a try!
