### ISSUE TITLE
C++ shadowing errors for member variables

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#1612]
We got following request:

> Problem:
>  
> In member function 'virtual void MyTimedStateMachine::setTimer(TimerInterface*)':
> build/yakindu/Release/board/MyTimedStateMachine.cpp:NNN:NN: error: declaration of 'timer' shadows a member of ' MyTimedStateMachine ' [-Werror=shadow]
>  
> Solution:
>  
> Prefix data members with “m_” to make the data member’s name m_timer.

**Comment by BeckmaR** [comment]
We really should ask users who complain about compiler errors to provide their used compiler and the compiler settings / options.

**Comment by tkutz** [comment]
OTRS Ticket ID: Ticket#2017081837000031
