### ISSUE TITLE
[Documentation] Variables in SGen

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#1643]
Variables can now be used in SGen like this:

GeneratorModel for yakindu::java {

 var targetSubFolder : string = "mySubFolder"
 var generateTimerServce : boolean = true

statechart ECU_B {   

    feature Outlet {
        targetProject = "TargetProject"
        targetFolder = "target/" + targetSubFolder
        libraryTargetFolder = "src"
    }  
    
    feature GeneralFeatures {
        TimerService = generateTimerServce
    }
}
}

These variables can also be overriden for the headless build with scc -v name=value;name2=value2

**Comment by BeckmaR** [comment]
Also, do not forget to update the output of `scc` in the documentation (or revalidate if it's actually needed there)

**Comment by RainerKlute** [comment]
Incorporated in pull request #1676.
