### ISSUE TITLE
Java code generator creates "magic" package

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1658]
If no base package is specified, like in the generator model below, the Java code is created in the "magic" package _org.yakindu.scr_ + statechart name. YSCT should either generate the classes in the default package instead, or the generator model should *require* the user to specify a base package.

```
GeneratorModel for yakindu::java {

	statechart light_switch {

		feature Outlet {
			targetProject = "light_switch"
			targetFolder = "src-gen/state_machine/java"
		}
	}
}
```

**Comment by BeckmaR** [comment]
The project name might be another good default option. I believe it's what eclipse likes to use as well.
