### ISSUE TITLE
Java code generators: inconsistent targetFolder behavior

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1659]
The Java code generators for state machines and for SCTUnit tests behave inconsistently regarding the Outlet feature's _targetFolder_ property if the generator model is located in a subdirectory, say _codegen_.

The state machine code generator interprets a relative _targetFolder_ value like "src-gen" as being relative to the directory the generator model is located in and creates the directory _codegen/src-gen_. A path relative to the project root can be specified as ```targetFolder = "/src-gen"```.

The SCTUnit code generator, however, interprets a relative _targetFolder_ value like "src-gen" as being relative to the project root and creates the directory _src-gen_.

**The SCTUnit code generator should behave like the state machine code generator.**

**Comment by andreasmuelder** [comment]
@RainerKlute please move this to scpro repo

**Comment by RainerKlute** [comment]
Moved to sctpro repository.
