### ISSUE TITLE
SCTUnit code generator pulls folder names into package names

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1662]
I have the following generator model:
```
GeneratorModel for sctunit::java {

	test foo.light_switch.test.light_switch_tests {

		feature Outlet {
			targetProject = "light_switch"
			targetFolder = "src-gen/sctunit/java"
		}

		feature Naming {
			basePackage = "bar.light_switch.tests"
		}

		feature StatechartNaming {
			basePackage = "bar.light_switch"
			implementationSuffix = "impl"
			libraryTargetFolder = "src-gen/sctunit/java_ltf"
		}

	}
}
```

I'd expect the package name of the generated classes to be _bar.light_switch.tests.foo.light_switch.test_. However, it is _sctunit.java.bar.light_switch.tests.foo.light_switch.test_. Obviously the code generator pulls the components of the _targetFolder_ into the package name, except for the first one.

**Comment by andreasmuelder** [comment]
@RainerKlute please move this to pro repo

**Comment by RainerKlute** [comment]
Moved to sctpro repository.
