### ISSUE TITLE
C++ generator: inconsistent types used for index into stateConfVector (signed / unsigned compare)

### ISSUE THREAD

**Issue by DanielBernhard** [Yakindu/statecharts#1679]
The maxOrthogonalStates variable (used to define the dimension of the stateConfVector array) is an sc_integer (e.g. int32_t) while the stateConfVectorPosition variable (used to access the array) is an sc_ushort (e.g. uint_fast16_t).

This is inconsistent and leads to "signed/unsigned compare" warnings of the compiler.

While I agree that the actual danger is non-existing (I don't assume that we ever have more than 16'000 orthogonal states) I don't think that this would be very hard to fix (change maxOrthogonalStates to sc_ushort and fix the type of the loop variable in the init function).
This would lead to consistent code (and fewer compiler warnings...)

**Comment by terfloth** [comment]
I completely agree. Issue is scheduled ...

**Comment by BeckmaR** [comment]
@terfloth - should we use `sc_integer` or `sc_ushort`for both?

**Comment by andreasmuelder** [comment]
@BeckmaR I think we can use sc_ushort as proposed

**Comment by terfloth** [comment]
Yes - sc_ushort fits well

**Comment by andreasmuelder** [comment]
fixed via #1845
