### ISSUE TITLE
Provide syntax-coloring for specification labels

### ISSUE THREAD

**Issue by jdicks** [Yakindu/statecharts#1687]
Currently the syntax highlighting is just visible if the embedded editor of a specification element is active.
This should be changed to show the highlighting if the editor is inactive also.

Besides there is an additional aspect where it would be nice to ensure a correct/unified indentation for the label and the embedded editor.

**Comment by BeckmaR** [comment]
Related to #1442

**Comment by andreasmuelder** [comment]
First implementation in branch https://github.com/Yakindu/statecharts/tree/issue_syntax_coloring_label
