### ISSUE TITLE
Timer does't work with ms, us and ns

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#169]
<img width="1411" alt="bildschirmfoto 2015-11-13 um 13 04 10" src="https://cloud.githubusercontent.com/assets/15800400/11145622/71c4e8f4-8a07-11e5-999e-b78df14e0754.png">
If you use 'ms' on the left interface window your timer won't work in your Statechart simulation. You stop in the 'aa' state and it doesn't go to the next one after 2s. But if you use 's' it will work. Moreover if you use 'us' and 'ns' you will get this error.
<img width="1383" alt="bildschirmfoto 2015-11-13 um 13 14 38" src="https://cloud.githubusercontent.com/assets/15800400/11145755/ca09e5c2-8a08-11e5-85e9-0c5c01e753cc.png">

**Comment by DominikTesch** [comment]
![1oversizeok sct](https://cloud.githubusercontent.com/assets/15800400/11147441/2f7cf5f4-8a16-11e5-9f4c-d5f365adbdd2.jpg)
The .sct project as .jpg

**Comment by andreasmuelder** [comment]
Fixed for M22
