### ISSUE TITLE
Add namespace support for C++ code generator  

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#1705]
The C++ code generator should provide a feature to specify the namespaces that should be used by:

- the generated state machine classes
- the interface types like StjatemachineInterface, TimedStatemachineInterface, TimerInterface...

**Comment by tkutz** [comment]
We could use the namespace feature from the definition section.

**Comment by BeckmaR** [comment]
@tkutz However, it would probably not be useful to put the `StatemachineInterface` and the likes into the namespace of the statemachine - consider the case where you have two statecharts with different namespaces, generate both into the same folder, the first statechart's interfaces would be overwritten by the second one.
