### ISSUE TITLE
[Linux] Refactoring within a statechar does not work

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#1734]
For Example:
You can't rename a variable name in the definition section/or any state.

@BeckmaR can you test this?

**Comment by BeckmaR** [comment]
Don‘t need to, I know it doesn‘t work. All text widgets loose focus on right click.

René Beckmann

**Comment by rherrmannr** [comment]
Does this issue already exist?

**Comment by BeckmaR** [comment]
It did, see #661, but it's closed because its author @RainerKlute said it would be working again. I can't remember it doing so, but I will re-test it tomorrow.

**Comment by BeckmaR** [comment]
Yeah, the issue does persist, I will re-open the old issue.
