### ISSUE TITLE
Changing the highlighting of time units in the Statechart Editor

### ISSUE THREAD

**Issue by jthoene** [Yakindu/statecharts#1735]
It looks a little bit confusing, if the time units have the same highlighting as the keywords.
For example if i have a expression on a transition like: 

> **after** 10**s**

It looks like the "10" is at the wrong place, especially in the Statechart Editor, where the keywords are not only highlighted bold but also in a different color.
Of course this may be a personal preference, but we should consider highlighting time units seperately.

**Comment by andreasmuelder** [comment]
@jthoene  @BeckmaR Please make a proposal how this could look like, this can be fixed easily

**Comment by andreasmuelder** [comment]
Not clear what to do here, closing for now.
