### ISSUE TITLE
Rework error messages

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1742]
As there were a lot of issues concerning error messages given by SCT that somewhat overlapped, it makes sense to tackle all of these problems at once.

* Orthography: #559
* Helpfulness: #305, #1532
* Provide documentation about error messages, and especially solutions: #330
* Provide examples in error messages: #1283

Basically what should be done is the following:

* Collect all error messages we do have in one place, for example an interface or a specialized class. -> Allows for easier verification of correctness, and easier checking where a specific error comes from.
* Fix all typing errors.
* Add error numbers to all error messages.
* Add error numbers to documentation, and document reasons, fixes and examples for correct input.

I will close all linked issues in favor of this one to clean up our issue backlog.

**Comment by andreasmuelder** [comment]
Closing this as all referenced issues are fixed.
