### ISSUE TITLE
TypeCastExpression should work on TypeSpecifier instead of Type

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#1761]
Otherwise we cannot cast to a generic type.

Using type specifier is also more consistent as we already use to wrap all other type references.

**Comment by svenjawendler** [comment]
The expression "tmp as string" has no effect. I try to cast an integer to string, integer to real, real to integer, string to boolean.

**Comment by svenjawendler** [comment]
A question regarding type casts came up recently in the google group.

**Comment by BeckmaR** [comment]
Resolved for future release
