### ISSUE TITLE
NPE with SCTUnit

### ISSUE THREAD

**Issue by svenjawendler** [Yakindu/statecharts#1764]
See screenshot:
![problemwithsctunit](https://user-images.githubusercontent.com/22005752/33375097-176c643c-d509-11e7-938b-cf2a4718b2c2.png)
It is not clear what the problem is here.

**Comment by svenjawendler** [comment]
Solution: add a validation rule: Parameters are not allowed within test declarations (or something like that).

**Comment by andreasmuelder** [comment]
Moving this to SCTpro repository
