### ISSUE TITLE
SCTUnit: Test does not compile but runs green

### ISSUE THREAD

**Issue by svenjawendler** [Yakindu/statecharts#1765]
See screenshot: Test does not find the statechart, but when I run it it complains about not compiling project, I am able to skip it and run the test and it is green.
![testdoesnotcompilebutunittestshowsgreen](https://user-images.githubusercontent.com/22005752/33376365-b2fcfdd6-d50d-11e7-8409-659518e619e9.png)

**Comment by BeckmaR** [comment]
SctUnit is not open source.
