### ISSUE TITLE
Add permalinks to documentation

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#1766]
Add Permalinks to the documentation, see for example https://docs.readthedocs.io/en/latest/
if you hover besides a headline, there is a permalink to that chapter that you can send.

**Comment by RainerKlute** [comment]
Fixed with pull request #1883.

**Comment by andreasmuelder** [comment]
The link URI should be copied to the clipboard when clicked.

**Comment by RainerKlute** [comment]
Fixed with full request #1917.
