### ISSUE TITLE
Hard plugin-dependency to org.apache.log4j instead of import-package

### ISSUE THREAD

**Issue by maximilianost** [Yakindu/statecharts#1768]
To be able to change the log4j implementation (e.g. by the implementation log4j.over.slf4j) it is necessary to not use Require-Bundle but instead use Import-Package.

But in the MANIFEST.MF of org.yakindu.sct.model.stext this is done.

Can you please change this?

**Comment by andreasmuelder** [comment]
@maximilianost that makes sense can you create a PR?

**Comment by maximilianost** [comment]
sorry, not allowed to do that...
