### ISSUE TITLE
Place Version Info into generated Code

### ISSUE THREAD

**Issue by DefCon-CC** [Yakindu/statecharts#1770]
It would be great when Yakindu SCT could place Version Info (Yakindu SCT Version, ....) into generated code.

**Comment by BeckmaR** [comment]
This is a good idea! The linked PR contains new builtin variables which you can refer to in your sgen file. This allows you to put the current SCT version, the timestamp, the user's name and the hostname into whatever string you want to.

For example, this sgen:
```
GeneratorModel for yakindu::cpp {

	statechart statechart {

		feature Outlet {
			targetProject = "Project"
			targetFolder = "src-gen"
			libraryTargetFolder = "src"
		}
		feature LicenseHeader {
			licenseText = "Generated on " + TIMESTAMP + " with YAKINDU SCT " + SCTVERSION + " by " + USER + " on " + HOSTNAME
		}
	}
}
```

generates the following license header into the generated files:
```
/* Generated on 11.12.2017 17:08:14 with YAKINDU SCT 3.2.0 by BeckmaR on BeckmaR */
```

**Comment by DefCon-CC** [comment]
Great. Thanks!

**Comment by andreasmuelder** [comment]
As commented by @RainerKlute we should use ISO-8601-Format for the date: YYYY-MM-TT.

**Comment by BeckmaR** [comment]
Closing as discussed with @andreasmuelder - the current date format is simply localized, as stated in the documentation.
