### ISSUE TITLE
3.2.0 Test - DefinitionSection: if it is pinned no errors, warnings are shown

### ISSUE THREAD

**Issue by svenjawendler** [Yakindu/statecharts#1794]
On Windows: If the definitions section is pinned neither the diagram nor the problems view shows any warnings or errors, though there are problems.
If I unpin it again the errors/warnings come back.
![nowarningonemptytransition](https://user-images.githubusercontent.com/22005752/33927976-712cb806-dfe4-11e7-8bb9-e806a597edab.png)

**Comment by svenjawendler** [comment]
A clean project seems to solve the problem. If I clean the project the markers are there. If I pin the definition section and solve the warnings errors the problems view is not updated. A clean project solves this.

**Comment by svenjawendler** [comment]
Another problem: When the definition section is in pinned state the pin icon seems to overlap the error marker. Fact is I do not see any error marker than. In the former version the markers were at the same position like the pin icon now is.
![definitionsectionerrormarkersannotations](https://user-images.githubusercontent.com/22005752/33928421-2bc2cae2-dfe6-11e7-999e-2938a187a21c.png)

**Comment by andreasmuelder** [comment]
@svenjawendler should be fixed, please reopen if the error still exists
