### ISSUE TITLE
Simulation for a single named initial state broken

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#184]
If the initial entry node have a name the simulation doesn't work. It doesn't highlight a state.
![default](https://cloud.githubusercontent.com/assets/15800400/11299945/5392a36a-8f8b-11e5-85e4-8b9978d6cd8e.png)
Maybe an error marker should be added

**Comment by andreasmuelder** [comment]
The STextJavaValidator#checkUnboundEntryPoints should also check the top level reginos

**Comment by terfloth** [comment]
No named entries should be allowed in top level regions for now.
