### ISSUE TITLE
Uninstall Destroys Eclipse Java Perspective (and leaves some Yakindu trash behind)

### ISSUE THREAD

**Issue by tom131313** [Yakindu/statecharts#1843]
On Windows 10, Eclipse Version: Neon.3 Release (4.6.3), I uninstalled (Help, Installation Details, Uninstall) all Yakindu named software from Eclipse list of installed software.  My Java installation disappeared.  A few remnants of Yakindu still remain in Eclipse folders and files.  Three perspectives remain in name only: Java, SC Modeling, SC Simulation.  I'm out of business and looking at many, many hours to recreate my Eclipse Java workspace.  What a mess.  Free software often isn't free, is it.

**Comment by andreasmuelder** [comment]
I can not reproduce this issue with the following steps:

- Download clean Eclipse Neon 4.6.3
- Installed latest YAKINDU Statechart Tools 3.1 Standard and Professional 
- create new Java Project, create new Java Class, create new Statechart
- uninstalled all YAKINDU Features (Help, Installation Details, Uninstall) 

After uninstall, Java and JDT are still there and working properly. 
The shortcuts for the perspectives are  stored in the workspace metadata (eclipse default) and can be removed via Preferences / General / Perspectives

Closing this issue, feel free to reopen it with proper steps to reproduce.
