### ISSUE TITLE
[Documentation] Review search feature description

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1847]
See pull request #1846.

**Comment by RainerKlute** [comment]
I did a first round of review, based on the documentation only. This still requires some work, for which I'd need YSCT executable which includes the search function.

**Comment by RainerKlute** [comment]
My current state of knowledge is consolidated in the _doc/search_ branch now.

**Comment by tkutz** [comment]
Reviewed and merged: https://github.com/Yakindu/statecharts/pull/2122
