### ISSUE TITLE
Java generator issue in TrafficLights example

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#186]
I tried to reproduce the Java version of the TrafficLight model. However, if you clean the project with "Build Automatically" being turned on, the following error message appears:

![screenshot_genmodeljava](https://cloud.githubusercontent.com/assets/1495781/11340532/8d3b1564-91fe-11e5-9d38-d3a5ec3232f7.png)

Everything works fine if you "Generate Code Artifacts" on the generator model or if you switch off the automatic project build and instead "Clean …" and "Build project" manually as separate steps.

**Comment by andreasmuelder** [comment]
Thanks for reporting, this is already fixed in master
