### ISSUE TITLE
Missing builder in C TrafficLights example

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#188]
I tried to re-create the C version of the TrafficLights example. Even after installing the PDE and CDT plugins, Eclipse still complains about a missing builder:

![screenshot_missingbuilderqt](https://cloud.githubusercontent.com/assets/1495781/11340974/b9f4e970-9200-11e5-8d03-87ada5fba1ad.png)

**Comment by andreasmuelder** [comment]
does this example require Qt?

**Comment by RainerKlute** [comment]
Looks like it does. It includes quite a couple of Qt widgets.

**Comment by andreasmuelder** [comment]
I removed this from the example wizard and added it to the archive git folder
