### ISSUE TITLE
"Yakindu" should read "YAKINDU"

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#189]
User-visible occurences of the string "Yakindu" should be replaced by "YAKINDU" in the software.

**Comment by andreasmuelder** [comment]
@RainerKlute Did you replace this in the documentation?

**Comment by RainerKlute** [comment]
Sure, I did – except for those places that are quoting the user interface verbatim.

**Comment by DominikTesch** [comment]
Fixed
