### ISSUE TITLE
README.md "Follow the installation instructions" link broken

### ISSUE THREAD

**Issue by marcindulak** [Yakindu/statecharts#1916]
https://github.com/Yakindu/statecharts/blob/master/plugins/org.yakindu.sct.doc.user/src/installation/installation.textile

should be

https://github.com/Yakindu/statecharts/blob/master/plugins/org.yakindu.sct.doc.user/src/user-guide/installation.textile

**Comment by andreasmuelder** [comment]
fixed, thanks for reporting !
