### ISSUE TITLE
Integer comparison is not working in Yakindu Professional

### ISSUE THREAD

**Issue by byrzish** [Yakindu/statecharts#1919]
With Yakindu Professional version 3.1.1 integer comparison is not working
in transition guards. If a variable is defined like this: var test: integer,
then in the transition if I try: [test == 1], I get error "Comparison operator '==' may only be applied on compatible types, not on integer and integer". The same with events with value. If the event is defined like this: interface: in event test: integer, then in the transition if I try: test [valueof(test) == 1], I get the same error. This is working on the Standard edition version 3.1.1.

**Comment by andreasmuelder** [comment]
I can not reproduce this problem.
@byrzish Can you update to latest YAKINDU Professional 3.2 and check if the error still occures?

**Comment by andreasmuelder** [comment]
Please reopen with steps to reproduce if this error still occures in the current version
