### ISSUE TITLE
Definition section should keep its width

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#1923]
When resizing the statechart editor view, the definition section should keep its width. Otherwise ugly things like this happens:

This is my starting point:
![grafik](https://user-images.githubusercontent.com/1495781/36495161-b263558c-1734-11e8-8339-184bad234843.png)

Now I am making the statechart editor view smaller. And the definition section gets totally distorted:
![grafik](https://user-images.githubusercontent.com/1495781/36495494-ae5007fa-1735-11e8-836a-72309467f33c.png)

**Comment by robert-rudi** [comment]
With the new embedded xtext editor, the definition doe not get distorted anymore. You will get a horizontal scrollbar for contents that are not visible in the definition section. 
The diagram editor will keep the width percentages between the definition section and the diagrams contents.
