### ISSUE TITLE
Missing label in generated documentation

### ISSUE THREAD

**Issue by Bananeweizen** [Yakindu/statecharts#1947]
When trying to open the documentation, I see this in the error log:
`Required attribute "label" missing from "topic" element in "/org.yakindu.sct.doc.user/help/user-guide/c-domain-toc.xml" (skipping element)
`

Indeed, c-domain-toc.xml contains this in line 3:
`<topic href="help/user-guide/c-domain.html" label=""></topic>`

**Comment by svenjawendler** [comment]
This is due to h1{%EARLY_SEPARATOR%}. @RainerKlute I do not want to damage something. Can you take a look at this?

**Comment by RainerKlute** [comment]
Yes, it is. It doesn't do any harm that I'd be aware of (except for the warning), so please bear with it.

**Comment by paphko** [comment]
![image](https://user-images.githubusercontent.com/6435623/91716051-2c0b2500-eb8f-11ea-9367-bc149b388980.png)

It's actually reported as errors when opened in a new (empty) workspace.
