### ISSUE TITLE
C code generator should allow to specify a maximum non-unique identifier length.

### ISSUE THREAD

**Issue by nyssen** [Yakindu/statecharts#196]
In addition to restricting the overall length of identifier, it would be nice if the generator would offer an option to enforce that two identifiers differ from some index position onwards via the IdentifierSettings feature. This would allow to follow MISRA-C:2004 Rule 05.01. without having to restrict the names in the overall.

**Comment by terfloth** [comment]
relates to rework of naming service

**Comment by BeckmaR** [comment]
We decided against this in favor of a solution that moves the responsibility for the generated names to the user, by providing feedback about the given names. This is done by #1912 and its accompanying PR in the pro repo.
