### ISSUE TITLE
interpreter does not process internal events correctly in event driven execution mode

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#1962]
The current implementation of the interpreter does not process internal events correctly. It seems that an internal event is just partly processed for one region.

The attached project includes a test model and a unit test. The test case defines how the interpreter should behave. The unit tests is successful with the last release but fails with a current product build.

Todo
* We have to check what changed in the interpreter implementation and / or the model sequencer since the last release.
* check the behavior of code generators

**Comment by terfloth** [comment]
[event_driven_test.zip](https://github.com/Yakindu/statecharts/files/1828868/event_driven_test.zip)

**Comment by andreasmuelder** [comment]
may be a regression introduced with https://github.com/Yakindu/statecharts/issues/1880

**Comment by andreasmuelder** [comment]
This is also not working in release 3.2.0.

**Comment by terfloth** [comment]
@andreasmuelder  your assumption was right - the cause was introduced with #1880 .
Debugging more deeply i came across another (more fundamental and ugly) problem.  The simulation engine executes some extra cycles. ...

I will take the ticket and go for a testing deep dive...

**Comment by andreasmuelder** [comment]
the problem here is a duplicate enumeration, I fixed this and will create a PR.
