### ISSUE TITLE
[Pinned Definition Section] Two different kinds of error markers

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#1971]
Seems like depending on origin of error (Xtext framework vs our own validations) the error icon is different. This is a bit confusing.

<img width="210" alt="bildschirmfoto 2018-03-21 um 11 28 53" src="https://user-images.githubusercontent.com/2589669/37705151-564809c8-2cfb-11e8-9136-6bbc569595c6.png">

**Comment by andreasmuelder** [comment]
The first icon indicates an error where a quick fix is available. Since we can not execute the quickfixes I agree that we should disable this for now until we provide a meaningful set of quickfixes
