### ISSUE TITLE
[Definition Section] Content assist broken

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#1975]
First it worked well. Then after a while it didn't anymore. Still need to find out what caused the behavior.

I basically did two things before I realized it is broken:
1. Enable syntax coloring in preferences
2. Pin and unpin the definition section

<img width="876" alt="bildschirmfoto 2018-03-21 um 11 50 05" src="https://user-images.githubusercontent.com/2589669/37705979-15698df2-2cfe-11e8-9929-a511c9479a57.png">

**Comment by tkutz** [comment]
Could not reproduce anymore after restart of tool

**Comment by robert-rudi** [comment]
I couldn't reproduce
