### ISSUE TITLE
[MacOS] Ctrl + Space on states doesn't seem to work

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#2042]
On my system, when selecting a state and then using control + space, the content assist does not work. Instead, the state gets selected with a blue border, and the properties view jumps to the statechart's properties. Ctrl + Space works fine everywhere else.

@tkutz please verify

**Comment by tkutz** [comment]
I can confirm that you need to press Ctrl-Space twice for the graphical content assist. 
This is different from the normal behavior and confusing for the user.
