### ISSUE TITLE
always, oncycle, every and after may be used as names for 'in events'

### ISSUE THREAD

**Issue by herrendorf** [Yakindu/statecharts#2045]
The internal event names `always`, `after`, `oncycle` and `every` may be used as names for `in events`:

```
@CycleBased(200)

interface:
// Define events and
// and variables here. 
//Use CTRL + Space for content assist.

in event always 
```

This causes an ambiguity, if the event is used on  transition.

**Comment by herrendorf** [comment]
`after` and `every` already break the parser and cause a `STextParser$SyntaxEception`. So an error is shown, but the message is rather confusing:
```
No viable alternative at input 'after'
Qualified name cannot be null```

**Comment by andreasmuelder** [comment]
same for exit and entry triggers

**Comment by andreasmuelder** [comment]
fixed by https://github.com/Yakindu/statecharts/pull/2057
