### ISSUE TITLE
No error is shown, if region contains an unnamed and a 'default' named entry

### ISSUE THREAD

**Issue by herrendorf** [Yakindu/statecharts#2051]
If I put an entry node without a name and another one named 'default' in a region, it's not recognized as duplicate entries. But in fact they're duplicates, because they're semantically equivalent (  [see doc](https://www.itemis.com/en/yakindu/state-machine/documentation/user-guide/sclang_statechart_language_reference#sclang_named_entries) )

**Comment by andreasmuelder** [comment]
Merged into https://github.com/Yakindu/statecharts/pull/2056/commits/52277daf92cd620f74b416a80b1518090a7961aa
