### ISSUE TITLE
Smell: Contradicting triggers on a transition

### ISSUE THREAD

**Issue by herrendorf** [Yakindu/statecharts#2055]
A reaction trigger like
```
always, after 10s
```
is useless, because `always` wins every time. ~~And it makes only sense, if `@CycleBased()` is enabled.~~
But the situation looks different, if there's guard. See #2053 for more information on that.

**Comment by herrendorf** [comment]
I'll submit a PR, if the issues of #2054 have been discussed.

**Comment by herrendorf** [comment]
Thanks for the information - I just didn't know that. We only used the `@CycleBased` in our university class. I've updated my first post.

**Comment by terfloth** [comment]
As there are cases which make sense in event-driven and cycle-based execution we will close the issue.
