### ISSUE TITLE
Missing validation rule for exit point without default trigger

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#2068]
The following example does not produce an error. 
![default](https://user-images.githubusercontent.com/6338708/40104967-f32bbd1c-58f1-11e8-8cd7-606f6f2d97dd.png)

When simulating, the state machine is in an invalid state with 0 active states.

**Comment by BeckmaR** [comment]
TODO:

* [ ] Fix check for non-existing exit transition
* [ ] Improve error messages
* [ ] Add or improve tests for transition priority handling etc
* [ ] Add or improve tests for validation of exit points
* [ ] Explain exit transitions in the documentation
