### ISSUE TITLE
Operations in different interfaces but with the same name

### ISSUE THREAD

**Issue by PaulWu7323** [Yakindu/statecharts#2095]
As discussed in the Yakindu User group: [https://groups.google.com/forum/embed/?place=forum/yakindu-user#!topic/yakindu-user/epCpV0LRqMg](https://groups.google.com/forum/embed/?place=forum/yakindu-user#!topic/yakindu-user/epCpV0LRqMg)

Steps to reproduce the issue:
1. Two operations with the same name but in two different interfaces. For example:
```
interface PlusOne:
operation add(num:integer):integer
interface PlusTwo:
operation add(num:integer):integer
```
2. Create two Java classes with the interface names and implement the methods. For example:
```
PlusOne.java
public class PlusOne {
    public long add(long num){
        return num+1;
    }
}
```
```

PlusTwo.java
public class PlusTwo {
    public long add(long num){
        return num+2;
    }
}
```

3. In the run configuration, add the Java class names to the Operation Class field.

4. Only one of the methods is invoked in the simulation. 
![](https://lh3.googleusercontent.com/-5Dv2_hXEkUA/Wxqjbw4gwYI/AAAAAAAADQ0/ZaQhntQMVVM9pp6oKxq7DRJwjfOPxik_gCLcBGAs/s1600/multi_operations.png)
As shown in the above image, only the add method implemented in PlusOne.java is invoked so both num1 and num2 are 2. 

Expected Behavior: The operations should be invoked according to the interface names. That is, Yakindu should match between interface names and Java class names.

Thanks.

**Comment by andreasmuelder** [comment]
Thanks for reporting!
