### ISSUE TITLE
Full product does not show "Welcome" page

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#210]
The full product as of 2015-11-25T17:25 (Linux 64 bit) does not show the usual "Welcome" page containing an overview of the available help topics.

The _Help → Welcome_ entry in the main menu is also missing:
![screenshot](https://cloud.githubusercontent.com/assets/1495781/11472808/482c98dc-976f-11e5-97c8-6e3286b72243.png)

**Comment by andreasmuelder** [comment]
Fixed
