### ISSUE TITLE
Create .gitignore generator

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#2109]
Normally, users would not want to commit generated statechart code into git, so having a .gitignore generator would be nice.

* In all folders in which sources are generated, the `.gitignore` should be **modified**
* All files generated by SCT should be added to these `.gitignore` files
* The `.gitignore` files need to be checked if the file is already mentioned, if not, a line must be appended (no overwriting)
* There must be a mechanism to ask the relevant source generator which files it would generate and where, so linking to another sgen would be needed
  * This would be very handy as well to introduce an *SCT clean* feature which would delete all files generated by us

Lines added by the generator to the `.gitignore` could be contained in a block like this: 
```
...other entries made by the user
// <SCT generated entries>
Statechart.c
Statechart.h
StatechartRequired.h
// <END SCT generated entries>
```
This would be pretty easy to parse and to modify, and is still easy to understand.

**Comment by terfloth** [comment]
increases complexity of product without need. User can manually configure dedicated folders for content that should not be checked into git.
