### ISSUE TITLE
Full version is missing an encapsulating directory

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#211]
Unpacking the full version does _not_ create the usual _eclipse_ directory containing the actual contents, but everything is dumped into the current directory instead.

The encapsulating directory should be (re-)introduced with a proper name, e.g. _eclipse_, _sct_, or whatever – perhaps even something with a version number.

**Comment by andreasmuelder** [comment]
Added root folder 'sct' to zip
