### ISSUE TITLE
Introduce information on number of states to generated C/C++ code

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#2128]
Currently it is not possible to determine the number of states of a generated state machine. This should be introduced for the generated C and C++ code.

**Comment by BeckmaR** [comment]
The simplest solution would be to add one more member to the enum, its value would automatically be the number of states.

**Comment by andreasmuelder** [comment]
We should add a #define <FQN>_STATE_COUNT XX to avoid clashes with enumeration literals.
