### ISSUE TITLE
Transition text is cropped

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#2159]
I have a transition with text: `eInt [valueof(eInt)==42]`
But on my screen I see:
<img width="331" alt="bildschirmfoto 2018-07-26 um 14 29 12" src="https://user-images.githubusercontent.com/2589669/43262458-798a69d2-90e0-11e8-85d4-34be2ad80684.png">

Tested on macOS.

**Comment by andreasmuelder** [comment]
seems to be an OS specific problem, works on Windows

**Comment by rherrmannr** [comment]
Can reproduce this on linux.
And I remember that I got the same problem on windows.
