### ISSUE TITLE
Model drawing issues

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#216]
The graphical model representation has a couple of issues, exemplified in the attached PNG file with red indicator numbers: 
- Transition does not properly vertically align with the initial state (1).
- There's a gap between the initial state and the transition (2).
- The arrow should end at the outer edge of the state's border line or alternatively end in the middle of the border line. In any case, it should not extend into the state's box (3).
- The state box's blue color gradient extends too far to the right and appears outside the box (4).
- Lines should either be rounded, mitered or skewed at the corners. In other words, corners should look nice (5).
- Box shadows should be smooth (6).
- State names are not centered, extend too far to the right and are clipped (7).  

![coffeemachine_01_problems](https://cloud.githubusercontent.com/assets/1495781/11531509/aa377864-98fd-11e5-8648-0ff3bc4a018f.png)

**Comment by andreasmuelder** [comment]
@tangele can you have a look which of these issues are already fixed in the current version?

**Comment by tangele** [comment]
still TODO:

* Transition does not properly vertically align with the initial state (1). 
* Box shadows should be smooth (6).

everything else is fixed in current [master ](https://github.com/Yakindu/statecharts/commit/f607ce8f13806032adf60c99a488758e449668d6)

**Comment by BeckmaR** [comment]
We shouldn't fix the shadows, me thinks...

**Comment by andreasmuelder** [comment]
Fixed in current master
