### ISSUE TITLE
Fix position of priorites

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2162]
The "number" of the priority moves if the transition is moved

**Comment by BeckmaR** [comment]
Agree, the positioning should not depend on the transition's length, else this happens:
![image](https://user-images.githubusercontent.com/15799654/43453252-ee7f6bf2-94b9-11e8-8a44-c623106663ee.png)

**Comment by andreasmuelder** [comment]
We could use fixed source decorators instead:

![decorators](https://user-images.githubusercontent.com/6338708/45963227-fcf2ed00-c022-11e8-97f7-92c35a8f260e.PNG)

**Comment by rherrmannr** [comment]
The circle could be a little bit bigger so that the numbers fit in.

**Comment by tkutz** [comment]
The new decorators are not removed when a transition is deleted.
