### ISSUE TITLE
Two different mouse cursor are confusing at transitions

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2163]
The mouse cursor changes, if the mouse is exactly over the middle of a transition.

**Comment by tkutz** [comment]
The different cursor indicates that you can select the transition now and specify a trigger. The cursor also changes when you hover a bend-point because in that position you can drag the bend-point to change transition routing.

**Comment by BeckmaR** [comment]
I would agree, that's intentional. If there isn't anything completely going wrong on Windows, this one can be closed...

**Comment by rherrmannr** [comment]
A different mouse cursor only appears in a very small area.

The mouse cursor changes in the red area, but got the same functionallity. 

![unbenannt](https://user-images.githubusercontent.com/25480651/43509865-27515f8e-9574-11e8-9d97-4ef7b874340c.png)

**Comment by BeckmaR** [comment]
I can confirm that this issue does **not** exist on Linux

**Comment by tkutz** [comment]
Also *not* reproducible on macOS.

**Comment by andreasmuelder** [comment]
external bug in GMF, we can't fix this here
