### ISSUE TITLE
MaxIdentifierLength deprecation message gives no alternative

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#2184]
The warning does not really help as it does not say what else to choose.

* Add hint for CShortIdentifier annotation (as already done in documentation)
* Remove "null" from message
* Remove the option from example in hover documentation
* Attach the warning to the parameter itself
* Add this warning also to CPP generator? @BeckmaR that is missing right?

![bildschirmfoto 2018-08-15 um 13 23 33](https://user-images.githubusercontent.com/2589669/44146123-825b1fda-a08e-11e8-9324-91de96d02c2f.png)

**Comment by andreasmuelder** [comment]
Partly fixes in https://github.com/Yakindu/statecharts/pull/2210

done: 
 * remove null
 * attach the warning to the parameter itself
