### ISSUE TITLE
Rename refactoring broken when definition section contains error

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#2185]
When definition section has an error, trying to rename an element from within this section does rename all references in the model but not the declaration itself.

Happens with both, pinned and unpinned definition section.

**Comment by tangele** [comment]
as discussed with @andreasmuelder, simply greying out the option to rename might not the best solution, because the reason for outgreying (=invalid definition section) might not be clear. The erroneous part might not be visible.

=> needs decision/discussion 

cc @tkutz

**Comment by tangele** [comment]
according to @andreasmuelder, making the renaming more reliable when the definition section is errorneous is not worth the effort. 

==> Closed.
