### ISSUE TITLE
Statechart is dirty and can't be saved

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2236]
Not sure how to reproduce this.

Statechart is dirty, save does not work or seems not to have an effect. Restart of IDE has no effect.

**Comment by andreasmuelder** [comment]
Please reopen with steps to reproduce

**Comment by svenjawendler** [comment]
![savingproblemswithcproject](https://user-images.githubusercontent.com/22005752/45481855-e6a87f80-b74c-11e8-9b17-a96c2d0ac1c6.png)

How to reproduce:
Create a new C Project
Create a new C Statechart
Clear the DefinitionSection
- Paste the following: internal:
 event press:  
  var x: bool=false 
Add a second Statechart and transition to it with press / x=true

Errors occur, save the model, clean project, restart IDE -> no effect, problems stay

**Comment by BeckmaR** [comment]
@svenjawendler this did not reproduce the issue for me. Also, your definition section just contains errors, the line `event press:` ends with a superfluos colon.
