### ISSUE TITLE
Time Triggers are not canceled properly

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#2242]
![unbenannt](https://user-images.githubusercontent.com/6338708/45365848-b9898f00-b5dd-11e8-8932-b055ad210e8b.png)

Steps to reproduce:
 - periodically raise event e with ~ 1 second delay, StateB should never be entered.

This applies to CycleBased as well as EventDriven semantics.

**Comment by tkutz** [comment]
Fixed with https://github.com/Yakindu/statecharts/pull/2246
