### ISSUE TITLE
definition section warning does not disappear

### ISSUE THREAD

**Issue by tangele** [Yakindu/statecharts#2251]
1. create new general project
2. create a new statechart model using default domain
3. create internal variable `test` from type integer
```
internal:
var test : integer
```
4. save
5. warning in the definition section pops up, `internal delcaration is not used in statechart`
6. save
7. warning in the problem view pops up,  `internal delcaration is not used in statechart`
8. entry/test = 0 in stateA.
9. expectation: warning in definition section is vanished. (it had popped up without saving. Therefore, it should also disappear without saving). observation: warning in definition section remains visible.
10. save
11. warning in problems view is vanished, warning in definition section still remains

**Comment by rherrmannr** [comment]
Can reproduce this with pinned definition section.

The warning dissapears in the problems view. The pinned defenition section needs to be touched and saved.
