### ISSUE TITLE
additional entry states sometimes cannot be deleted; redo/undo behavior sometimes doesn't work.

### ISSUE THREAD

**Issue by tangele** [Yakindu/statecharts#2253]
all these issues are not deterministically reproducible:

* adding additional entry states and trying to delete them via the `delete` key doesn't work. When that happens, the undo/redo behavior also doesn't work
* sometimes the added entry state even cannot be deleted via rightclick -> delete from model.

Version used: https://sctbuilds.itemis.de/job/SCT_REPOSITORY/266/

**Comment by andreasmuelder** [comment]
@tangele please provide steps to reproduce

**Comment by tangele** [comment]
cannot reproduce in current master.

**Comment by dylon** [comment]
I encountered this bug but could not tell you the steps required to reproduce it.  I restarted Eclipse and it resolved itself.
