### ISSUE TITLE
Define behaviour for multiple entry points

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2273]
We don't have described the behaviour for multiple entries.
Are they allowed? How should they be executed? 

![bildschirmfoto vom 2018-09-20 11-04-40](https://user-images.githubusercontent.com/25480651/45818779-03136180-bce3-11e8-9e35-2b7ff681d848.png)

**Comment by andreasmuelder** [comment]
as discussed, multiple entry points are not allowed.
