### ISSUE TITLE
Test SCT with latest Java version

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2358]
We should test the current release with Java 10 and 11.
We should also extend the matrix build to use the latest Java version.

**Comment by rherrmannr** [comment]
I'm not 100% sure, but I think I got it running with Java 11.

Java 10 and 9 is not supported on ubuntu 18

https://wiki.ubuntuusers.de/Java/Installation/OpenJDK/

**Comment by rherrmannr** [comment]
@andreasmuelder 
any further steps? build a product with java 9/10/11 for testing?

**Comment by rherrmannr** [comment]
Not working with Java 11. Tested by @tangele

**Comment by andreasmuelder** [comment]
see https://github.com/Yakindu/statecharts/issues/2542
