### ISSUE TITLE
state content is not completely visible

### ISSUE THREAD

**Issue by tangele** [Yakindu/statecharts#2362]
follow https://github.com/Yakindu/statecharts/blob/master/manual-tests/org.yakindu.sct.test.manual/testcases/sct_testcase_02_editor.textile until  2.8.

![1](https://user-images.githubusercontent.com/37842129/47160582-8c24b500-d2f0-11e8-8145-4ef58c2eaa16.PNG)

double clicking the state content yields

![2](https://user-images.githubusercontent.com/37842129/47160585-8e870f00-d2f0-11e8-812d-1da0409c1f06.PNG)

which is annoying. The content is not completely visible.

**Comment by rherrmannr** [comment]
This has been fixed in v4
