### ISSUE TITLE
Print transition fatter when TransitionSpec is in focus

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#2401]
When the transition spec text field is selected or edited right now, the related transition should be printed differently, e.g. with a different line width or a different color. This simplifies editing.

See image below for example - which transition does `[check("AAA")]` belong to?
![image](https://user-images.githubusercontent.com/15799654/48124303-436f7480-e27c-11e8-9ad7-85485ed8b6f7.png)

**Comment by andreasmuelder** [comment]
This is a duplicate to https://github.com/Yakindu/statecharts/issues/48

However, just making the transition fatter when selected does not help to assign it when printed out
