### ISSUE TITLE
Add support for external event queues for event driven C++ code generator 

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#2444]
The C++ code generator currently does not support external event queues. Add this feature to the code generator according to the following requirements:

- [x] The statechart class will contain an additional queue. Use std::deque for the implementation.
- [x] The implementation should follow the same implementation pattern like the internal event queue.
- [x] The raise methods queue the events instead of directly invoking the runCycle.
- [x] A run loop method is required that processes the events on the event queue.
- [x] The behavior of internal events and the internal queue won't change. Internal event processing will remain as inner loop.  

Open points:
- [x]  Define if event raising automaticall should trigger the run loop or if that should be called separately.
- [ ] Define handling for out events. In this scenario we should consider to switch to a push instead of poll style interface for out events. Options would be introducing event handlers, observables, out queues.

**Comment by BeckmaR** [comment]
How do we handle out events? Say I queue `e1`, `e2`, `e3`, and run the loop. During the runs, the out events `o1`, `o2` and `o3` are raised, respectively. Will they be queued as well? Just leaving them as active might lead to wrong behavior if they are used in a condition.

How are internal events merged with this? Do we loop through in-events in the outer loop, and through internal events in an inner loop?

**Comment by terfloth** [comment]
First step is implementing a derived C++ code generator that add the event queue for in events to the state machine. In a second step this feature must be merged with the original C++ code generator.

**Comment by BeckmaR** [comment]
Closed via #2577
