### ISSUE TITLE
user visible error message after renaming statechart name & its filename

### ISSUE THREAD

**Issue by tangele** [Yakindu/statecharts#2472]
* create a new statechart model, using the default domain
* rename the statechart name
* rename the statechart file name in the project explorer with right-click -> rename.

=> user visible error occours:

```
'Updating encoding settings.' has encountered a problem. 

Problems encoutered while updating encoding settings.

Problems encountered while updating encoding settings.
Could not save encoding settings.
Exception occurred while saving project preferences: /org.itemis.webShop/.settings/org.eclipse.core.resources.prefs.
```

**Comment by rherrmannr** [comment]
Tried this three times. Cannot reproduce.

Reopen with more detailed steps to reproduce.
