### ISSUE TITLE
Improve moving transitions

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2500]
The behaviour while moving transitions is annoying. Transitions are always settled in the middle of the state. 

This is shown in the picture, where I have moved a transition from the right side of the state to the upper side. In my opinion, the transition should be placed in the right corner of the upper side.

![movingtransitions](https://user-images.githubusercontent.com/25480651/49524478-1d091d00-f8ac-11e8-978a-c14cfe2e0f7f.png)

**Comment by BeckmaR** [comment]
In my opinion, there should be "anchors" to which transitions can connect (and nowhere else). There should be one in the middle and one in every corner, and with increasing state size there should be more anchors.

**Comment by andreasmuelder** [comment]
handled with new router/layouter
