### ISSUE TITLE
Syntax highlighting in YAKINDU SCT not correct

### ISSUE THREAD

**Issue by WolfgangHa** [Yakindu/statecharts#2520]
In a transition condition the syntax highlighting is wrong if an expression appears commented and uncommented.

Transition not in edit mode:
![diagramnotineditmode](https://user-images.githubusercontent.com/22558514/49856499-39e3aa00-fdf0-11e8-9d2a-5714382f0980.png)
Transition in edit mode:
![diagramineditmode](https://user-images.githubusercontent.com/22558514/49856500-3a7c4080-fdf0-11e8-85f3-d03f25ecf5d9.png)

OBSERVED: If transition is not in edit mode, the expression "a >= 1" appears in colour for commented code.
EXPECTED: The expression "a >= 1" should NOT appear in colour for commented code.

**Comment by WolfgangHa** [comment]
We assume that the bug was introduced with: 
https://github.com/Yakindu/statecharts/pull/1709

**Comment by andreasmuelder** [comment]
It seems like the lineOffset in SyntaxColoringLabel#paintText is calculated wrong when the same text appears multiple times in different lines sind indexOf returns the first occurence:

`int lineOffset = getText().indexOf(originalDraw);`
