### ISSUE TITLE
Simulation drops user event inputs 

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#255]
When a user raises an event in the simulation view with a high frequency only the first input is used. Repeating event raising requires ca. half a second in order to work properly.

Reproduce by:
- open and run the digital_watch/Watch.sct example
- try to set the time by
   - button.set
   - button.set (now you can set hours)
   - raise button.onoff - and play with click frequency....

**Comment by andreasmuelder** [comment]
Seems to be an issue with the JFace TreeViewer SelectionChangedListener. If you move the mouse slightly while clicking it works as expected.

**Comment by andreasmuelder** [comment]
Fixed with 3da3401
