### ISSUE TITLE
Exception during simulation when clicking on slot for an event with payload

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#2553]
Clicking on UserEvent slot while it has no value gives an exception:

<img width="844" alt="bildschirmfoto 2018-12-21 um 16 43 39" src="https://user-images.githubusercontent.com/2589669/50350520-b76d8f80-053f-11e9-99af-8f3ee05ed958.png">

**Comment by andreasmuelder** [comment]
won't fix as discussed with @tkutz working as expected
