### ISSUE TITLE
Content Assist shows types where it shouldn't

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#2605]
![image](https://user-images.githubusercontent.com/15799654/51249406-75dfd100-1993-11e9-8c77-4c5b83d73906.png)

Same happens in front of a transition reaction

**Comment by andreasmuelder** [comment]
The problem here is that there can be (complex) types that contain events (or meta-features) that can be used as triggers. So we won't fix for now.

**Comment by tkutz** [comment]
This is a regression (I think with version 3.5.0). We have test cases where we do not expect primitive types in the content assist, and these tests worked, but now they don't.

**Comment by BeckmaR** [comment]
Such a nice surprise in my inbox!
