### ISSUE TITLE
Feature names and descriptions are inconsistent

### ISSUE THREAD

**Issue by nyssen** [Yakindu/statecharts#261]
The feature names, descriptions, and providers of the SCT features are inconsistent and should be adopted as follows:

* org.yakindu.base.feature.group
** name: "YAKINDU Base Feature" -> "YAKINDU Statechart Tools (SCT) Base"
** description: "Basic YAKINDU Statechart Tools 2." -> adopt to some rich description of the offered functionality.
** provider: "statecharts.org"

* org.yakindu.sct.feature.group
** name: "YAKINDU Feature" -> "YAKINDU Statechart Tools (SCT)"
** description: "Basic YAKINDU Statechart Tools 2." -> adopt to some rich description of the offered functionality.
** provider: "statecharts.org"

* org.yakindu.sct.sdk.feature.group:
** name: "YAKINDU 2 SDK" -> "YAKINDU Statechart Tools (SCT) SDK"
** description: "Generators for YAKINDU Statechart Tools 2." -> adopt to something that explains what is contained.
** provider: "yakindu.org" -> "statecharts.org"

* org.yakindu.sct.generator.c.feature.group
** name: "YAKINDU C Generator Feature" -> "YAKINDU Statechart Tools (SCT) C code generator"
** description: "Generator for C/C++ of the YAKINDU Statechart Tools 2." -> adopt to something that explains in detail what the scope of the generator is.
** provider: "yakindu.org" -> "statecharts.org"

* org.yakindu.sct.generator.cpp.feature.group
** name: "YAKINDU C++ Generator Feature" -> "YAKINDU Statechart Tools (SCT) C++ code generator"
** description: "Generator for C++ of the YAKINDU Statechart Tools 2." -> adopt to something that explains in detail what the scope of the generator is
** provider: "statecharts.org"

* org.yakindu.sct.generator.java.feature.group
** name: "YAKINDU Java Generator Feature" -> "YAKINDU Statechart Tools (SCT) Java code generator"
** description: "Generator for Java of the YAKINDU Statechart Tools 2." -> adopt to something that explains in detail what the scope of the generator is
** provider: "statecharts.org"

The source features corresponding to the generators provide inconsistent names, descriptions, and providers as well and should be adjusted accordingly. If they are contained in the SDK, it should be investigated whether these need to be provided as standalone features at all.

**Comment by andreasmuelder** [comment]
## Descriptions
* org.yakindu.base.feature.group: The YAKINDU Base feature provides extensions to existing frameworks (GMF, Xtext) as well as a generic expression language that may be used outside of the SCT context. This feature is required when installing YAKINDU Statechart Tools.
* org.yakindu.sct.feature.group : The YAKINDU SCT feature contains the graphical statechart editor, the simulation engine and the code generation infrastructure to plug in different code generators.
* org.yakindu.sct.sdk.feature.group: The YAKINDU SCT feature contains the graphical statechart editor, the simulation engine and the code generation infrastructure to plug in different code generators. The SDK bundle also contains the source code.
* org.yakindu.sct.generator.c.feature.group: The YAKINDU C Code generator feature contains the default switch / case based code generator for the C programming language. 
* org.yakindu.sct.generator.cpp.feature.group: The YAKINDU C++ Code generator feature contains the default switch / case based code generator for the C++ programming language. 
* org.yakindu.sct.generator.java.feature.group: The YAKINDU Java Code generator feature contains the default switch / case based code generator for the Java programming language.
