### ISSUE TITLE
JavaGen: Inner Interface implementation classes should be static

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#2629]
This needs further work in all cases where the inner interface implementations call the outer statemachine, e.g. in the event driven case where `runCycle` is called.

**Comment by tkutz** [comment]
I think the rule of thumb is: If the inner class does NOT require access to the outer class, make it static (to save the implicit reference and allow usage independent of the outer class).
But in our case, the event raising methods need to call runCycle, so the inner classes require access to the outer class. Furthermore, a statechart interface class is nothing you want to use on its own, it represents a part of the outer staatechart class and should not live without it (if the statechart dies, the inner classes should also die).

All in all, I think having non-static inner classes for the statechart's interfaces is just fine.
