### ISSUE TITLE
Code generators should all report what features they support

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#2639]
For example, if a code generator does not support event driven yet, we should produce a warning in the genmodel. Also, this makes it harder to forget a code generator when implementing a new feature.

This could look like this:
```
ICodeGenerator {
    public void supportsEventDriven();
    public void supportsChildFirstExecution();
}
```

**Comment by andreasmuelder** [comment]
obsolete since all generators support all available features now
