### ISSUE TITLE
Transitions with multiple exit point connections are not handled correctly

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#2690]
For some reason, if a transition specifies multiple handled exit points like `# e1> e2>`, only the first one works correctly, whereas the other one breaks the statechart. See example:

![image](https://user-images.githubusercontent.com/15799654/53534107-cfdcc600-3afd-11e9-89fb-53899f2ab8b0.png)

When simulating this, either event `e1` or `e2` should have the same effect - **StateA** is left, `x` is set to 1, **1** is active. This only works for `e1`. `e2` deactivates **StateA**, does not activate **1**, and does not set `x` to 1.

This can also be observed in the generated code (everything inlined):

```

/* The reactions of exit e1. */
static void react_main_region_StateA__region0_e1(Default3* handle)
{
	/* The reactions of exit e1. */
	/* Default exit sequence for state StateA */
	/* Default exit sequence for region  */
	/* Handle exit of all possible states (of default3.main_region.StateA._region0) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Default3_main_region_StateA__region0_State1 :
		{
			/* Default exit sequence for state State1 */
			handle->stateConfVector[0] = Default3_last_state;
			handle->stateConfVectorPosition = 0;
			break;
		}
		default: break;
	}
	/* Exit action for state 'StateA'. */
	handle->iface.x = 1;
	/* 'default' enter sequence for state 1 */
	handle->stateConfVector[0] = Default3_main_region__1;
	handle->stateConfVectorPosition = 0;
}

/* The reactions of exit e2. */
static void react_main_region_StateA__region0_e2(Default3* handle)
{
}
```

While exit `e1` properly reacts, exit `e2` does nothing.

OTRS #2019022737000101

**Comment by tkutz** [comment]
Fixed with https://github.com/Yakindu/statecharts/pull/2720
