### ISSUE TITLE
.sct

### ISSUE THREAD

**Issue by XiaoXiaoYi123** [Yakindu/statecharts#2708]
Hello, I am very interested in this tool.

I've been working on the.sct file and I've learned that it's an xmi file and I'd like to know how this.sct file is generated.

I see that the.sct file has two pieces of information, one about the state of the state diagram and the migration between states, and the other about the UI information for each node. In addition, I saw the sgraph.ecore and stext.ecore files in the source code, and I found that sgraph.ecore is the structure part of the description of the state diagram, and stext.ecore is the behavior information of the description of the state diagram.

I have the following questions:

1. Are the states in the. SCT file and the migration information between them generated by the sgraph.ecore and stext.ecore files?

2. If 1 is true, how to generate UI information of each node? Through the GEF framework?

3. If I want to generate a. SCT file from excel, I need to create an excel ecore model. In addition, regarding the UI information of nodes, could you give a fixed value first, then open it with yakindu, and then modify the corresponding information?

My question is a little bit doha, I really need your help, if you can reply to me, I will be very grateful. Looking forward to your reply.

If I say something wrong, I hope you can point it out. 

I wish good

**Comment by BeckmaR** [comment]
Closing, this is not an issue.

A valid issue is, for example:
* a bug report
* problems with the documentation
* reporting missing features
* reporting unexpected behavior
