### ISSUE TITLE
Variables from operations are not accessible in C++ generated code.

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#271]
If I code the following:

internal:
    var muted :  boolean
    operation Mute()

The muted variable is not accessible from the Mute() method. This is true for internal scope and from any interface scope when using C++ generated code.

**Comment by andreasmuelder** [comment]
afaik this is by design - it is not allowed to read or write internal variables outside of the statemachine.
if the variable is contained in an interface it should be possible to access the variable via a getter.

**Comment by stmork** [comment]
Am 27.12.2015 um 11:33 schrieb Andreas Mülder:
> afaik this is by design - it is not allowed to read or write internal
> variables outside of the statemachine.
> if the variable is contained in an interface it should be possible to
> access the variable via a getter.
It makes sense for internal operations to access internal variables. I
don't want to access the variables from outside. Even from an external
visable interface it was not possible to access the variables out of the
operations from the same scope.

I used the workaround to set the innerFunctionVisibility = "protected"
generator property.
