### ISSUE TITLE
No C++ Example available in documentation as opposed mentioned there.

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#272]
While reading http://statecharts.org/documentation.html#SpecCpp there is a C++ example application using Qt mentioned but inside the repository there is only a Qt application using a C statemachine.

**Comment by RainerKlute** [comment]
At the moment we are considering the examples anyay. Stay tuned!

**Comment by RainerKlute** [comment]
The C++ example is available now in https://github.com/Yakindu/examples/tree/master/traffic_light_waiting_cpp. The documentation has been fixed.
