### ISSUE TITLE
Always trigger is declared implicit when guard is used

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2728]
The behavoir of not using always triggers is not consistent.
Always trigger will be used implicit, if guards are used.

In my opinion, there should be a warning caused by the missing trigger. StateC should not be entered.

I'm not sure if we should change this, because this would have an impact on the execution behavior of the simulation and the generated code.

![missingTrigger](https://user-images.githubusercontent.com/25480651/55156103-59ad9c80-5159-11e9-8561-1ae3f5a650b5.png)

**Comment by BeckmaR** [comment]
StateC is just taken here because transitions without trigger are never taken, so transition 2 is taken instead - as the warning says. I don't get the issue...

**Comment by andreasmuelder** [comment]
As the topic says, when a guard is defined an implicit always trigger is added. This is the desired behaviour.
