### ISSUE TITLE
No documentation about headless build available

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#273]
I would prefer to build the statemachines artifacts with Maven headlessly. Is there any example of a pom.xml out there?

**Comment by andreasmuelder** [comment]
Wouls be very useful, but it requires some refactoring to remove dependencies to the eclipse file system to allow headless execution.
Duplicate of #162

**Comment by stmork** [comment]
Am 27.12.2015 um 11:27 schrieb Andreas Mülder:
> Wouls be very useful, but it requires some refactoring to remove
> dependencies to the eclipse file system to allow headless execution.
> Duplicate of #162 <https://github.com/Yakindu/statecharts/issues/162>
Is there no pom.xml or something like this outside? This forces me to
check in the generated artefacts into version control which is not best
practice.

**Comment by andreasmuelder** [comment]
This is not yet implemented but contributions are always welcome :)

**Comment by stmork** [comment]
Am 27.12.2015 um 13:01 schrieb Andreas Mülder:
> This is not yet implemented but contributions are always welcome :)
My job is to implement a statemachine for an embedded system. May be
that I would contribute something to SCT in future but my job is not to
fix your bugs and do your work.

Have a happy new year 2016

**Comment by stmork** [comment]
I've tried the example @jdicks posted on your website (https://blogs.itemis.com/en/how-to-standalone-generate-statechart-code-for-continuous-integration-builds). Unfortunately it does not work with the C++ generator. The reason is that the package of the CPPDefaultFeatureValueProvider is not reexported in the manifest file.

Btw. Is it possible to define the feature libraries using platform URIs like platform:/plugin/...? This seems to be better than copying/extracting the XMIs from the git repository.
