### ISSUE TITLE
Cleanup generator model for version 4

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#2730]
We have lots of different generator options. When moving towards a version 4 where we do not need to be backwards compatible, we should cleanup the generator model.

So this issue is for collecting ideas/todos.

Here are some starting points:
* remove deprecated `maxIdentifierLength`
* remove deprecated `SynchronizedWrapper` and `RunnableWrapper` feature
* harmonize naming between different target languages (`GeneratorOptions` in C/C++ vs `GeneralFeatures` in Java)

**Comment by BeckmaR** [comment]
We should think about whether we want to keep any code-related functional features in the genmodel or if this should be solved via annotations in the statechart. This would decouple the genmodel from the statechart and turn it into a simple output configuration. This fits our new generator architecture better.
