### ISSUE TITLE
Restart button is missing in simulation

### ISSUE THREAD

**Issue by glykerak** [Yakindu/statecharts#2733]
When a simulation is terminated, no other action can be made. 
Place a “Restart” button next to “Resume”, which will start the same simulation from the beginning.

**Comment by tkutz** [comment]
This is already fixed in 3.5.3 ;)
See release notes here: https://www.itemis.com/en/yakindu/state-machine/documentation/user-guide/release_notes_3.5.3#release_notes_3.5.3
