### ISSUE TITLE
Update site label on marketplace shows old version

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#2736]
Seems like there is still the 3.3.0 version on Eclipse marketplace.

At least that is what the installation wizard tells you. However, on further stepping through, the current version (3.5.3) will be installed:

<img width="535" alt="Bildschirmfoto 2019-04-03 um 16 09 59" src="https://user-images.githubusercontent.com/2589669/55485545-f3c68680-562a-11e9-94d0-ab1c1e40cc4f.png">

**Comment by andreasmuelder** [comment]
<img width="411" alt="3 5 10" src="https://user-images.githubusercontent.com/6338708/76738672-5e54d180-676b-11ea-8a29-b35e5305fbe1.PNG">
