### ISSUE TITLE
Read-only modus: Elements should not be displayed as editable.

### ISSUE THREAD

**Issue by glykerak** [Yakindu/statecharts#2739]
When the user is on read-only modus and double-clicks e.g. a state name, the name is selected and it is displayed as if it is editable. 
With double-clicking, the name should be selected but only as a plain text and the text area border should not be visible.
![readonly_edit](https://user-images.githubusercontent.com/47387684/55947889-a6ac6b00-5c4f-11e9-869f-d57f059d5b5a.PNG)

Similarly, when a state is selected, small edges are displayed on the border which give the feeling that it can be dragged. On click, the border should be showed, but not the edges.
![vergrößern](https://user-images.githubusercontent.com/47387684/55947954-ccd20b00-5c4f-11e9-8fde-2766863dd946.PNG)

**Comment by andreasmuelder** [comment]
won't fix, the model cant be edited anyway
