### ISSUE TITLE
Error message is weak for "exit is not connected to any outgoing transitions"

### ISSUE THREAD

**Issue by DefCon-CC** [Yakindu/statecharts#2742]
In Yakindu SCT 3.4.1 we got the following error message when generating the state machine

```
Generating 'Example' to target project 'Appl' ...
The referenced model (Example) contains errors and could not be generated:
This exit is not connected to any outgoing transitions.
Example done.
```

But for large state machines (with many sub-diagramms) it is very unprecise where the error "This exit is not connected to any outgoing transitions." occured. A remark in which region, sub-diagram, ... the error occured would be helpful!

**Comment by andreasmuelder** [comment]
If the model is faulty, you should get a problem marker in the Problems View. You can jump to the location with a double click. Is this not sufficient?

**Comment by DefCon-CC** [comment]
> If the model is faulty, you should get a problem marker in the Problems View. 

I do not see any problem marker in the Problems View. I see also in the model no error

**Comment by andreasmuelder** [comment]
It should look like this.
![exit](https://user-images.githubusercontent.com/6338708/57225955-0e1ac800-700e-11e9-9d9f-7e5afd798479.PNG)

Maybe "Build automatically" is disabled in your workspace? Do you see an error marker after project / build?

**Comment by DefCon-CC** [comment]
Ahh, the problem was introduced by second *.sct file in the same folder with the same StaeChart Name I keept as backup. Ticket can be closed!
