### ISSUE TITLE
Website "Download product" is confusing

### ISSUE THREAD

**Issue by glykerak** [Yakindu/statecharts#2750]
The site for downloading the product looks overloaded and confusing. The user doesn’t know which versions for downloading he has selected. The naming of the buttons don't match the actual versions.

**Comment by glykerak** [comment]
![editions](https://user-images.githubusercontent.com/47387684/57435183-faa17400-723c-11e9-99c8-c45132988ee5.PNG)
![professionaledition](https://user-images.githubusercontent.com/47387684/57435190-fe34fb00-723c-11e9-97b4-2b355b48f383.PNG)

**Comment by andreasmuelder** [comment]
should be discussed in pro repository
