### ISSUE TITLE
Missing print preview/JPEG save

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#277]
For documentation purposes we have to print or save the statechart into file. I found no possibility how to do that.

**Comment by andreasmuelder** [comment]
You can right click on the canvas and select Save as Image File

**Comment by stmork** [comment]
No, I'm not able to save. I've attached a screen shot.
![statechart-jpeg-error](https://cloud.githubusercontent.com/assets/975841/12079027/0754f5cc-b22a-11e5-8c30-ca7f120cdd3a.gif)

**Comment by andreasmuelder** [comment]
I can't reproduce this on Windows 64 bit with JDK 8.
Which OS and JDK do you use? Does it work for BMP, PNG etc?

**Comment by stmork** [comment]
Ubuntu 14.04.3 LTS and OpenJDK7. I need only JPEG. So please test yourself.

**Comment by RainerKlute** [comment]
This functionality depends on the Java Runtime Environment: I was able to reproduce this bug on Linux (64bit) with OpenJDK; however, everything works fine with Oracle JDK.
Please change your JDK or export as PNG and convert to JPEG externally.
