### ISSUE TITLE
SCTUnit assert operation call not working as documented

### ISSUE THREAD

**Issue by tuttoaldoc** [Yakindu/statecharts#2774]
Hello,
I'm testing a state machine using operation call assertion and I noticed that if I do

assert called sStopPwm [x] times

it returns me true whenever sStopPwm operation is called a numbert of time >= [x] instead from your documentation it should assert an ==.
"The third assertion checks whether the operation myOperation has been called exactly 4 times"
best regards
Michele

**Comment by tkutz** [comment]
Hi @tuttoaldoc ,
we decided to update the documentation on that issue to not break existing tests. So the semantics is `at least X times`.
