### ISSUE TITLE
No action executed on outgoing transitions from an initial state

### ISSUE THREAD

**Issue by egrolleau** [Yakindu/statecharts#278]
Simple setup to expose the bug: create a new statechart.

In the declarative part, write:
internal:
var a:integer

Name the state "A". On the transition from the initial state to A, write:
/a=3

Simulate. After simulation, the value of a is 0, while it should be 3.
It seems that Yakindu simulation ignores any action on an outgoing transition from an initial state.

**Comment by DominikTesch** [comment]
added tests for c, cpp, java and interpreter to pull request #281 reassigning @terfloth
