### ISSUE TITLE
Install problems-require your help

### ISSUE THREAD

**Issue by XiaoXiaoYi123** [Yakindu/statecharts#2799]
hello, when i installed  Yakiindu from source code, there existed no problems, but when  I run Yakindu from source code, it showed "Installation is currupt . License is missing. - editor is in readonly mode"
![image](https://user-images.githubusercontent.com/45426458/64310117-7d5ef380-cfd1-11e9-937e-6ac54637ac9f.png)

**Comment by tkutz** [comment]
This is actually changed on purpose in version 3.5.6 to avoid usage of Yakindu without having a valid license. If you want to work on the code for your private project you can always switch to the 3.5.5 tag.

**Comment by XiaoXiaoYi123** [comment]
There is another small request. I don't know where to get the 3.5.5 version. Thank you very much for your help

**Comment by XiaoXiaoYi123** [comment]
Hello, I installed it according to your installation tutorial. If I want to install version 3.5.5, should I reinstall it or modify the configuration? In addition, where should I find the installation package if I want to reinstall it？

**Comment by tkutz** [comment]
You just need to checkout the corresponding git tag `release_3.5.5`.

**Comment by XiaoXiaoYi123** [comment]
Ok，thanks for your help

**Comment by XiaoXiaoYi123** [comment]
I'm sorry to bother you again. When I have installed the Yakindu release 3.5.5 from source code. The problem has already existed. Does that mean we can't operate on the GUI without a license？I also tried to install Yakindu from eclipse Marketplace, also has a problem same as this  one.

**Comment by tkutz** [comment]
What do you mean with "installed from source code?".

**Comment by XiaoXiaoYi123** [comment]
I followed this instruction to install the Yakindu release 3.5.5:
![image](https://user-images.githubusercontent.com/45426458/64411688-57644c80-d0c0-11e9-99bd-57436fc5ed68.png)
 But I found that the link 
"
![image](https://user-images.githubusercontent.com/45426458/64412076-2c2e2d00-d0c1-11e9-93f5-d77c52182b75.png)
"
is the same as the release 3.5.6.
I guess that this may cause problems when I met in release 3.5.6.(the editor is only read)
I don't know how to install the release 3.5.5, so I really need your help.
Thank you sincerely!

**Comment by tkutz** [comment]
When used `StatechartTools.setup` the installer will download the source code into a local git repository. In this git repository you can switch branches/tags. Default is the current `master`. You would need to switch to the `3.5.5` tag. You can do this in your eclipse or command line or whatever tool you use to manage your git repos.

**Comment by XiaoXiaoYi123** [comment]
I understand what you mean if used 
![image](https://user-images.githubusercontent.com/45426458/64513928-3304ac00-d31c-11e9-9635-ec82f0ec941b.png)
the source code in GitHub will be downloaded locally，like this 
![image](https://user-images.githubusercontent.com/45426458/64514019-69422b80-d31c-11e9-876b-536e6294f940.png)
 and then I can modify the version of Yakindu in this git repository.
You said that I can modify the Yakindu tool version in eclipse. Do I need to replace the files in the git repository with the 3.3.5 version? I am very sorry that I did not understand your meaning clearly. I am looking forward to your reply. Thank you very much

**Comment by andreasmuelder** [comment]
closing as orphaned

**Comment by kubsztal** [comment]
> If you want to work on the code for your private project you can always switch to the 3.5.5 tag.

How this restriction relates to the EPL license which allows to make any modification to the code anyway, thus one can simply revert this change in order to use the software above the version 3.5.5?
