### ISSUE TITLE
Convert documentation to DocBook

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#280]
Subtasks:
* convert source files ✔
* adapt build process (Ant) ✔
* adjust HTML formatting ✔
* adjust PDF rendering ✔
* adapt context-sensitive help ✔
* adapt inclusion of help text snippets ✔
* adapt build process integration (Maven) ✔
* merge into master branch ✔

**Comment by nyssen** [comment]
The currently used wiki-text supports generation of DocBook. Why switch the underlying format?

**Comment by RainerKlute** [comment]
DocBook has a very rich content model which outpaces textile (wiki text) by far. Using DocBook XSL, the documentation source can be converted into a multitude of output formats, including Eclipse Help, HTML, PDF, and EPUB.

Some more goodies:
* Extensible output formatting/generation
* Headline enumeration
* Conditional text
* Index
* Glossary
* …

**Comment by andreasmuelder** [comment]
@RainerKlute Did you close this because it is fixed? Is there a pull request fixing this issue?

**Comment by RainerKlute** [comment]
It's closed, because it's fixed. However, it's in the userdoc_structure_2.0 branch only.

**Comment by andreasmuelder** [comment]
Can you create a PR to merge this into master?

**Comment by RainerKlute** [comment]
I think merging the userdoc_structure_2.0 branch into the master would not be sensible at this time, because that branch comprises the new documentation structure, which is still work in progress. We could consider to transfer select contents of the new documentation to the old textile format, but we might also consider that a waste of time – time that should better be spent on rewriting the documentation to fill the new structure appropriately.

**Comment by RainerKlute** [comment]
Merged into master branch.
