### ISSUE TITLE
Cropped text in SVG image export

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#282]

**Comment by stmork** [comment]
[home.zip](https://github.com/Yakindu/statecharts/files/81053/home.zip) Unfortunately github does not accept SVG updoads directy, so I uploaded a zip file.

**Comment by stmork** [comment]
![home](https://cloud.githubusercontent.com/assets/975841/12169716/d1b56dc0-b53a-11e5-8a06-5049833d7911.png) The same problem with PNG images.

**Comment by andreasmuelder** [comment]
Problem with underlying framework, out of scope for us. 
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=312723

**Comment by stmork** [comment]
At least you should promote fixing the bug!
