### ISSUE TITLE
Java codegen renames "switch" events for EventDriven simulations in Impl but not interface

### ISSUE THREAD

**Issue by vesalvojdani** [Yakindu/statecharts#2850]
The following simple example generates code that does not compile:

```
@EventDriven
interface:
in event switch
operation turnOn()
operation turnOff()
```

The raiseSwitch method is renamed to `raiseSwitch_ID` in SCInterfaceImpl, but not in the SCInterface. This renaming happens only for EventDriven simulations, so if you delete the first line, the generated code compiles without any renaming at all.

**Comment by tkutz** [comment]
Thanks for reporting this, we will have a look!
