### ISSUE TITLE
"Fold outgoing Actions" produces code with error

### ISSUE THREAD

**Issue by Mazesch** [Yakindu/statecharts#2876]
After going through the click test and folding the outgoing actions in part 12.7 a whitespace wasn't created and some text got concated wrong

this might be connected to issue #2610 

**BEFORE:**
![LightOff_fold_outgoingActions](https://user-images.githubusercontent.com/53564458/68850706-d97e7c00-06d4-11ea-93c8-4c8f1ac17fe1.PNG)
**AFTER:**
![LightOff_fold_outgoingActions_error](https://user-images.githubusercontent.com/53564458/68850709-db483f80-06d4-11ea-968a-09e8e78493b1.PNG)

**Comment by tkutz** [comment]
This is a regression coming from https://github.com/Yakindu/statecharts/pull/2583
