### ISSUE TITLE
Migrate to newer googletest verion

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#2903]
We have to update the googletest framework since GCC > 7.1 throws a warning with the current tests:
1.8.1 + 1.10.0 do not compile for C++:

Compilation failed (exit status 1):
/home/travis/build/Yakindu/statecharts/googletest-release-1.8.1/googlemock/build/libgmock_main.a(gmock_main.cc.o): In function `main':
gmock_main.cc:(.text+0x31): undefined reference to `testing::InitGoogleMock(int*, char**)'
collect2: error: ld returned 1 exit status
	at org.yakindu.sct.generator.cpp.test.OperationsTest.setUp(OperationsTest.java:33)

**Comment by rherrmannr** [comment]
There was a bug report: https://github.com/google/googletest/issues/1094
But seems like there is no fix.

**Comment by rherrmannr** [comment]
Actually, we don't use anything from gmock. We can simply remove the include.
