### ISSUE TITLE
Usage of 'always' leads to superfluous code in case condition is also provided (C code generator)

### ISSUE THREAD

**Issue by nyssen** [Yakindu/statecharts#295]
When using 'always' on a transition together with a guard expression, the check function is generated with 'bool_true && ...' in its body, e.g.:
```
static sc_boolean sCT_check_Active_Calltr0_tr0(const SCT\* handle) {
    return ((bool_true) && handle->ifacePhone.duration > 5) ? bool_true : bool_false;
}
```
This is superfluous and could be optimized away to only use the guard expression:
```
static sc_boolean sCT_check_Active_Calltr0_tr0(const SCT\* handle) {
    return (handle->ifacePhone.duration > 5) ? bool_true : bool_false;
}
```

**Comment by andreasmuelder** [comment]
@terfloth I think this is fixed with the current PR you are working on?

**Comment by terfloth** [comment]
This issue still exists.
