### ISSUE TITLE
Transition can specify multiple entry points

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#300]
It is possible to specify multiple entry points in a transition, e.g. "# >failure >success". While it is reasonable to allow for multiple exit points, the number of entry points should not exceed one.

**Comment by andreasmuelder** [comment]
multiple exit points should also be restricted

**Comment by rherrmannr** [comment]
Multiple exit points are working in simulation. Also checked C code generation. There is a sctunit test, which uses exit states (ExitState.sct).

@RainerKlute with ``the number of entry points should not exceed one`` you mean the number of exit points used in the transition, correct?

**Comment by rherrmannr** [comment]
Additionally, code completion does not work any more.

**Comment by rherrmannr** [comment]
I've already implemented a validator for that issue. Meanwhile I have found the example statechart "UnboundEntryPoints02.sct" and modified it. 

Is this behavior correct? 

![bildschirmfoto vom 2018-09-20 11-04-40](https://user-images.githubusercontent.com/25480651/45808001-0697f000-bcc5-11e8-8500-56a68e23041f.png)

**Comment by rherrmannr** [comment]
We need to define the behaviour for multiple entries.
Closed. See https://github.com/Yakindu/statecharts/issues/2273
