### ISSUE TITLE
No proposal for the keyword 'import'

### ISSUE THREAD

**Issue by Mazesch** [Yakindu/statecharts#3007]
In an empty statechart definition section there is no proposal for the keyword `import`, which is used by multi statecharts

**Comment by tkutz** [comment]
Which branch/product? That is something that was actually fixed one or two days ago.

**Comment by Mazesch** [comment]
This was done on the sctpro build for 4.0.0 (#381)

**Comment by tkutz** [comment]
This is already fixed in the current 4.0.0 Beta release
