### ISSUE TITLE
Task Markers are not navigable via double click in task view

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#303]
If a Task Marker is created via //TODO or //FIXME in the textual part, the task marker is not navigable via double click from Eclipse Task View.

**Comment by terfloth** [comment]
desired behavior is specified by [Req.SCT.Editor.TodoAndFixmeTasks](../blob/master/specification/Req.SCT.Editor.TodoAndFixmeTasks.md)

**Comment by andreasmuelder** [comment]
Fixed

**Comment by andreasmuelder** [comment]
fixed with PR #1711
