### ISSUE TITLE
Zooming by mouse wheel is slow

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#304]
Report via Survey: Zooming via mouse wheel is very slow because of the animation.

**Comment by stmork** [comment]
+1 With Linux the zooming with CTRL + mouse wheel is unusable.

**Comment by andreasmuelder** [comment]
Fixed with  1be3df9

**Comment by andreasmuelder** [comment]
@RainerKlute can you test this with Linux ?

**Comment by RainerKlute** [comment]
Zooming on Linux is fast.
