### ISSUE TITLE
Project explorer jumps around selecting sgen/sct files

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#3042]
Project explorer jumps around switching selecting sgen/sct/text files. This is not a Linux bug - saw this on windows, too.
![pejumps](https://user-images.githubusercontent.com/25480651/76615159-c021fb00-6521-11ea-8db1-89f9cb8bff0c.gif)

**Comment by andreasmuelder** [comment]
This is not a bug. The toolbar is filled depending on the editor type. The graphical statechart editor adds a toolbar for fonts/colors etc, this is removed for the xtext sgen editor.
