### ISSUE TITLE
Feature Request: Dynamic time trigger by variable

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#306]
The after and every time trigger take only constant time values. Today we needed a dynamic time ratio for delays which are configurable. It would be nice that these time trigger would take the time from a variable configured in statechart description language.

**Comment by andreasmuelder** [comment]
Closing as invalid since this (i.e. after 3 * x s) is already possible in the current version.

**Comment by stmork** [comment]
You should think about document this feature. Btw.: The code completion does not suggest any variable.

**Comment by andreasmuelder** [comment]
@RainerKlute can you add this to the documentation section?

**Comment by RainerKlute** [comment]
Fixed with pull request #356.
