### ISSUE TITLE
Deadlock using @SuperStep with inEventQueue test

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#3071]
1. open inEventQueue.sct
2. add @SuperStep
3. raise event ``f`` at least once
4. raise event ``e``
-> Deadlock

**Comment by tkutz** [comment]
There is a cycle in the statechart, so the interpreter runs forever:
![Bildschirmfoto 2020-05-13 um 11 48 44](https://user-images.githubusercontent.com/2589669/81797963-bb70c780-950f-11ea-90be-de386fcc798e.png)

Cycle detection is hard as we could also have guard expressions involved, like this one in state L:
![Bildschirmfoto 2020-05-13 um 11 49 46](https://user-images.githubusercontent.com/2589669/81798066-dfcca400-950f-11ea-9084-9031b36af285.png)

But at least we should make the simulation cancelable, and not run in the UI thread directly.
