### ISSUE TITLE
TODO info marker on transition not removed after text was removed

### ISSUE THREAD

**Issue by jfgo20** [Yakindu/statecharts#3090]
In the diagram, the steps to reproduce are.

Create a transition with a TODO comment.
  -> The TODO info marker is shown.

Remove the TODO comment.
  -> The TODO info marker is still shown.

I'm using Yakindu 3.5.11

**Comment by andreasmuelder** [comment]
@jfgo20 I can not reproduce this behavior.  Did you save the diagram after removing the TODO comment? Markers are updated on save.

**Comment by jfgo20** [comment]
I don't think so. It was maybe my problem.
