### ISSUE TITLE
Internally used out events do not work with C observables

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#3095]
Observables and internally used out events do not work together.
Current tests are on blacklist:
- EventDrivenOutEvents
- RaiseEvent

**Comment by terfloth** [comment]
Possible solution: 
* handle comparable to external out events and create shadow event as internal event

**Comment by rherrmannr** [comment]
Tests are running.
Already fixed with https://github.com/Yakindu/statecharts/pull/3111
