### ISSUE TITLE
Oomph!: Use raw link for auto update oomph setup files

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#310]
Don't download the setup file as described here:

Download and start Oomph and the Oomph-Setup file (rightclick, save as...).
On the initial page, click on the Switch to advanced mode button in the top right.
On the Product page, select Eclipse IDE for Eclipse Committers, press Next.
On the Project page, press on the green plus-symbol. Browse File System to select the downloaded Oomph-Setup file.

**Comment by DominikTesch** [comment]
Fixed
