### ISSUE TITLE
Compilation errors for composite states without inner states

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#3134]
The C code generator generates code with [Wunused-function] and [Wunused-value] issues for the following statechart:

![Bildschirmfoto 2020-06-24 um 15 45 46](https://user-images.githubusercontent.com/2589669/85568253-d1ef6000-b631-11ea-97ce-6c4289e9e611.png)

![Bildschirmfoto 2020-06-24 um 15 43 57](https://user-images.githubusercontent.com/2589669/85568275-d582e700-b631-11ea-92f6-debb342925d3.png)

Java code generator produces compilation errors:

![Bildschirmfoto 2020-06-24 um 15 51 59](https://user-images.githubusercontent.com/2589669/85569283-b33d9900-b632-11ea-831f-aebff585d440.png)

**Comment by tkutz** [comment]
Example Models:

[Archiv.zip](https://github.com/Yakindu/statecharts/files/4825739/Archiv.zip)

**Comment by terfloth** [comment]
How does this relate to #3086

**Comment by tkutz** [comment]
It does not relate much to #3086, which is specific to time events on composite states while this one is about the outgoing transition of a composite state.
