### ISSUE TITLE
[true] guard leads to compile errors

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#3149]
Using ``[true]``at transitions without always/else leads to compile errors in C, as the sequencer does not do any optimizations.
Using ``always [true]`` resolves the problem, as the sequencer recognizes an ``AlwaysEvent`` and evaluates the guard expression. 

![image](https://user-images.githubusercontent.com/25480651/86344450-96205000-bc5a-11ea-9e30-f935f491e90b.png)

[AlwaysTrue.zip](https://github.com/Yakindu/statecharts/files/4863362/AlwaysTrue.zip)

Same problem for C++ and Java:
```c
void AlwaysTrue::effect_alwaysTrue__choice_0_tr1()
{
	();
}
```

```java
private void effect_alwaysTrue_A_tr1() {
	exitSequence_alwaysTrue_A();
	();
}
```

**Comment by rherrmannr** [comment]
We need to discuss if we want to do the same optimizations as we do with ``always [true]`` or if we extend the validator.

**Comment by tkutz** [comment]
Might be also related to #3134
