### ISSUE TITLE
Export statecharts as SCXML

### ISSUE THREAD

**Issue by developeron29** [Yakindu/statecharts#315]
Hi there,

Yakindu is such a great tool to create/edit statecharts. Thanks! 

I was working on a project that requires me to display/edit the statecharts that i create using yakindu on a web page. The best way to do that, that i could find was to export the statechart files as SCXML and displaying it using a SCXML javascript statecharts framework like jbeard4's SCION. But i was wondering if it was even possible to export the statecharts files from yakindu, in the scxml format. As the present .sct files seems to be formatted as basic xml. 

Any help would be deeply appreciated. Cheers

**Comment by terfloth** [comment]
@developeron29 : An SCXML export is not available currently. SCT makes use of XMI for storing the statechart. An SCXML export could be implemented as a code generator. Code generators are pluggable into SCT.

**Comment by terfloth** [comment]
follow general interest in SCXML with Yakindu SCT 

see also: http://www-ens.iro.umontreal.ca/~syriani/courses/IFT6253-2016H/Project/topics.html

**Comment by andreasmuelder** [comment]
This blog post may serve as a starting point, contributions are always welcome.
https://blogs.itemis.com/custom_code_generator_scxml

**Comment by developeron29** [comment]
Thanks, I found an alternative to this,
Where i parse XML using DOM_Parser, fetch the required values and paste those values into a SCXML format.. Did the job, Thanks for all the help!

**Comment by andreasmuelder** [comment]
@developeron29 nice, interested in sharing this with the community?

**Comment by andreasmuelder** [comment]
just for documentation, YAKINDU has a SCXML code generator now.
https://www.itemis.com/en/yakindu/state-machine/documentation/user-guide/scxml_codegen
