### ISSUE TITLE
Consolidate: Using annotations vs generator features for event processing

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#3162]

**Comment by andreasmuelder** [comment]
Check docu for all annotation
Change defaults for annotations:

@EventDriven is default, wizard generates EventDriven(@Eventdriven, this annotation is required (validator) 
@Superstep(yes/no) default is @Superstep(no), wizard generates: @Superstep(no)
@ChildFirst /@ParentFirst as is (Warning, parent first is deprecated)

@EventBuffering(in = yes, internal = no) //wizard default no annotation

Validation: internal = no is not possible for EventDriven

SGen: remove Feature EventProcessing, InEventQueue -> deprecated, python remove InEventQueue,
