### ISSUE TITLE
[Homepage] Code formatting is broken on home page

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#3176]
See: https://www.itemis.com/en/yakindu/state-machine/documentation/examples/org-yakindu-sct-examples-codegen-python?hsLang=de

![image](https://user-images.githubusercontent.com/25480651/87306349-2c385e00-c518-11ea-9bb2-6fc3c3bde281.png)

**Comment by andreasmuelder** [comment]
moved to website repo
