### ISSUE TITLE
[Homepage] Move/Remove docu + social buttons

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#3177]
See: https://www.itemis.com/en/yakindu/state-machine/documentation/examples/org-yakindu-sct-examples-codegen-python?hsLang=de

The left part of the page is wasted. 
![image](https://user-images.githubusercontent.com/25480651/87306614-8f29f500-c518-11ea-9d12-4036b3ad4b43.png)

**Comment by andreasmuelder** [comment]
moved to website repo
