### ISSUE TITLE
Domain com.yakindu.domain.scxml is not available SCXML export bug

### ISSUE THREAD

**Issue by IOTeule** [Yakindu/statecharts#3204]
Trying to generate SCXML file from example **TrafficLightStateMachine**.
The Editor complains about missing domain com.yakindu.domain.scxml.

Version: 4.0.0

Documentation not up to date, there is no **model.sgen** file
![image](https://user-images.githubusercontent.com/53375523/92902397-89219900-f421-11ea-9df6-83f613d74a82.png)

Trying to run **TrafficLightStateMachine.sgen** instead failed.

![image](https://user-images.githubusercontent.com/53375523/92901946-2e883d00-f421-11ea-9385-f99feb674c85.png)

Export not possible
![image](https://user-images.githubusercontent.com/53375523/92902721-c84fea00-f421-11ea-9b20-1b020c4bfd42.png)

![image](https://user-images.githubusercontent.com/53375523/92903783-a4d96f00-f422-11ea-80ab-ba398a188ecb.png)

**Comment by andreasmuelder** [comment]
@IOTeule thanks for the bug report. The SCXML Domain is not part of the current beta 4 release, you can download the official release 3.5.13 for the SCXML generator.

**Comment by IOTeule** [comment]
Danke für den schnellen Support
