### ISSUE TITLE
Eclipse 2020-09 + 2.9.3 Community Edition -> broken Java Code generation

### ISSUE THREAD

**Issue by Eno77** [Yakindu/statecharts#3205]
code generated:

protected SCInterfaceImpl **___nterface**; //underlines, instead of "sCI"
(...)
public SCInterface getSCInterface() {
	return sCInterface; //naming is right here
}

vs old:
protected SCInterfaceImpl **sCInterface**;
(...)
public SCInterface getSCInterface() {
	return sCInterface;
}

Same issue (Underlines instead of letters) appears in the port state enumeration.

**Comment by andreasmuelder** [comment]
Hi @Eno77 thanks for the report.
2.9.3 is outdated and not supported anymore. Consider upgrading to a newer version!
