### ISSUE TITLE
Copy / paste of state(s) not working in version 4

### ISSUE THREAD

**Issue by jfgo20** [Yakindu/statecharts#3212]
With CTRL-C/CTRL-V and with contextual menu, it doesn't work.

**Comment by tkutz** [comment]
You need to select the region into which you want to paste. In version 4, a region is selected by clicking on its name or border, not by clicking inside. We changed this in favor of the multi-selection function.

**Comment by jfgo20** [comment]
OK, it worked. But this behavior is different from almost all software. I think I won't be the only one to complain about this.

**Comment by tkutz** [comment]
Ok, thanks for the hint. We will check if more people have similar problems with that.
