### ISSUE TITLE
Connection to github

### ISSUE THREAD

**Issue by LidorPrototype** [Yakindu/statecharts#3216]
Hey, I was wondering if there is a way to connect my SCT to my GitHub?
I've been searching the web for a solution but with no luck

**Comment by LidorPrototype** [comment]
or if there an outside software that can helps with it, for example like GitKraken that helps with some ides and more

**Comment by andreasmuelder** [comment]
Hi, sorry for the late response. What you can do is install the Git Client into YAKINDU:
Help / Eclipse Marketplace / Search for 'Git' / Install 'EGit Integration to Eclipse'
Here is some documentation about EGit:
https://eclipsesource.com/blogs/tutorials/egit-tutorial/
