### ISSUE TITLE
Add error messages and solutions in user docu

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#330]
Mostly, the error messages in SCT show only the errors and not their solution. As the problems view has not the right format to integrate the solutions, it was decided to document the error messages in the user docu together with the solution and to link from the error messages in SCT to this parts of the docu.

Steps to do:
- List error messages (codes)
- Describe problems in user docu
- Add solution descriptions to the problems in the docu
- Link the error messages in SCT with the problems/solutions in the docu

**Comment by terfloth** [comment]
We have to think about the introduction of error codes.

**Comment by svenjawendler** [comment]
This can be connected to #1283, and #559.

**Comment by SimonEit** [comment]
The scope of this seems more like an epic rather than a simple ticket. 

Suggestion: talk with @terfloth and @andreasmuelder about next steps

**Comment by BeckmaR** [comment]
Closing in favor of #1742 where all error message issues are collected.
