### ISSUE TITLE
In a state there are scrollbar artifacts (high metric problem)

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#331]
States have scrollbar artifacts on the right (becomes visible when there is a mouseover -> show a hover). They should be deleted.

<img width="43" alt="hover-state" src="https://cloud.githubusercontent.com/assets/16920235/12718023/1e3e3bee-c8ec-11e5-96bd-c4b2e0be40ce.PNG">

**Comment by BeckmaR** [comment]
Hi @SanniSch, on which Operating System did you encounter this issue? I can't reproduce this right now with the newest version of SCT on Windows 7.

**Comment by svenjawendler** [comment]
Hi, i cannot reproduce it. I once had this problem too, but with the current version this does not occur on windows.
