### ISSUE TITLE
"Show related transition relationships" does not work

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#332]
To reproduce:
- double click on a transition
- click "Show related transition relationships"
  -> nothing happens

Check the configuration of the connection handles: If the function is not implemented, delete it and change tooltip text (Delete "Double click..." part).

**Comment by BeckmaR** [comment]
I can't even get a menu of any sorts when I double click a transition. If @terfloth or @andreasmuelder can confirm, this issue can be closed.

**Comment by svenjawendler** [comment]
I cannot reproduce this too.
