### ISSUE TITLE
Add file extension automatically when user creates new statechart or code generator

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#340]
When creating a new statechart model or code generator, the user has to add the file extension (.sgen or .sct). However, the default title is highlighted completly: when the user starts entering text, the title and the file extension disappear.
-> If the user forgets to add the file extention behind the title, it should be automatically added when the statechart/code generator is created.

**Comment by SimonEit** [comment]
Same issue was reported in #1280 

Current fix is that the error message shows the filetype.

@svenjawendler please close.

**Comment by SimonEit** [comment]
<img width="486" alt="grafik" src="https://user-images.githubusercontent.com/23032586/30157929-df67c580-93c3-11e7-8a16-5551bdb53591.png">
Not the optimal solution for this issue for sure, but good enough for now. Usability Tests should be rerun on this, to see if this is actually an improvement for newbie-users.
