### ISSUE TITLE
Bug in example: Unbound classpath container...

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#342]
When opening the example projects from the welcome page, for the example "traffic_light" there are two error messages as it can be seen in the screenshot.

![traffic_light_error](https://cloud.githubusercontent.com/assets/16920235/12720749/7bdf703c-c8fc-11e5-99b6-e95605038546.png)

**Comment by terfloth** [comment]
@DominikTesch : is this fixed? then please close + pull request if required

**Comment by DominikTesch** [comment]
can not reproduce. Probably realated to missing Java instalation.
