### ISSUE TITLE
Replace SText ParseTreeConstructorFragment with new SerializerFragment

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#397]
In GenerateSText.mwe2, replace the old Serializer API with the new one:

``` XML
fragment = parseTreeConstructor.ParseTreeConstructorFragment {}
```

with

``` XML
fragment = serializer.SerializerFragment auto-inject {
    generateStub = false
  }
```

This has some side effects on the STextResource when auto-serializing feature is enabled (for example during refactorings), SCTResourceTests are failing.

**Comment by tkutz** [comment]
Fixed with PR https://github.com/Yakindu/statecharts/pull/2189
