### ISSUE TITLE
Feature Type Library not included in Custom Generator Plugin

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#399]
When I created a custom generator project as an Eclipse plugin with feature type library. The feature type library description file is not included into the plugin jar. The solution is quiet simple. When generating the project, please generate the library directory entry additionally into the build.properties file.

**Comment by andreasmuelder** [comment]
Thanks for reporting, this is a minor fix and will be part of the next release.

**Comment by andreasmuelder** [comment]
fixed
