### ISSUE TITLE
Document how to create a custom generator

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#401]
I needed about two days to setup a complete SCT custom generator infrastructure including maven build into an updatesite. So I assume that a lot of less experienced people have to spend more time to setup such a project. So it would be nice to have some more documentation how to develop a custom generator.

**Comment by andreasmuelder** [comment]
How to build a custom generator with maven and create an update site is out of scope of YAKINDU Statechart Tools. The documentation on how to create a custom generator - especially more documentation about the different meta models - would be useful.

**Comment by svenjawendler** [comment]
Is this still an issue? The documentation on this is 4 pages.

**Comment by andreasmuelder** [comment]
This should be sufficient. Otherwise it is an issue for the professional support.
