### ISSUE TITLE
Add C++11 timer interface as option to code generator

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#41]
```
Review, test and add Ward Willats contribution:

https://groups.google.com/forum/#!searchin/yakindu-user/Timer/yakindu-user/WWShB
RXAeMk/a0yxLAfbrjMJ

Make generation configurable through sgen switch.
```

Original issue reported on code.google.com by `markus.muehlbrandt` on 29 Sep 2014 at 2:19

**Comment by terfloth** [comment]
Will be added when we revise the c++ code generator.

**Comment by andreasmuelder** [comment]
We will provide a new timer infrastructure in one of the next releases. So this can be closed.
