### ISSUE TITLE
Improve simulation view

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#422]
The simulation view is not prominent enough. Therefore there should be some improvements:
- Switch the position of the outline view and the simulation view
- The simulation view must be wider (currently only the a part of the first column is visible) -> the first and the second column should be visible
- The width of the columns should adapt automatically to the content
- The simulation buttons (start simulation, stop, pause,...) should be integrated at the top of the simulation view

**Comment by terfloth** [comment]
Derive tasks

**Comment by svenjawendler** [comment]
@SanniSch  Is this ok for you?
![simulationperspective](https://cloud.githubusercontent.com/assets/22005752/25616374/768ed90e-2f3c-11e7-8d87-113c679227b5.png)

**Comment by terfloth** [comment]
* We should check if the simulation view layout is smart enough to adapt to view space. There should be no minimal size requirement.

**Comment by SimonEit** [comment]
A follow-up suggestion for this issue:

During usability tests users reported that the current way the transitions are listed in the simulation view reminds them more of "hyperlinks" than actual buttons. Light blue underlined text appears as a link to an external source.

A smarter way would be to display the transitions as visual clickable buttons.

**Comment by robert-rudi** [comment]
simulation view has been improved and new features are already merged.
