### ISSUE TITLE
Builder should consider dirty state

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#427]
The builder does not consider the dirty state, this should be the case.
This leads e.g. to the following problem:
1. Create a new project
2. Create SCT model (do not save)
3. Generate SGen (do not assign it to a SCT)
-> The first state has a error that a state must have a name although it has one

![sct_bug reconstruktion0](https://cloud.githubusercontent.com/assets/16920235/13169346/1ee3ebaa-d6e5-11e5-964f-580a39c1186a.png)
![sct_bug reconstruktion1](https://cloud.githubusercontent.com/assets/16920235/13169343/1e946cc4-d6e5-11e5-9e0f-2409b828cc81.png)
![sct_bug reconstruktion2](https://cloud.githubusercontent.com/assets/16920235/13169342/1e8fc912-d6e5-11e5-8464-572230c5d8c4.png)
![sct_bug reconstruktion3](https://cloud.githubusercontent.com/assets/16920235/13169347/1efa5fca-d6e5-11e5-8a8f-efb2991a2e3f.png)
![sct_bug_rekunstruierung 0](https://cloud.githubusercontent.com/assets/16920235/13169349/1f0b668a-d6e5-11e5-86d0-1ff97df25e9c.png)
![sct_bug_rekunstruierung 1](https://cloud.githubusercontent.com/assets/16920235/13169344/1ea17518-d6e5-11e5-8716-067dc3222791.png)
![sct_bug_rekunstruierung 2](https://cloud.githubusercontent.com/assets/16920235/13169345/1ea820a2-d6e5-11e5-905c-f5eb8042b3dc.png)
![sct_bug_rekunstruierung 3](https://cloud.githubusercontent.com/assets/16920235/13169348/1efa831a-d6e5-11e5-9493-a864035d73be.png)

**Comment by BeckmaR** [comment]
Can't reproduce, possibly fixed already.

**Comment by svenjawendler** [comment]
I cannot reproduce it. I assume it also as fixed.
