### ISSUE TITLE
Avoid Duplicate NamedElement error

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#428]
It is not ovious that an initial entry node or a history must have a name: the problem occurs when the user drags both to the SC. Then there is an error message that there is a dublicated NamedElement. It should be avoided that such errors occur. As it is not possible to name the elements in the SC model direclty but only in the properties, the elements could get a default name (e.g. histroy1, history2). Furthermore, the properties should open when such an element is dragged (with cursor in field name) that the user can change the name direclty if he like. 
If there is still an error, the error message should be more concrete: it should include the type of the elements which have the same name (e.g. initial entry node, history) and the dublicate name.

**Comment by andreasmuelder** [comment]
This was fixed with https://github.com/Yakindu/statecharts/pull/1879
