### ISSUE TITLE
Shortcuts/Delete via keyboard does not always work

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#430]
In the statechart diagram it is no possible to delete elements via delete key. Also shortcuts such as Ctrl + Z do not work. This is a general problem on MAC (e.g. delete never works) but also happens sometimes on windows.

**Comment by jdicks** [comment]
on windows shortcuts are working as expected, even if perspectives are changed. This might be an external issue. 
we still have to test this on mac.

**Comment by tkutz** [comment]
My assumption is that the statement "Does never work on Mac" refers to using backspace which is [Fn+Backspace] on Mac or [Del] is extended keyboard is used.

**Comment by tkutz** [comment]
@andreasmuelder @DominikTesch please test this and fill out the above table

**Comment by jdicks** [comment]
@andreasmuelder observed that it becomes broken after editing via the properties view or editing wihtin specification items, but still not reproducible.

**Comment by svenjawendler** [comment]
Windows 7: Ctrl+M, Ctrl+Y, Ctrl+Z, Ctrl+A, Ctrl+C, Ctrl+V, Ctrl+X work fine.

**Comment by svenjawendler** [comment]
On Mac all the matching shortcuts also work.
