### ISSUE TITLE
Difficult to select elements, especially transitions

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#431]
The user must be very precisly when he wants to select elements, especially transitions. The clickable area of all elements should be enlarged.

Further it is very hard to multi-select nested elements. Users wish to have a selection tool similar to the marquee tools from papyrus: https://wiki.eclipse.org/Papyrus_User_Guide/Palette/Marquee_Selection_Documentation

**Comment by svenjawendler** [comment]
Also survey participants wanted this enhancement !

**Comment by svenjawendler** [comment]
Today a user that sent feedback also reported this issue.

**Comment by andreasmuelder** [comment]
First part is fixed, I opened a new issue for the marquee tool:
https://github.com/Yakindu/statecharts/issues/2260
