### ISSUE TITLE
Allow to change content of code area by single click

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#435]
To enter code in the code area of the statechart model the user must do a doubleclick. This is cumbersome: the area should become active by a single click.

**Comment by terfloth** [comment]
We should implement this prototypically and check if single click activation interferes with other interactions.

**Comment by svenjawendler** [comment]
Currently with a single click the title is editable. Another click activates the textual area, though it is not visible. I only recognize it when I start typing.

**Comment by SimonEit** [comment]
#1442 is the "epic" / collective of tickets regarding the improvement of the specification section and covers everything in here. Therefore closing it.
