### ISSUE TITLE
Improve responsive behavior of welcome dialogue

### ISSUE THREAD

**Issue by SanniSch** [Yakindu/statecharts#436]
When the screen becomes smaller, the welcome page behaves responsive. However, the size (length) of the different boxes is different (see screenshot). The boxes in each row should have the same length.

<img width="431" alt="welcome-page" src="https://cloud.githubusercontent.com/assets/16920235/13170411/097d13d4-d6ec-11e5-8ecd-1ddef49150de.PNG">

**Comment by svenjawendler** [comment]
Why should they have the same length? 
![saverequireddirtyeditorsbeforelaunching](https://cloud.githubusercontent.com/assets/22005752/25615188/2fd1ff1a-2f36-11e7-86ef-a3d0b28f8193.png)

**Comment by andreasmuelder** [comment]
duplicate in pro
