### ISSUE TITLE
Scope provider should make use of import aware scope provider from xtext

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#442]
The scope provider is reimplementing functionality that is already provided by ImportedNamespaceAwareLocalScopeProvider. This should be refactored.

**Comment by andreasmuelder** [comment]
@tkutz is this done?

**Comment by tkutz** [comment]
Fixed by pull request #443

**Comment by tkutz** [comment]
Further fixes related to this issue are performed in pull requests:
#455 #458
