### ISSUE TITLE
FOP throughs exceptions upon generating PDF documentation

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#448]
The PDF version of the documentation is generated in two steps:

* DocBook XSL transforms the DocBook sources to XSL-FO.
* Apache FOP transforms XSL-FO to PDF.

While throwing exceptions, FOP still generates the PDF documentation. However, the underlying problem should be analyzed and mitigated, if possible.

**Comment by andreasmuelder** [comment]
Closing as invalid since we do not use docbook anymore
