### ISSUE TITLE
Error Icon overlaps the label

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#45]
```
The Error icons hides parts of the underlying label that makes the diagram hard 
to read if errors exists.
```

Original issue reported on code.google.com by `A.Muel...@googlemail.com` on 29 Sep 2014 at 2:51

**Comment by SimonEit** [comment]
@svenjawendler and i reviewed this issue. Problem seems to still exist in few cases and seem very minor. 
Here is an example on how to reproduce the issue:

Step 1: Create a simple errorous state chart
<img width="251" alt="grafik" src="https://user-images.githubusercontent.com/23032586/29570427-ba59ff20-8756-11e7-8d3b-c17bf681aa2e.png">

Step 2: Move the state up
<img width="219" alt="grafik" src="https://user-images.githubusercontent.com/23032586/29570472-d31ffcf8-8756-11e7-9f4a-3b7ec2fe85ba.png">

The error icon now overlaps the transition label. A simple manual drag of the label fixes the issue.

Suggestion: close this ticket, reason: very minor issue
