### ISSUE TITLE
Test are not executed in build

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#457]
TimedTransitionTest ( c-test )
ActionOutgoingTransitionInitialState ( c-test )
test-gen ( java-test )
alle org.yakindu.sct.generator.java.test (src, java-test )
InterpreterOperationsTest.java ( core.sexec.test )
NullCheckTest ; OperationWithoutBracesTest ; TimedTransitionTest ; TriggerExpressionPrecedenceTest ; TypeAliasTest ( test-gen, core.sexec.test )

**Comment by andreasmuelder** [comment]
fixed
