### ISSUE TITLE
Replace tabs by spaces in generated source code

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#469]
Use source code having tabs anywhere in a context with different tab with settings – e.g. in the SCT documentation –, and everything looks awkward and broken. This is especially true if those tabs are not just at the beginning of lines but somewhere in the middle.

Consequently, all code generators should be fixed to generate spaces instead of tabs.

**Comment by andreasmuelder** [comment]
We will not change the way how the code is generated only for documentation. Closing as invalid
