### ISSUE TITLE
Pressing Save while the in diagram editor is open closes the editor

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#47]
```
The in diagram editor should stay open if CTRL-S is pressed during text editing.
```

Original issue reported on code.google.com by `A.Muel...@googlemail.com` on 29 Sep 2014 at 2:54

**Comment by BeckmaR** [comment]
This is most likely not easily achieved. Eclipse itself handels the resource that is saved and closes all widgets way before any yakindu class gets called. The editing text window is already closed as soon as our editor's function `DoSave` is called. A `SaveableHelper` takes care of this.

**Comment by BeckmaR** [comment]
Reopening, there has to be a way, because form-based editors are able to keep the focus when saving.

**Comment by BeckmaR** [comment]
The main problem is that, for example, a state has an `XTextStyledTextEditor` that has the focus. When the focus is lost, this element is destroyed. When the focus should come back, the receiving element has gone away, and can't take the focus back. Closing for now.
