### ISSUE TITLE
Prioritization of regions is not obviously visible in editor and simulator.

### ISSUE THREAD

**Issue by nyssen** [Yakindu/statecharts#475]
Regions are executed according to their respective prioritization. When simulating the attached example as follows, this leads to the following (intended behavior):

![sct_issuet](https://cloud.githubusercontent.com/assets/1277220/13454553/48a84914-e058-11e5-888a-b4ad348c7917.PNG)

After starting the simulation:
1.  raise 'change': states B (region a) and D (region b) become active, i.e. the change2 event, raised by exiting state A, is directly consumed in region b (as this region has lower priority and is executed before).
2.  raise 'change3': state C (region b) becomes active, but not state A (region a), because it is contained in a region that has higher priority (and the internal event is raised after the region was executed, so here the raised event is not directly consumed).

While the behavior is consistent (the execution semantics is defined based on prioritization of regions), the user does not have any direct visual feedback about the prioritization in the UI, but only implicit through their orientation (priorities match the orientation). We should IMHO add a more specific visualization of the priorities.

Further, during simulation the execution of the region is never highlighted as a simulation step. As such, the fact that in step 2. region a is executed (while not doing anything) before region b is not visible to the user. We should IMHO highlight the active region and add support for visualization of such 'micro steps'.

**Comment by nyssen** [comment]
The following models can be used to reproduce the issue.
[default.sct.txt](https://github.com/Yakindu/statecharts/files/154324/default.sct.txt)
[default.sgen.txt](https://github.com/Yakindu/statecharts/files/154325/default.sgen.txt)

**Comment by jdicks** [comment]
This came up from several users, see:
* https://groups.google.com/forum/#!msg/yakindu-user/wgkUHokZDZ0/aJt7BJffo7MJ
* https://groups.google.com/forum/?fromgroups#!topic/yakindu-user/bkDvPghMiYk

@terfloth explained related aspects of current solution: 
https://groups.google.com/d/msg/yakindu-user/wgkUHokZDZ0/VOkBzhh_T8EJ

**Comment by andreasmuelder** [comment]
Added visual feedback for regino priorities
