### ISSUE TITLE
Typo in error message: "Transisition is never taken"

### ISSUE THREAD

**Issue by szarnyasg** [Yakindu/statecharts#476]
There is a typo in the error message "Transisition is never taken", instead of "**Transition** is never taken". The source of the string is https://github.com/Yakindu/statecharts/blob/master/plugins/org.yakindu.sct.model.stext/src/org/yakindu/sct/model/stext/validation/STextValidationMessages.java#L45.

The typo originates from commit https://github.com/Yakindu/statecharts/commit/ee7777eec334c5d5dcf7edaef8ba59720b852d78.

**Comment by andreasmuelder** [comment]
fixed via fc918b2 , @szarnyasg thanks for reporting
