### ISSUE TITLE
C code generator does not handle externally defined enumerations

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#488]
Although we do not support yet the declaration of enums in statechart specification (#477), there are use cases where enums are externally provided. These enum types are not handled by the C code generator.

In order to reuse most of the existing implementation it might make sense to let the meta type Enumerator inherit from Declaration in the types metamodel. The C code generator can then be easily adjusted.

**Comment by terfloth** [comment]
@tkutz isn't this issue fixed with PR #489

**Comment by tkutz** [comment]
Fixed with pull request #489
