### ISSUE TITLE
Eclipse helptext - bad characters

### ISSUE THREAD

**Issue by gjsjohnmurray** [Yakindu/statecharts#491]
For example in "Statechart Tools User Guide, SCT, Generating Java source code, The CallHandling example, Creating the statechart model" I see this (notice the two occurrences of â€Š):

Let’s have a closer look at the listing above:
• yakindu::java is the unique ID of the Java code generator. 
•The statechart CallHandling { â€Š } block references the statechart model we want to generate code for. 
•The feature Outlet { â€Š } block specifies where the generated code artifacts are to be placed, i. e. in the Eclipse project CallHandling and within that project in the src-gen folder.

**Comment by gjsjohnmurray** [comment]
Just found this already logged in #424

**Comment by gjsjohnmurray** [comment]
Under #424 you're asking for clarification about this, so am reopening here with a screenshot attached showing how it affects your help when viewed from within Eclipse, but not at your website.

![issue424](https://cloud.githubusercontent.com/assets/6726799/13854490/a7888f36-ec63-11e5-95b5-51a7083e96bb.png)

**Comment by RainerKlute** [comment]
Oh, I see. Thanks for clarification, John!

**Comment by RainerKlute** [comment]
Fixed with pull request #514.
