### ISSUE TITLE
Getting Started, CallHandling example project needs to be created as a new Java project

### ISSUE THREAD

**Issue by gjsjohnmurray** [Yakindu/statecharts#492]
Text headed "Creating the statechart model" says:

> In the Getting Started tutorial we have seen how to operate the statechart editor. So let’s create a new project now and use the statechart editor to create the CallHandling statechart model as outlined above.

 
I suggest you clarify that we need to create a Java project, unlike in the LightSwitch example where it was a General Project.

**Comment by RainerKlute** [comment]
Will be fixed in the next release.
