### ISSUE TITLE
Documentation lacking info about Exit pseudostate

### ISSUE THREAD

**Issue by gjsjohnmurray** [Yakindu/statecharts#494]
[This 2014 forum post](https://groups.google.com/forum/#!searchin/yakindu-user/exit/yakindu-user/QErG1mu4Smw/xIykMDO2at8J) is the best I have found so far, though the PNG link in Andreas's first reply no longer works.

**Comment by gjsjohnmurray** [comment]
More info in [this newer forum post](https://groups.google.com/d/msg/yakindu-user/p2isZPHqTsk/wxp6QdjioLMJ).

**Comment by RainerKlute** [comment]
Entry, exit, initial and final states will be explained in detail in the documentation of the next release.
