### ISSUE TITLE
SCT simulation triggers workspace build

### ISSUE THREAD

**Issue by nyssen** [Yakindu/statecharts#496]
In case of C projects that might lead to execution of make, which is not required for the generation (and make consume a considerable amount of time).

**Comment by andreasmuelder** [comment]
@nyssen Is this only the case when the model that is simulated was dirty before starting the simulation and thus an incremental build is triggered when auto-saving the resource?

**Comment by terfloth** [comment]
The CDT build won't be triggered on saving a dirty statechart but on starting the simulation. This should not happen. Simulation should work independent of automated build settings.

**Comment by andreasmuelder** [comment]
This is the default eclipse behavior, you can disable this via the launch preferences

![buildbeforelaunch](https://cloud.githubusercontent.com/assets/6338708/20054526/89501222-a4dd-11e6-9bad-92c53507a9b6.png)

Hoewever, we could override this settings to always return false in case of statechart simulation.

**Comment by andreasmuelder** [comment]
I opened PR #1067 to never build workspace before launching statechart simulation
