### ISSUE TITLE
Cannot generate into a project's root folder

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#499]
I cannot generate code into a project's root folder. SGen configuration options like

```
    targetFolder = "."
```

```
    targetFolder = "/"
```
```
    targetFolder = ""
```
won't work. They are triggering a warning, saying the respective folder wouldn't exist. No code is generated.

**Comment by andreasmuelder** [comment]
@terfloth is this a requirement?

**Comment by terfloth** [comment]
Yes this is definitely necessary.

**Comment by jdicks** [comment]
i tried out 
~~~
 targetFolder = "."
~~~
an code was generated into the root folder, even if the warning in sgen file will be shown

**Comment by RainerKlute** [comment]
Confirmed. There shouldn't be any warnings, though.
