### ISSUE TITLE
Include wikitext.zip statically for now

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#510]
Unfortunately Mylyn WikiText Standalone is available as a nightly build only. Downloading it dynamically during the build is shaky at best, leading to frequent build errors. Until a released WikiText version is available, download the most current wikitext.zip from the link given in http://www.eclipse.org/mylyn/downloads/, include it statically in our repository, and update it as needed.

**Comment by andreasmuelder** [comment]
@RainerKlute The link you posted contains a releases update site:
http://download.eclipse.org/mylyn/releases/latest

**Comment by RainerKlute** [comment]
@andreasmuelder I need the standalone version.

**Comment by RainerKlute** [comment]
Fixed in branch https://github.com/Yakindu/statecharts/tree/issue_510_wikitext.zip.
