### ISSUE TITLE
Redraw SGen screenshots for CallHandling example

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#524]
### Task 1
The screenshots are missing the _libraryTargetFolder_ option and should be recreated, provided we are keeping the _CallHandling_ example.

### Task 2
In issue #424, @SanniSch pointed out:
> * CallHandling Tutorial in Dismiss State "dura (new line)tion": there is a line break here that is wrong

**Verified**. It's in the images. They should be redrawn, provided we are keeping the *CallHandling* example.

**Comment by andreasmuelder** [comment]
Closed since we won't keep the callhandling example
