### ISSUE TITLE
Consistently use spaces around ellipses on "welcome" page

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#525]
Currently (i. e. in release 2.5.0) spaces around ellipses on the "welcome" page are used inconsistently.

To suggest an omission, the ellipsis character (…) must always be used, not three dots in a row (...).

There doesn't seem to be a typographic rule for the English language, stating whether to put spaces around an ellipsis or not. Anyway, we should do it consistently.

I like the German rule and suggest to apply it:
* If the ellipsis replaces a **part** of a word, don't put a space between the ellipsis and the remaining part of the word. Example: "You are the biggest id… on earth."
* If the ellipsis replaces a **complete** word or a sequence of complete words, separate the ellipsis and the remaining text by spaces. Example: "You are the biggest … on earth."

(Inspired by issue #424)

![welcome_page](https://cloud.githubusercontent.com/assets/1495781/13990502/eb72cfd0-f114-11e5-93d9-0da7f199ca52.png)

**Comment by andreasmuelder** [comment]
This issue was moved to Yakindu/sctpro#231
