### ISSUE TITLE
Remove unused imports from example custom xtend code generator

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#532]
When creating a new custom xtend code generator, the created generator has two warnings because of unused imports. These should be removed.

**Comment by terfloth** [comment]
What are the unused imports? 

If these are potentially useful we should extend the provided generator skeleton to make the usage clear.

**Comment by tkutz** [comment]
The unused imports are:

import java.io.File
import java.io.FileOutputStream

They became obsolete after IFileSystemAccess has been used.

**Comment by DominikTesch** [comment]
Fixed #587
