### ISSUE TITLE
Simulation View disappears after terminate

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#543]
When you change something in your statechart while running it, and you start a new simulation you must save the new one and you have to terminate the old simulation. Then the new simulation starts without a simulation view.

**Comment by andreasmuelder** [comment]
Steps to reproduce:
1. Launch a startchart
2. Change the statechart model, do not save
3. Launch another statechart
4. Save and terminate
Result: Statechart is running with empty Simulation view

**Comment by andreasmuelder** [comment]
Fixed via PR ##658 @DominikTesch  Please retest this

**Comment by DominikTesch** [comment]
The activ state in the first statechart simulation stays activ after after terminate.

**Comment by terfloth** [comment]
@DominikTesch  @andreasmuelder  : isn't the issue reopened due to another problem then the original? Then close this and open a new issue.

**Comment by andreasmuelder** [comment]
The merged PR introduces this regression, so reopening this issue is fine.

**Comment by robert-rudi** [comment]
could not reproduce initially described issue
