### ISSUE TITLE
Fix spelling in run configuration

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#545]
In the run configuration dialog, "cycle based" must be replaced by "cycle-based" and "event driven" by "event-driven".

Capitalization should be consistent. One might argue whether to use sentence style, title style, or heading style (see [these explanations](https://en.wikipedia.org/wiki/Letter_case#Case_styles)), but in any case we should be consistent. I suggest to use sentence style and in analogy to "Model file" label the other parameters as "Operation class", "Execution type", and "Cycle period".

**Comment by jdicks** [comment]
see #651

**Comment by DominikTesch** [comment]
Fixed #651
