### ISSUE TITLE
Exception on full build for traffic light example

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#551]
When you open one example, all examples will open (traffic light, digital watch, light switch).
The ftaffic light example throws an NullPointer Exception because of the generator.
Moreover it is the wrong traffic light example

**Comment by tkutz** [comment]
@terfloth which traffic light example do we want to ship? There is a new one with swing graphics, but it is currently not included in the product.

**Comment by tkutz** [comment]
The problem is related to the order of eclipse builders specified in .project file.
We need the Xtext builder to run first in order to create an index and afterwards run the SCTBuilder to invoke our generator models (.sgen).

**Comment by terfloth** [comment]
Changed order of builders on the project.
