### ISSUE TITLE
Java API or Xtext grammar to design SCT

### ISSUE THREAD

**Issue by benedekh** [Yakindu/statecharts#556]
Dear All,

Is there a Java API or Xtext grammar to construct SCT programmatically?

Best regards,
Ben

**Comment by terfloth** [comment]
@benedek : yes - there is a Java API. Everything is based on EMF with some SCT specific extensions. SCT itself creates statecharts using the API. For an example take a look at the [CreationWizard.createDiagram()](https://github.com/Yakindu/statecharts/blob/master/plugins/org.yakindu.sct.ui.editor/src/org/yakindu/sct/ui/editor/wizards/CreationWizard.java) method and [FactoryUtils](https://github.com/Yakindu/statecharts/blob/master/plugins/org.yakindu.sct.ui.editor/src/org/yakindu/sct/ui/editor/factories/FactoryUtils.java) class. FactoryUtils creates both the semantic and notation (diagram) part of the statechart. Creating the notation part (everything from gmf / Nodes and Edges) is optional.

**Comment by benedekh** [comment]
Thank you.
