### ISSUE TITLE
Cut-Copy-Paste Keyboard-Shortcuts do not work on OSX

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#557]
Using the context menu actions works as expected.

**Comment by terfloth** [comment]
Cmd-X-C-V works in the SCT product. 

In the developer runtime workspace there are additional bindings (when: diagram editing) that seem to conflict with the standard binding (when: in dialogs and windows). It is probably Papyrus stuff...

![bildschirmfoto 2016-04-04 um 11 10 03](https://cloud.githubusercontent.com/assets/1296498/14243459/fc59b3d2-fa55-11e5-9981-0938e36975dc.png)

**Comment by tkutz** [comment]
Yes indeed, it seems to be related to papyrus. Disabling papyrus plugins from launch config helps.

Is there anything to be done for this issue then?

**Comment by tkutz** [comment]
@andreasmuelder add reference to bugzilla entry and close the issue

**Comment by andreasmuelder** [comment]
This is an external bug by papyrus https://bugs.eclipse.org/bugs/show_bug.cgi?id=481230
