### ISSUE TITLE
Fix upper case versus lower case spelling errors

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#559]
Nouns in error messages and other strings – except for the first word of such a phrase and except for titles and/or headings – must begin with a lower-case letter.

A counter-example is the following error message:

`Duplicate NamedElement 'xyz' in Region 'main region'`

Should read:

`Duplicate named element 'xyz' in region 'main region'`

More counter examples:
- `Outgoing Transitions from Entries can not have a Trigger or Guard.`

**Comment by jdicks** [comment]
@terfloth : plz comment

**Comment by terfloth** [comment]
Yes validation texts should be fixed.

**Comment by BeckmaR** [comment]
Closing in favor of #1742 where all error message issues are collected.
