### ISSUE TITLE
'Extract subdiagram' refactoring can also be applied to states that are connected to synchronization nodes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#57]
```
The current implementation of the refactoring cannot handle connected 
synchronization nodes (see attachment).

- investigate how the refactoring court be extended to cover this scenario.
```

Original issue reported on code.google.com by `AxelTerfloth` on 8 Oct 2014 at 11:07

Attachments:
![test_composite](https://cloud.githubusercontent.com/assets/12081541/8671586/af41604a-2a26-11e5-8645-914be4d3437f.png)

**Comment by terfloth** [comment]
is duplicate of #56
