### ISSUE TITLE
Ctrl +/- for zooming does not work

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#570]
The shortcut does not work on Mac as well as on Windows.

**Comment by RainerKlute** [comment]
Same for Linux

**Comment by tkutz** [comment]
Fixed with pull request #842.
Following shortcuts work now:

Win/Unix - English keyboard: Ctrl= / Ctrl-
Win/Unix - German keyboard: Ctrl+ / Ctrl-

OS X - English keyboard:  Cmd= / Cmd- 
OS X - German keyboard: Cmd+ / Cmd-

**Comment by DominikTesch** [comment]
![tastatur_de svg](https://cloud.githubusercontent.com/assets/15800400/22147149/9716fd6c-df07-11e6-995b-c316bfdf0c6b.png)
CTRL and + / - in the green box are working
CTRL and + / - in the red box are not working

**Comment by svenjawendler** [comment]
This behavior is similar in other eclipse editors.
