### ISSUE TITLE
False error on synchronization node if it is embedded in one of orthogonal regions 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#58]
```
What steps will reproduce the problem?
1. See the attached image

What is the expected output? What do you see instead?
There should be no error marker

Please use labels and text to provide additional information.

```

Original issue reported on code.google.com by `AxelTerfloth` on 8 Oct 2014 at 11:13

Attachments:
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/12081541/8671525/191e06cc-2a26-11e5-89b6-7af6675e121d.png)

**Comment by bohl-itemis** [comment]
Validation rule matches a predecessor definition, in which this error marker is purposed (no switching between orthogonal areas).

This works:
![image](https://cloud.githubusercontent.com/assets/12081541/8778017/b68a1a2a-2efb-11e5-9216-b28443115101.png)

This should not be possible:
![image](https://cloud.githubusercontent.com/assets/12081541/8778033/d8d734e6-2efb-11e5-9093-249062de4dfa.png)

A clear and consistent Definition is needed for orthogonal regions.

**Comment by terfloth** [comment]
This issue essentially describes two validation bugs:

1. The placement of the synch node in one of the regions is valid and the code generator correctly generates code from it.
1. The transition between two orthogonal states is invalid.
