### ISSUE TITLE
Highlighting of taken transitions

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#581]
It seems like the highlighting of taken transitions is not working as expected anymore:

When a transition is taken, it is only briefly highlighted. It would make sense to have a permanent highlighting so that the user understands from which transition a state was entered (see test case T3.2 in test manual)

We should discuss what the expected highlighting strategy is and reflect it in the test manual.

**Comment by andreasmuelder** [comment]
@terfloth @tkutz  A taken transition only flashes once, would it be better to highlight the transition as long as the state is active?

**Comment by terfloth** [comment]
This could provide a better orientation for the user. We should also consider, that there are more complex scenarios, especially when pseudo states (choice, synch, entry, exit) are involved. We also have to consider high frequency highlighting changes as well as single step debugging modes.

**Comment by svenjawendler** [comment]
Now the behavior is as stated by andreasmuelder.
