### ISSUE TITLE
Operation calls without brackets possible

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#582]
Consider a statechart with an operation defined as "operation myOp():boolean". 
This operation can be called as "myOp" instead of "myOp()" in the statechart.

As there is an explicit test case in our test manual (T11.6), I assume this is unexpected behaviour.

To fix this we should:
1. Add a validation
2. Provide better code completion that automatically creates these brackets

**Comment by tkutz** [comment]
The possibility to use a function without brackets when it has no input parameters is desired behavior.
The test case is wrong and should be deleted.

**Comment by RainerKlute** [comment]
I left the test case in the test plan but specified the correct behavior. Fixed with pull request #590.
