### ISSUE TITLE
Documentation of keyword proposals is white on white

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#583]
The documentation of keyword proposals is available and correct, but it is displayed white on white, i.e. the popup windows seems to be empty. Select the text with the mouse to make it visible.

This is some CSS issue.

**Comment by tkutz** [comment]
It works fine for Mac and Windows.
Seems to be Linux specific.

**Comment by RainerKlute** [comment]
Fixed with pull request #595.
