### ISSUE TITLE
Compare produces invalid models which cannot be repaired in GUI-Editor

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#60]
```
If you merge only selected changes a merge can cause a invalid model which 
cannot be repaired in editor.

1. compare the two statecharts
2. go down the tree and merge the selected part (see picture 01.png)
3. save
4. the "copy of default.sct" becomes invalid (Error 1 is expected, error 2 
causes in a lack of "target" for the Transition feature. see picture 02.png)



```

Original issue reported on code.google.com by `malkne...@gmail.com` on 14 Oct 2014 at 12:13

Attachments:
![01](https://cloud.githubusercontent.com/assets/12081541/8671919/6cc04f94-2a29-11e5-8382-f9ab6d6613d1.png)
![02](https://cloud.githubusercontent.com/assets/12081541/8671920/6e64ecc4-2a29-11e5-84a3-d609e2a45765.PNG)
* [default.sct](https://storage.googleapis.com/google-code-attachments/yakindu/issue-60/comment-0/default.sct)
* [Copy of default.sct](https://storage.googleapis.com/google-code-attachments/yakindu/issue-60/comment-0/Copy of default.sct)
* [Copy of default_after merge.sct](https://storage.googleapis.com/google-code-attachments/yakindu/issue-60/comment-0/Copy of default_after merge.sct)

**Comment by andreasmuelder** [comment]
Does this bug still exist with the mars target?

**Comment by andreasmuelder** [comment]
@bohl-itemis Does this bug still exist with the mars target?

**Comment by bohl-itemis** [comment]
With Mars Target now, an exception is thrown:
![image](https://cloud.githubusercontent.com/assets/12081541/9713751/b9c4cf4a-5553-11e5-821d-691355b09ac7.png)

**Comment by andreasmuelder** [comment]
The Models are not accessible and I could not reproduce this error with new models.
Closed
