### ISSUE TITLE
Cannot zoom to selection since selection is deselected

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#600]
- Select some part of a statechart you want to zoom to, e.g. one or two states out of many.
- Right-click on the canvas in order to open the context menu and be able to access the _Zoom → Fit to Selection_ menu entry.
- However, upon right-clicking, the selected elements are deselected, and there is not a longer a selection to zoom to.

Zooming to a selection works (more or less) when using _Diagram →  Zoom → Fit to Selection_ from the main menu.

**Comment by jdicks** [comment]
This is as eclipse works in general, whenever a right-click is used the actual mouse position will be passed as context.

**Comment by RainerKlute** [comment]
Well, if _Zoom → Fit to Selection_ cannot work when called from the context menu, we shouldn't offer it there, but only in as _Diagram → Zoom → Fit to Selection_ in the main menu.

**Comment by jdicks** [comment]
The zoom tools are contributed by the underlying GMF Framework. Please file GMF related bugs into the Eclipse GMF Bugzilla.
