### ISSUE TITLE
"Fit to selection" should show the selection after zooming

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#601]
1. Select e.g. a state.
1. Select _Diagram → Zoom → Fit to Selection_ from the main menu.
1. The statechart editor does some zooming. However, the viewport doesn't show the selected elements the user wanted to zoom to, but instead points elsewhere.

**Comment by andreasmuelder** [comment]
The zoom tools are contributed by the underlying GMF Framework. Please file GMF related bugs into the Eclipse GMF Bugzilla.
