### ISSUE TITLE
Reconsider element documentation UI

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#603]
YAKINDU Statechart Tools allows for annotating elements with a _documentation_ property. However, graphical presentation and editing this property in the statechart editor are suboptimal is several respects. For example, enter a very, very, very long line as element documentation and see what happens in the properties view as well as in the diagram. I suggest to reconsider the element documentation UI.

**Comment by andreasmuelder** [comment]
The text box for the documentation should auto wrap to avoid layout issues for long documentation strings.

**Comment by andreasmuelder** [comment]
Fixed with PR #654
