### ISSUE TITLE
Updatesite suggests SCT 2.6.0 but installs 2.5.0

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#605]
See attached screen shots.
![sct1](https://cloud.githubusercontent.com/assets/975841/14403039/1641695c-fe48-11e5-8937-38ef1bc79d0f.jpg)
![sct2](https://cloud.githubusercontent.com/assets/975841/14403041/1657050a-fe48-11e5-95db-5a8266deeae0.jpg)
![sct3](https://cloud.githubusercontent.com/assets/975841/14403040/1642e570-fe48-11e5-942f-fc2944aea306.jpg)

**Comment by tkutz** [comment]
Thanks for the hint, we will fix this as soon as possible.

For now, please do not check "YAKINDU 2 SDK" which only exists in version 2.5.0 and not for 2.6.0. That should give you a clean installation of the 2.6.0 version.

**Comment by tkutz** [comment]
To make it clearer for the user, we added a new category "YAKINDU SCT (old 2.5.0) which only contains 2.5.0 relevant features. The normal YAKINDU SCT category hence does not contain the 2.5.0 SDK feature anymore.
