### ISSUE TITLE
"Check for updates..." does not work on SCT

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#606]
After checking for updates the following error messages appear:

![sct4](https://cloud.githubusercontent.com/assets/975841/14403052/9c95825e-fe48-11e5-9424-d7b2525a311b.jpg)
![sct5](https://cloud.githubusercontent.com/assets/975841/14403053/9fe20932-fe48-11e5-997b-13cd4c933d94.jpg)

**Comment by tkutz** [comment]
The problem here seems to be that we do not ship an SDK feature anymore with 2.6.0.

A workaround is to first uninstall the YAKINDU 2 SDK feature. Afterwards, the update should work.

**Comment by tkutz** [comment]
There seems to be no solution for now, other than uninstalling the SDK before invoking an update.
