### ISSUE TITLE
Selection tool label should read "Transitions only"

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#612]
The fourth submenu of the _selection_ tool in the statechart editor's palette is labeled `Connections only`. It should read `Transitions only` instead.

This applies analogously to the _Intersection selection_ menu.

**Comment by RainerKlute** [comment]
Please also see issue #614.

**Comment by andreasmuelder** [comment]
Added by Papyrus and not part of the product. Closing as invalid.
