### ISSUE TITLE
Includes to headers should be relative paths

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#627]
Currently the C code generator creates includes as simple file names, e.g.:
````
#include "sc_types.h"
````
This works fine when the header is in the same folder as the source. But as we can set the library target folder, the include should be relative, e.g.:
````
#include "src-lib/sc_types.h"
````

This issue involves some refactoring because we need to know the generation target locations of all artifacts before we can compute their contents. Currently our C code generator works the other way round, first create content and then define where to write it to.

**Comment by jdicks** [comment]
fixed by #629
