### ISSUE TITLE
Transition not taken when operation not found

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#637]
![unbedsfnannt](https://cloud.githubusercontent.com/assets/15800400/14631378/5c88b8c0-0613-11e6-8593-12c0cf55d39f.jpg)

In Run As mode, when changing the operation return value to something >100, the transition is taken.
In Debug mode, this does not work. It seems like in debug mode, a search for a java operation is failed as the following exception says:

**Comment by DominikTesch** [comment]
![unbedsfnannt](https://cloud.githubusercontent.com/assets/15800400/14631863/c93cdb52-0615-11e6-8656-5cef4df5322f.jpg)

**Comment by andreasmuelder** [comment]
This issue was moved to Yakindu/sctpro#229
