### ISSUE TITLE
Replace "Xtend2/Java" by "Xtend/Java"

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#639]
While http://www.eclipse.org/xtend/ calls Xtend "Xtend", SCT still calls it "Xtend2/Java" in documentation and GUI.

In order to minimize disorientation, replace "Xtend2/Java" replace "Xtend" everywhere.

**Comment by andreasmuelder** [comment]
This wizard support Xtend and Java, not only Xtend. The language option can be selected via checkbox in the wizard.

**Comment by RainerKlute** [comment]
Understand. So "Xtend2" should be replaced by "Xtend".

**Comment by andreasmuelder** [comment]
This is what I did as you can see in 4c88be6
