### ISSUE TITLE
Rework feature structure and dependencies

### ISSUE THREAD

**Issue by jdicks** [Yakindu/statecharts#644]
org.yakindu.sct-feature should be splitted into logical senseful parts to increase flexibility during integration.

As a starting point see: https://github.com/Yakindu/statecharts/pull/643

__NOTE__ This might break update functionality!
_______________________________________________________________
extracted see  #653 
~~Further branding & documentation should be seperated from each other to avoid deep coupling between 'branded' features and the documentation(/branding) plugin.~~

**Comment by andreasmuelder** [comment]
@jdicks can you please split this in two issues?
