### ISSUE TITLE
"Rename" refactoring doesn't work on Linux

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#661]
There are two variants of brokenness of the _Rename_ refactoring on Linux:
- When trying to rename e.g. a variable in the definition section or in the graphical editor, the _Refactoring_ menu appears only very, very briefly, if at all.
- When trying to rename e.g. a variable in the _State Behavior_ section in the _Properties_ view, the selected variable's _Refactoring_ menu appears, but its _Rename …_ entry is inactive.
  ![screenshot](https://cloud.githubusercontent.com/assets/1495781/15011548/b5e16ac6-11f2-11e6-9174-3464a7ed7beb.png)

**Comment by jdicks** [comment]
is related to #1364

**Comment by RainerKlute** [comment]
This is working now.

**Comment by BeckmaR** [comment]
Cannot confirm, still broken as tested just now and reported by @rherrmannr in #1734.

**Comment by svenjawendler** [comment]
With 3.1.1. there is a problem regarding the rename refactoring feature. How to reproduce:
Select an interface within the definition section
Select Refactor - rename in the context menu
In the text field write the new name and click OK
Expectation: every occurence of the interface name will be renamed
Current result: the source name, the interface name is not renamed (< problem), other occurences are
