### ISSUE TITLE
Rework tutorial structure

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#663]
Please note: This issue has been split into two different one: this one and issue #684.

The "comprehensive tutorial" that is probably the first thing a user will read before downloading the tool is very long and detailed (as the word comprehensive suggests). For creating a statechart with two states, this gives the impression of a complicated and hard to use tool.

Especially with the need to give some personal data (email, name, etc.) before downloading the tool, we should give the potential user a good first impression on how the tool looks like when he visits the online documentation and tutorials.

For this I suggest the following:
* Add a 5 minutes tutorial:
  * import light switch example
  * start simulation
  * create sgen file for code generation
* Add a more detailed consistent example
  * The problem of the comprehensive example is that is uses different models for modeling/simulation (light switch) and code generation (call handling). We should use one model throughout the whole tutorial. I would suggest the call handling example as it shows a bit more of SCT's possibilities.
* Some parts of the comprehensive example can be moved to the (non-tutorial-like) documentation part (editing features, simulation).

**Comment by andreasmuelder** [comment]
Divided into separate tickets, close if 5 minutes tutorial is completed
