### ISSUE TITLE
Small Mistake in the Documentation

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#673]
In "The statechart language", part 1.2.5 Exit, it is stated a transition can specify an Exit, so it is taken when that exit is taken as well. The syntax is stated as 

> `# exit-point-1 < [ exit-point-2 < ]…`

Later, the syntax is with an '>' sign instead of '<':

> - If the `>` character is to the right of a name, like in `exit_name>`, that name denotes an exit.
- If the `>` character is to the left of a name, like in `>entry_name`, that name denotes an entry.

 It seems like the second case seems to be the correct one.

**Comment by RainerKlute** [comment]
@BeckmaR, thanks for pointing this out! The bug will be fixed with pull request #674.
