### ISSUE TITLE
Improve feature structure

### ISSUE THREAD

**Issue by jdicks** [Yakindu/statecharts#676]
To get the possibility to integrate the SCT features with less dependencies as possible the org.yakindu.sct-feature should be seperated into logical senseful parts. This will give the opportunity to ship subsets of features to end users and lead in more robust integration scenarios.

starting point will be plugins of 'org.yakindu.sct-feature'

suggestion for resulting features: 
* **org.yakindu.sct.compare-feature**
  * plugins 
    * org.yakindu.sct.compare
* **org.yakindu.sct.editor-feature**
  * plugins
    * org.yakindu.sct.ui.editor
    * org.yakindu.sct.refactoring
    * org.yakindu.sct.model.sgraph
    * org.yakindu.sct.model.sgraph.edit
    * org.yakindu.sct.model.sgraph.ui
    * org.yakindu.sct.model.stext
    * org.yakindu.sct.model.stext.edit
    * org.yakindu.sct.model.stext.ui
    * org.yakindu.sct.domain
    * org.yakindu.sct.ui ( divide into model and simulation UI) 
    * org.yakindu.sct.ui.navigator
    * org.yakindu.sct.domain.generic
* **org.yakindu.sct.simulation-feature**
  * plugins
    * org.yakindu.sct.model.sexec
    * org.yakindu.sct.simulation.core
    * org.yakindu.sct.simulation.core.sexec
    * org.yakindu.sct.simulation.ui
    * org.yakindu.sct.simulation.ui.sexec
    * org.yakindu.sct.model.sexec.edit
* **org.yakindu.sct.generator-feature**
  * plugins
    * org.yakindu.sct.generator.core
    * org.yakindu.sct.model.sexec
* **org.yakindu.sct.generator.model-feature** (#32)
  * plugins
    * org.yakindu.sct.model.sgen
    * org.yakindu.sct.model.sgen.edit
    * org.yakindu.sct.generator.genmodel
    * org.yakindu.sct.generator.genmodel.ui
* **org.yakindu.sct.documentation-feature**
  * plugins
    * org.yakindu.sct.examples
    * org.yakindu.sct.documentation
 * org.yakindu.sct.ui.intro

**Comment by andreasmuelder** [comment]
Feature dependencies:
org.yakindu.sct.compare-feature -> org.yakindu.sct.editor-feature
org.yakindu.sct.simulation-feature -> org.yakindu.sct.editor-feature
org.yakindu.sct.generator.c-feature -> org.yakindu.sct.generator-feature
org.yakindu.sct.generator.cpp-feature -> org.yakindu.sct.generator-feature
org.yakindu.sct.generator.java-feature -> org.yakindu.sct.generator-feature

**Comment by andreasmuelder** [comment]
Check how to keep updatebility

**Comment by jdicks** [comment]
To avoid breaking updates the sct.feature will remain in the product for at least one version. It includes the new features so updates will be executed as expected. 
Once the sct.feature is removed updating from older versions without updating to a version including the sct.feature will fail and a clean installation will be necessary.

Added a manual test to our test plan.
