### ISSUE TITLE
Documentation does not explain state actions

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#690]
In the documentation, state actions are used many times, for example in "The Statechart language 1.2.11 - Shallow History", where the entry in a state or exit out of it can trigger actions, like setting variables etc.. These are not explained at all. A normal finite state machine can only have those actions on the transitions, and I would consider it a real feature of SCT to have those - but what is not documented does not exist.
### Solution:
- Explain that this is possible at all, ideally before chapter 1.2.11 of the statechart language
- Explain and document the "Entry / <actions>" and "Exit / <actions>" syntax, and how these can be combined
- In general, explain the preset keywords better. Which exist? E.g. entry, exit, after... Case sensitivity?

**Comment by RainerKlute** [comment]
Fixed with pull request #911.
