### ISSUE TITLE
Implement Choice behavior (static / dynamic)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#70]
```
The behavior of Choices in SCT doesn't work at the moment (dynamic is default).

The SCTUnit test "StaticChoice.sctunit" implements a test for this feature. At 
the moment it's outcommented.

This feature has be implemented by the Execution Model Transformation.
```

Original issue reported on code.google.com by `A.Muel...@googlemail.com` on 17 Nov 2014 at 2:37

**Comment by terfloth** [comment]
static choices are much more complicated

Disable choice for static and dynamic property

**Comment by andreasmuelder** [comment]
Choice Kind Property Section disabled for M23 - scheduling this to backlog since static and dynamic behavior are not yet implemented.

**Comment by andreasmuelder** [comment]
Seems that this feature is not requested for our users - closing
