### ISSUE TITLE
Introduce maven toolchain to ensure xtend compiler produces java 7 compatible code

### ISSUE THREAD

**Issue by jdicks** [Yakindu/statecharts#702]
While analyzing #648 it was observed that building SCT produces java 8 based code when compiling xtend. Further information was given by xtend commiters [here](https://groups.google.com/forum/m/#!topic/xtend-lang/anRox6rEGLs).

Even if configurating jenkins to use a JDK 7 for build execution solves this issue for now, using maven toolchains would be a more robust solution to ensure extend compiler produces java 7 compatible code.

How maven toolchains can be configured is explained [here](http://maven.apache.org/guides/mini/guide-using-toolchains.html).

**Comment by andreasmuelder** [comment]
Not needed anymore since we are building with a matrix build against JDK 7 and 8
