### ISSUE TITLE
Wrong task type for TODO and FIXME

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#706]
According to https://github.com/Yakindu/statecharts/blob/master/specification/Req.SCT.Editor.TodoAndFixmeTasks.md, the type of tasks originating from statecharts must be "SC Task" or "Statechart Task".

However, it is "Xtext Task".

**Comment by svenjawendler** [comment]
This feature does not work anymore :(

**Comment by jdicks** [comment]
Seems that this is leading into the impossibility to jump to TODOs & FIXMEs by double-clicking within the task view. Technically the issue type is used to ensure a parameter for the notation element is set on the issue/marker.

**Comment by andreasmuelder** [comment]
fixed with PR #1711
