### ISSUE TITLE
Icon missing in welcome page integration

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#710]
the specification for the content extension does not work in swt mode:
```xml
<group style-id="content-group" id="yakindu-introLink-group">
			<link label="YAKINDU Statechart Tools" url="http://statecharts.org"
				id="yakindu-dokumentation-Link" style-id="content-link">
				<img id="logo_small" style-id="logo_small" src="img/logo_small.png"></img>
				<text>Learn more about YAKINDU Statechart Tools...
				</text>
			</link>
		</group>
```
The img tag should be replaced by an alt style, see JDT for example.

**Comment by RainerKlute** [comment]
Couldn't reproduce the bug: the icon is always there. Neverthelesse I fixed some labels and had the "Tutorials" link indeed point to the tutorials, see pull request #768.

**Comment by andreasmuelder** [comment]
@RainerKlute this seems to be platform dependent. The bug is on windows with an installed SCT via update site.

**Comment by RainerKlute** [comment]
Sigh! So I'll have to set up a development environment under Windows …

**Comment by andreasmuelder** [comment]
We have do provide an alt-style, see for example the JDT
https://github.com/eclipse/eclipse.jdt/blob/master/org.eclipse.jdt/intro/migrateExtensionContent.xml

**Comment by RainerKlute** [comment]
Okay, there's something on the issue_#710_welcome branch now that you can test, @andreasmuelder.

**Comment by RainerKlute** [comment]
Styling and logo presentation improved.

**Comment by RainerKlute** [comment]
Sucessfuly tested on Windows 7, @andreasmuelder.

**Comment by RainerKlute** [comment]
I found a way to enter SWT mode. Eclipse must be run with the following properties:
-Dorg.eclipse.swt.browser.DefaultType=mozilla
-Dorg.eclipse.swt.browser.XULRunnerPath=null
This brings up SWT mode on Windows. On Linux, however, the welcome page is completely blank.

**Comment by RainerKlute** [comment]
Tested and fine-tuned, see pull request #797.
