### ISSUE TITLE
Generate online documentation

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#713]
A process has to be set up to generate and publish the YAKINDU Statechart Tools documentation automatically to https://www.itemis.com/en/yakindu/statechart-tools/documentation/ resp. https://www.itemis.com/en/yakindu/statechart-tools/documentation/tutorials

**Comment by andreasmuelder** [comment]
Divide this task into different tickets

**Comment by RainerKlute** [comment]
Continuing in PRO.
