### ISSUE TITLE
assignment in guards is possible and ends up in Code Generator Error

### ISSUE THREAD

**Issue by t00manysecretss** [Yakindu/statecharts#718]
By using an Assignment in Guards the Java Code Generator creates an error in the _statemachinename_.java file.

![choise](https://cloud.githubusercontent.com/assets/19646660/15645847/0a7d6a40-265b-11e6-9f15-e894ab9870d9.png)
![error in code generator](https://cloud.githubusercontent.com/assets/19646660/15645846/0a7abb24-265b-11e6-8f23-5f6af6d36cfa.png)

Error Message: Cannot return a void result

**Comment by tkutz** [comment]
Fixed with pull request #729
