### ISSUE TITLE
Extend Flow Optimizer to cover entry and exit actions of statechart

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#72]
```
Extend Flow Optimizer to cover entry and exit actions of statechart
```

Original issue reported on code.google.com by `A.Muel...@googlemail.com` on 17 Nov 2014 at 2:43

**Comment by terfloth** [comment]
We have to implement a more intelligent inlining strategy. Thus we move this issue to M23

**Comment by terfloth** [comment]
Entry and exit action functions are only called once each.  So the sequences for entry and exit actions of the statechart should always be inlined.
