### ISSUE TITLE
Maintain sct.base feature dependencies

### ISSUE THREAD

**Issue by jdicks** [Yakindu/statecharts#725]
During #676 the sct-feature was seperated into editor, generator, documentation, generator.model & simulation features.
the old sct feature includes the new once so the possibility to update will be ensured.

The seperated features need an explicit dependency to the sct.base feature to ensure a single feature installation will complete successfully. So each new feature should be proved with repsect to the need of ia feature dependency to the sct.base feature.

**Comment by tkutz** [comment]
For the upcoming 2.6.2 release, the new features are first deactivated from the update site.
