### ISSUE TITLE
Manual event trigger fails for second invocation

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#726]
Consider following statechart:

![bildschirmfoto 2016-06-01 um 14 21 09](https://cloud.githubusercontent.com/assets/2589669/15709263/1e8d71b0-2804-11e6-9698-2e64e14fcc7f.png)

When clicking on "e" in simulation view the state change happens correctly. When state A is active again, another click on event "e" does not trigger a state change.

When changing the event value manually by inserting "1" again into the text field, it works fine.

It seems like the label in the simulation view is not updated after an event has been consumed.

**Comment by tkutz** [comment]
Fixed with pull request #851.

**Comment by tkutz** [comment]
This does not work for events with a type that does not have a default value (e.g. externally defined enumerations).

**Comment by andreasmuelder** [comment]
@tkutz is this fixed?

**Comment by tkutz** [comment]
This is fixed with pull request #1013
