### ISSUE TITLE
Enhance documentation for entry and exit points

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#73]
```
Enhance documentation for entry and exit points
```

Original issue reported on code.google.com by `A.Muel...@googlemail.com` on 17 Nov 2014 at 2:44

**Comment by RainerKlute** [comment]
Fixed in "userdoc_structure_2.0" branch, not in master.

**Comment by RainerKlute** [comment]
Fixed with pull request #356.
