### ISSUE TITLE
Statecharts are not scaled correctly with Windows DPI Settings

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#735]
150% DPI setting, incorrect scaling:
![150% DPI setting, incorrect scaling](https://cloud.githubusercontent.com/assets/15799654/15776916/b3432380-298b-11e6-955b-410d07c6f35c.PNG)
100% DPI, normal scaling:
![100% DPI, normal scaling](https://cloud.githubusercontent.com/assets/15799654/15776917/b35ce356-298b-11e6-8c57-c5dfeff796c8.PNG)

When the screen DPI settings in Windows are changed, the text size and the box size in a statechart view is changed, but the position is not. This leads to overlapping states and subcharts and everything. This might be an issue when multiple developers try to work on the same statechart with different screens (I increased the DPI setting because of my 4K screen).
1. Open any statechart with normal DPI settings, check correct look.
2. Save your current work, you'll need to logout later
3. In Win7, right click on desktop, change display settings, go to "make display elements and text larger or smaller" (or similar)
4. Increase DPI setting from 100% to 150%
5. Logout as requested, login, open SCT, open same statechart
6. (Reset DPI setting and logout and login again)

Screenshots attached.

**Comment by BeckmaR** [comment]
Note: It looks like the boxes are not scaled at all; some only grow because text is enlarged and needs more lines now.

**Comment by andreasmuelder** [comment]
I can not reproduce this with Windows 10. Can someone confirm that this does not happen on Windows 10?

**Comment by BeckmaR** [comment]
Looks like Microsoft has fixed something in their graphics libraries then. This would probably mean there isn't much we can do about this behavior on Win7 (Win8?) anyways...

**Comment by andreasmuelder** [comment]
This is still an issue on windows 10. The problem is that the Font is adjusted and thus the preferred size of a State is different. The only solution I see here is to avoid font scaling in statechart diagram and use the zoom instead.

This font adjusting must be provided as an option since we do not want to change the layout for existing diagrams modeled with DPI scaling enabled.

**Comment by andreasmuelder** [comment]
Add documentation and close
