### ISSUE TITLE
Update EPL Licence Text

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#745]
The Software User Agreement in SCt features is from April 14, 2010.
the latest Agreement published from eclipse is from April 9, 2014.

the result is an update licence dialog with 2 different user agreements:
![lua](https://cloud.githubusercontent.com/assets/6338708/15853034/b766d572-2ca3-11e6-939e-2e6509ecf167.png)

**Comment by andreasmuelder** [comment]
@DominikTesch I merged the PR into the master, please retest this with the update site

**Comment by DominikTesch** [comment]
Fixed #750
