### ISSUE TITLE
Statechart name can contain whitespace, source generator doesn't accept it

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#757]
Using whitespace in the statechart name field is not marked as Error, but the generated *.sgen file marks it as such. In short, using whitespace in the statechart name makes it impossible to generate source from it, but the editor allows it.
See example "coffee machine".

**Comment by andreasmuelder** [comment]
We should add a validation constraint that the statechart name must conform to an ID rule. (No whitespace, must not start with numbers, etc.)
