### ISSUE TITLE
Add comments to c generated files (edit this / don't edit)

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#763]
The file sc_types.h is made to be edited by the user, while other files like statechart.h and statechartRequired.h are not. This is not made clear by contained comments, a big header comment with generation time, used statechart etc might be useful in general.

**Comment by andreasmuelder** [comment]
files that should not be edited by the user are marked as derived that forces a warning. they are also not generated into the same folders, I think this is sufficient.
