### ISSUE TITLE
Wrong paths generated in c header file

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#764]
The default setting for the C generator is to generate statechart.c, statechart.h and statechartrequired.c in a "src-gen" folder, and sc_types.h in a "src" folder. The build then fails because statechart.h uses
`#include "sc_types.h"`
instead of
`#include "../src/sc_types.h"`,
so that sc_types can't be found. (At least with the arduino compiler)

**Comment by terfloth** [comment]
An't reproduce this issue on the master branch.

**Comment by terfloth** [comment]
@BeckmaR : did you mean the C++ code generator?

**Comment by BeckmaR** [comment]
No, the issue was in the C generator, but I can confirm the issue is solved.
