### ISSUE TITLE
Simulation does not accept real values

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#770]
When running a simulation, setting real variables to real values does not work.
- Initial value is displayed as 0.0
- Changing the value to something like 0.7, 1.3 is not accepted, 0.0 is displayed again
- Changing the value to 1, 2 or 3 does work, new value is displayed WITHOUT decimal point
- Typing '0,3' with comma instead of decimal point doesn't work either, localisation issue unlikely.
- Same issue exists with operations that return real values, not only real variables

**Comment by tkutz** [comment]
Regression was introduced with pull request #369 (for issue #329)

**Comment by tkutz** [comment]
Fixed with pull request #775
