### ISSUE TITLE
Make properties view visible by default

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#771]
The standard view has the Problems Tab in focus instead of the Properties tab. Change this so that users actually see that there is a properties tab, I learned about it while doing the test plan.

Additional idea:
Focus the problems view when problems are available, focus back to properties when there are no problems.

**Comment by terfloth** [comment]
This issue is very valid. We should also think about view arrangement in the Statechart perspectives. Nevertheless this issue requires more detailed specification.

**Comment by BeckmaR** [comment]
Original issue fixed with PR #966
