### ISSUE TITLE
File a bug: Make sure JDT finds a JRE

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#783]
Under certain circumstances JDT does not find even a single JRE, i.e. the list of installed JREs is empty. However, since Eclipse has been started successfully, at least one JRE is necessarily installed somewhere.

**Comment by andreasmuelder** [comment]
Please file a bug in JDT issue tracker

**Comment by andreasmuelder** [comment]
@RainerKlute did you file a bug?

**Comment by RainerKlute** [comment]
Bug filed as https://bugs.eclipse.org/bugs/show_bug.cgi?id=499352.
