### ISSUE TITLE
Inside state comments view in C and C++ code before  method 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#79]
```
Below I have attached a state with comments.I just need that comments before 
the 
method like this-

//My comments
void func1(int a)
```

Original issue reported on code.google.com by `adnanrab...@gmail.com` on 26 Nov 2014 at 3:23

Attachments:
![state_with_comments](https://cloud.githubusercontent.com/assets/12081541/8671977/f27d5032-2a29-11e5-8227-1d271f73ebd1.png)

**Comment by terfloth** [comment]
State name usage is not valid.
