### ISSUE TITLE
Remove 'examples/traffic_light_arduino'

### ISSUE THREAD

**Issue by jdicks** [Yakindu/statecharts#793]
as .elf is a binary format it isn't well compareable and mostly marked as changed when using git/eGit.

Further the whole folder 'traffic_light_arduino\Release' is a majorly platform dependant result and therefore should not be present in the repository.

**Comment by andreasmuelder** [comment]
@jdicks can you file this in the new Yakindu/examples repository, all examples contained inYakindu/statecharts will be deleted soon.

**Comment by jdicks** [comment]
see https://github.com/Yakindu/examples/issues/1

**Comment by jdicks** [comment]
@BeckmaR will take over the issue in example repository. i will delete the sample from statechart repository.
