### ISSUE TITLE
Ordering issue when creating new .sgen

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#796]
When creating a new sgen file with multiple statecharts to choose from, the sort order is weird.
![createsgenorder](https://cloud.githubusercontent.com/assets/15799654/16409356/617fd96c-3d1d-11e6-93ec-8639e0a77426.PNG)
This order is neither alphabetical nor based on the file creation time. Alphabetical order would be nice.

**Comment by terfloth** [comment]
The order should be the same as in the project explorer.

**Comment by BeckmaR** [comment]
It is not.

![bildschirmfoto vom 2016-09-20 16-16-07](https://cloud.githubusercontent.com/assets/15799654/18673861/a08a6e70-7f4d-11e6-83ee-4d0e4145806d.png)
