### ISSUE TITLE
Package http://www.yakindu.org/base/base/2.0.0 is registered twice

### ISSUE THREAD

**Issue by jdicks** [Yakindu/statecharts#799]
It seems the http://www.yakindu.org/base/base/2.0.0 package will be registered twice. It is suspcious that both registrations come from the same source 'org.yakindu.base.types'.

It seems there aren't functional impacts.

On startup the following warning is shown. It is visible in the runtime error log also.
!MESSAGE Both 'org.yakindu.base.types' and 'org.yakindu.base.types' register a package for 'http://www.yakindu.org/base/base/2.0.0'

**Comment by andreasmuelder** [comment]
Seems to be that the generated epackage is registered twice in the plugin.xml 
https://github.com/Yakindu/statecharts/blob/master/plugins/org.yakindu.base.types/plugin.xml

**Comment by andreasmuelder** [comment]
Fixed with PR #810
