### ISSUE TITLE
Interpreter does not process transitions without trigger.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#80]
```
What steps will reproduce the problem?
1. Create a statechart and add an (initial) state A 
2. Add a with a transition without trigger to state B
3. Simulate the statemachine
4. State B won't be reached

What is the expected output? 
* state B should be reached 

```

Original issue reported on code.google.com by `AxelTerfloth` on 5 Jan 2015 at 11:05
* Blocked on: #81

**Comment by bohl-itemis** [comment]
This change causes regression with exit points. Three tests fail: 

- ExitState.namedExitThroughNamedTransition
- ExitState.remainInA
- **HistoryWithExitPoint.historyEntryAfterExit**

Statechart:
![issue_80_regression](https://cloud.githubusercontent.com/assets/12081541/8772885/fdcfb3da-2ecf-11e5-87d3-dbda0dfd9fc6.PNG)

Test:
![issue_80_regression_02](https://cloud.githubusercontent.com/assets/12081541/8772906/41128d16-2ed0-11e5-833c-382db9ba0ed6.PNG)

**Comment by terfloth** [comment]
The described behavior is correct. There is a validation in place that indicates a warning and a solution approach.
