### ISSUE TITLE
Refactoring composite state to subdiagram does not work when CS already contains another SD - class cast exception

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#802]
Doing the above produces the errors listed in the uploaded file (class cast exception)
[exception.txt](https://github.com/Yakindu/statecharts/files/343524/exception.txt).
Reproduce via:
1. open digital_watch example
2. Refactor composite state "stop watch" contained in "Regular" into subdiagram (works)
3. Try to refactor big composite state "Regular" into subdiagram, nothing happens, only Exception in Error log
Doing Step 3 without Step 2 beforehand works.

**Comment by BeckmaR** [comment]
I was not able to reproduce this in SCT 2.6.2, might have been fixed before. @andreasmuelder should close this if not able to reproduce either.

**Comment by andreasmuelder** [comment]
Not able to reproduce this
