### ISSUE TITLE
Undo doesn't work with "Refactor -> Extract subdiagram"

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#803]
Doing so throws a BasicIndexOutOfBoundsException
[exception.txt](https://github.com/Yakindu/statecharts/files/343547/exception.txt)
To reproduce, open the digital_watch example, refactor the composite state "SetTime", and undo.

**Comment by BeckmaR** [comment]
Could not reproduce in a new statechart, but this issue happens with all composites in digital watch

**Comment by BeckmaR** [comment]
Still happens after update to newest SCT version 2.6.2

**Comment by andreasmuelder** [comment]
This happens, when a Composite State is extracted that has incoming or outgoing transitions to another state which are refactored to entry or exit points.

**Comment by tkutz** [comment]
Fixed with pull request #858.
