### ISSUE TITLE
NPE when calling "Generate Code Artifacts"

### ISSUE THREAD

**Issue by wendehals** [Yakindu/statecharts#827]
When calling "Generate Code Artifacts" from navigator contect menu an a closed sgen resource, following NPE is thrown:

java.lang.NullPointerException
    at org.yakindu.sct.generator.core.GeneratorExecutor.getGenerator(GeneratorExecutor.java:93)
    at org.yakindu.sct.generator.core.GeneratorExecutor.executeGenerator(GeneratorExecutor.java:68)
    at org.yakindu.sct.generator.core.GeneratorExecutor$1.run(GeneratorExecutor.java:55)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

The sgen file hasn't been opened before.

**Comment by andreasmuelder** [comment]
I can only reproduce this when the project the .sgen file is contained in does not have the xtext nature. I
Maybe we should handle this in a more user-friendly way instead of throwing a NPE.

**Comment by wendehals** [comment]
Ok, I agree, I only encounter the problem when the project has no xtext nature. Somehow my projetcs were misconfigured. It works now for me.

**Comment by andreasmuelder** [comment]
We should add a check in the SCTBuilder if the xtextNature is present. If not we should do nothing.
In the GenerateAction, we should show up the dialog if the user wants to add the XTextNature as in StatechartDiagramEditor#checkXTextNature

**Comment by terfloth** [comment]
Derive tasks and close this issue ....

**Comment by BeckmaR** [comment]
Closing, followup in #1439
