### ISSUE TITLE
"Link with Editor" does not work

### ISSUE THREAD

**Issue by wendehals** [Yakindu/statecharts#829]
The navigator feature "Link with Editor" does not work with sct files.

**Comment by andreasmuelder** [comment]
@wendehals I can not reproduce this behavior, it is working as expected for me. Can you provide some more details? Which view does not link? The Project Navigator or Package Explorer? Which version are you using?

**Comment by wendehals** [comment]
I'm using SCT 2.6.2. But actually I also can not reproduce the problem anymore. I used the C pespective but it works fine now.

**Comment by andreasmuelder** [comment]
OK, I will close this issue then. Please reopen if this happens again.

**Comment by wendehals** [comment]
The problem encounters when the scp file is already opened when eclipse starts and the navigator tree is initially collapsed .
