### ISSUE TITLE
Copying region produces graphic errors

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#831]
How to reproduce:

Select main region, copy and paste.

You get some graphic errors like this:

![staircase](https://cloud.githubusercontent.com/assets/15800400/16834139/c5c10ff8-49b2-11e6-89d9-2e65960f697a.jpg)

**Comment by BeckmaR** [comment]
Could reproduce, possibly related to #99?

**Comment by svenjawendler** [comment]
I cannot reproduce it any more. Close it?

**Comment by BeckmaR** [comment]
Issue doesn't seem to be fixed according to #1527.

**Comment by BeckmaR** [comment]
Another report: #1639

**Comment by andreasmuelder** [comment]
closing as duplicate

**Comment by BeckmaR** [comment]
This issue still persists, all other issues related to this are closed, reopening
