### ISSUE TITLE
Performance issue: Validation slows down for large models with many interface elements

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#846]
Large statecharts with many interface elements cause long running validations that interrupt the user during modeling. In the first step profile an appropriate scenario.

**Comment by andreasmuelder** [comment]
One performance issue is the calculation if the ID attribute, I created a separate ticket for this. Affected versions are 2.6.2 and 2.7.0. #848

**Comment by andreasmuelder** [comment]
An option to disable the live validation is now available under Window/Preferences/YAKINDU SCT/Diagram Appearance
