### ISSUE TITLE
Split sc editor and interface editor in multipage editor

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#849]
Currently, the interface declaration is a textfield inside of the graphical editor. This solution has certain advantages and drawbacks.
Pro:
- The interface declaration and the statechart can be seen simultaneously side by side. Elements in the statechart can easily be referenced in the interface declaration.
- The statechart and the interface declaration can be printed at once.

Con:
- The intferface declaration isn't edited in a real text editor, the text field needs to be double clicked to edit it, the whole text moves a bit when activating the editing mode, and editing feels sluggish. All in all, it feels like editing a text label in photoshop or similar.
- The interface text label doesn't have line numbering
- Scrolling inside of the text label is not possible, the whole statechart needs to be scrolled, which turns awkward for huge statecharts

It's also questionable if one really needs to see both the statechart and the declaration. All in all, the statechart pretty much speaks for itself - all events / variables of an interface are prefixed with the interface name anyways, it's clearly visible if an interface is an _in_\- or an _out_-event, and the type of variables can be deferred by usage or maybe via tooltip on hover. Also, I wouldn't want to print the statechart declaration on the same page as the diagram itself, because it's hard to fit a bigger statechart on a standard page anyways without losing information.

So, moving the interface declaration inside of another tab with a real text editor seems to be a better solution than the current one all in all, except for very tiny statecharts. An option to show both tabs side by side or to undock the editor would be nice, if this is possible with eclipse.

**Comment by andreasmuelder** [comment]
This is fixed via  #1151
