### ISSUE TITLE
[SCTCompare] Text Compare also should be shown in diagram

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#85]
```
When selecting a change in text mode only the changes in text are shown.

A additional graphic, which shows the graphical effect of the change, would be 
useful. At the moment you only can choose either or.
```

Original issue reported on code.google.com by `b...@itemis.de` on 27 Jan 2015 at 10:16

Attachments:
![diagramm](https://cloud.githubusercontent.com/assets/12081541/8673154/90243346-2a34-11e5-9f84-28e0a1de61ab.PNG)
![text](https://cloud.githubusercontent.com/assets/12081541/8673157/91df9428-2a34-11e5-8174-b3a9f3372d7a.PNG)

**Comment by andreasmuelder** [comment]
we can't fix this since we reuse GMF and EMF compare here...
