### ISSUE TITLE
[SCTCompare] Transition target change should be shown in diagram

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#86]
```
In the diagram view not every change is visualised.

A transition target change shows the textual view only, see pictures.
```

Original issue reported on code.google.com by `b...@itemis.de` on 27 Jan 2015 at 10:58

Attachments:
![diag](https://cloud.githubusercontent.com/assets/12081541/8673164/a6f854ee-2a34-11e5-9eab-b7685fc37eeb.PNG)
![text](https://cloud.githubusercontent.com/assets/12081541/8673165/a854c25a-2a34-11e5-81ee-47bbe7fb4d72.PNG)

**Comment by andreasmuelder** [comment]
closing as invalid
