### ISSUE TITLE
Pro icon covers text

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#874]
![unbenannt](https://cloud.githubusercontent.com/assets/15800400/17395648/d9ab3a88-5a2f-11e6-9ae0-5c36d6997930.png)

**Comment by RainerKlute** [comment]
Works for me. This is probably an OS-specific issue we can't fix anyway.

![screenshot](https://cloud.githubusercontent.com/assets/1495781/17474831/4b64b71e-5d58-11e6-9709-928660895466.png)

**Comment by andreasmuelder** [comment]
This seems to be an stylesheet issue that has to be fixed

**Comment by RainerKlute** [comment]
Fixed.
