### ISSUE TITLE
Using operation from proposal provider should print brackets

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#879]
When selecting an operation from proposal provider, no brackets are printed after the operation name. In case the operation has at least one parameter, we should print the brackets and put the cursor between the brackets.

**Comment by BeckmaR** [comment]
I would say the brackets / parantheses should always be printed, although it works without them if there are no arguments - but that looks pretty confusing.

**Comment by terfloth** [comment]
We explicitly decided to make brackets optional for no arg ops. So creating brackets for the case operations require parameters is valid.
