### ISSUE TITLE
[Ctrl + S] does not work in Properties View

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#880]
When editing an element in the properties view, Strg + S does not save the statechart as long as the Properties have focus. The user needs to select the statechart diagram editor to save with strg + s again.

**Comment by andreasmuelder** [comment]
This behavior is defined by the eclipse platform, there is an open issue for that:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=481640
