### ISSUE TITLE
Refactoring button is not disabled, but does nothing

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#883]
Two states, A and B, an event and a bool variable exist.
There are two transitions from A to B, both have the event as trigger, but one sets the variable to false, the other one to true. The testplan specifies Refactoring -> fold incoming actions / fold outgoing actions should be disabled (because folding is not possible), but the button is not disabled. clicking it just does nothing. (Testcase 12.10 and 12.11)

**Comment by tkutz** [comment]
Fixed with pull request #910.
