### ISSUE TITLE
Example wizard: initial layout 

### ISSUE THREAD

**Issue by jdicks** [Yakindu/statecharts#890]
If starting the example wizard it is hard to get an overview of the examples without collapsing all the nodes in visible tree, find screenshot below.

The following things might improve the current situation, see also 2nd screenshot
- collapse all top level nodes (see #926)
- select an example
- enlarge dialog dimension
- there might be a better order than an alphabetical (basic->advanced)

Current:
![sct_example_wizard_1](https://cloud.githubusercontent.com/assets/5557073/17526467/a78757ee-5e67-11e6-9468-df816b745571.PNG)

Draft initial layout:
![sct_example_wizard_2](https://cloud.githubusercontent.com/assets/5557073/17526496/c389a488-5e67-11e6-81f6-9c9ec44b54a4.PNG)

**Comment by terfloth** [comment]
This tasks is mainly about the usability of the example wizard. We should derive different tasks from this issue:

- implement basic improvements like collapsing top level nodes
- Apply a usability tests to this feature.

**Comment by andreasmuelder** [comment]
Not required since we provide the examples as flat list
