### ISSUE TITLE
Example Wizard: Add option to show flat list of all examples

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#891]
Currently, examples are sort by category, but since an example has multiple categories, they all appear multiple times. This is confusing.

Solution A:
- Provide radio button to switch between "sort by category" and "sort by name". The second option would then just show all the examples sorted alphabetically (see also #890 )

Solution B:
- Provide checkbox "Show categories". If enabled, we get the current behavior, if disabled, examples are only shown with their names and not categorized

**Comment by terfloth** [comment]
As there are other options for handling n:m relation between categories and examples and as it is basically a usability issue we should derive UX tasks.

**Comment by andreasmuelder** [comment]
for the next release we will show a simple flat list. This is sufficient for ~8 example projects.
