### ISSUE TITLE
Model tab should bind to the canvas

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#906]
The statechart editor displays the _Model_ tab in the _Properties_ if the user selected the model's definition section.

This is not intuitive. The _Model_ tab should also be displayed if the user selects the canvas (background) resp. selects nothing at all.

**Comment by SimonEit** [comment]
From what i understand the Model tab is context senstive, i.e. if i select a region the Model tab contains the Region Name. If i select the specification section, the Model tab contains the Statechart Model informations. With that context-sensitive-paradigm in mind it seems okay, to hide the Model tab when "nothing" is selected.

Please reopen the ticket if you disagree @RainerKlute
