### ISSUE TITLE
Wrong software update sites (old Mars URLs)

### ISSUE THREAD

**Issue by wendehals** [Yakindu/statecharts#909]
YAKINDU SCT 2.7.0 is based on Neon but the software updates sites set up in the preferences still refer to Mars. These are:
http://download.eclipse.org/releases/mars
http://updates.yakindu.org/sct/mars/releases/

This causes updates to be failing.

**Comment by andreasmuelder** [comment]
Fixed with 97851fb769d919aa1ee8e3ac99664d64f588c261
