### ISSUE TITLE
Design smell in IGenArtifactConfigurations API

### ISSUE THREAD

**Issue by wendehals** [Yakindu/statecharts#912]
The interface org.yakindu.sct.generator.c.IGenArtifactConfigurations there is a method

List<GenArtifactConfiguration> getConfigurations();

that has a design smell. The type parameter GenArtifactConfiguration of the returned list is actually an inner class of org.yakindu.sct.generator.c.GenArtifactConfigurations that implements IGenArtifactConfigurations. Thus, there is no real decoupling between the interface and its implementation.

Consider to create an interface IGenArtifactConfiguration for the type parameter of the getConfigurations() method.

**Comment by tkutz** [comment]
Ok I see, will keep that in mind when refactoring the generators anyways.

**Comment by andreasmuelder** [comment]
done with PR #921
