### ISSUE TITLE
Documentation regarding transit sequence is wrong

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#918]
The documentation states:

9.2.4 Events specification:
      "entry - State has just become active."

9.2.3.1 Fundamental statechart methods:
       "3. If a state change has to be done:
                        1. Execute exit actions of the present state.
                        2. Save history state, if necessary.
                        3. Make the new state active.
                        4. Execute entry actions of the new state."

The actual sequence for a transition from A -> B is

1. mark A inactive
2. perform exit actions of A
3. perform transition actions
4. perform entry actions of B
5. mark B active

**Comment by RainerKlute** [comment]
Where's saving the history state in your sequence, @terfloth?

**Comment by RainerKlute** [comment]
Fixed with pull request #920.
