### ISSUE TITLE
Diagram validation during live validation

### ISSUE THREAD

**Issue by tkutz** [Yakindu/statecharts#928]
During live validation, the diagram seems to get also validated which results in undesired error messages, like "Duplicate style 'isHorizontal'".

To reproduce: Create a statechart with two states and produce an error message. While the statechart is dirty, the mentioned error message appears. On save, they disappear.

Probably related to recent refactoring in domain infrastructure. Seems like SCTResourceValidatorImpl is not bound where ever it is needed.

**Comment by andreasmuelder** [comment]
Fixed with PR #938
