### ISSUE TITLE
Do not generate unused functions for Java / C Code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#95]
```
The generated code should be without warnings.
```

Original issue reported on code.google.com by `A.Muel...@googlemail.com` on 12 Feb 2015 at 3:23

**Comment by nyssen** [comment]
For the C generator, this also leads to a violation of HIS metric STST3.

**Comment by terfloth** [comment]
All empty functions except for possible empty state reacts are eliminated.
