### ISSUE TITLE
Documented but unimplemented sgen-features

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#951]
The new test introduced with PR #950, according to issue #946, finds two features in the generator documentation that are not actually implemented:
* `JUnitWrapper`, doc says it's a feature of the CPP generator, but seems to be a sctunit generator feature (that's what @muehlbrandt said)
* `Template`, feature of the XPAND generator, most likely removed by @tkutz in 027c62c

**Comment by tkutz** [comment]
Fixed with https://github.com/Yakindu/statecharts/commit/acab338f0358167ed46e8f1bf09a08836060a4e8
and https://github.com/Yakindu/statecharts/commit/027c62cdf6c0f6cb0cd07b6ab2a1c4edc9a29de4
