### ISSUE TITLE
Images in the comprehensive tutorial are not sized well

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#963]
I don't know why, but this looks off. Maybe the text should not wrap around the images? Or maybe we should use a tabular design in chapters where many images are used, so that text is in the left column and images on the right, but in a more balanced way (e.g. center images horizontally and vertically, text only vertically).

![documentation](https://cloud.githubusercontent.com/assets/15799654/18381415/61687810-767c-11e6-904e-39574b23489a.PNG)

**Comment by RainerKlute** [comment]
Improved with pull request #970. If you have any specific wishes, please let me know!
