### ISSUE TITLE
Using the colorpicker for statechart colors makes SCT lose focus

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#986]
- Open a statechart, select a state
- In the properties tab, go to Appearance
- Click on the icon in the middle to change the color of the state text
- Click on "Custom...". Focus changes to another window, color picker still comes up in SCT.

Seen on Windows, master branch.

**Comment by svenjawendler** [comment]
This bug still exists: 2.05.2017

**Comment by andreasmuelder** [comment]
Closing this as an External Bug in SWT Color Picker control.
