### ISSUE TITLE
Transition label missing after refactoring to subdiagram 

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#990]
Consider the following statechart:
![s1](https://cloud.githubusercontent.com/assets/1495781/18670756/a9784234-7f41-11e6-92e6-ece3181fb216.png)
Refactoring state A and extracting a subdiagram leads to the following:
![s2](https://cloud.githubusercontent.com/assets/1495781/18670757/a978e7e8-7f41-11e6-813c-e40bb80cf66b.png)
So far, so good. However, now let's change the name of the transition's source state so that it contains a space character, e. g. by changing the name from _B_ to _B B_:
![s3](https://cloud.githubusercontent.com/assets/1495781/18670759/a97da396-7f41-11e6-9cf1-1b9e5af4118d.png)
Extracting the subdiagram now leaves the transition without any labeling:
![s4](https://cloud.githubusercontent.com/assets/1495781/18670758/a97d4f22-7f41-11e6-9f20-d1d541346107.png)

**Comment by svenjawendler** [comment]
Added test project
[bug_990.zip](https://github.com/Yakindu/statecharts/files/533768/bug_990.zip)
In the correct example there is this exit point. (see 2.sct)
![990_correct](https://cloud.githubusercontent.com/assets/22005752/19442333/4433a2b2-9489-11e6-8dfe-977cc94f6c10.png)
Here it is missing. (see 4.sct)
![990_incorrect](https://cloud.githubusercontent.com/assets/22005752/19442332/43d832e2-9489-11e6-9087-4fdf2bac504b.png)
